uktrade/lite-frontend

.gitignore
caseworker/cases/helpers/case.py
caseworker/cases/views/main.py
conf/base.py
exporter/compliance/forms.py
tests_common/api_client/sub_helpers/cases.py
tests_common/tools/helpers.py
ui_tests/caseworker/conftest.py
ui_tests/caseworker/step_defs/test_compliance.py
ui_tests/caseworker/step_defs/test_finalise_case.py
ui_tests/exporter/conftest.py
ui_tests/exporter/step_defs/test_compliance.py
ui_tests/exporter/step_defs/test_sites.py

Timezone is set to "Europe/London" and all references to datetime are updated to use localtime as per that timezone.

Ltd-136: Configure timezone correctly

---

pipeline/Jenkinsfile

created a new channel for Jenkins to send slack merge messages to.

change slack channel name

---

caseworker/search/forms.py

Queue name, team
Case officer username and email

Update filters regex with additional fields

---

core/client.py

This will fail louder so we can better understand the cause of errors

Improve error handling of hawk auth

---

caseworker/assets/javascripts/update-total-value.js
caseworker/templates/components/goods-licence-list.html
core/builtins/custom_tags.py
lite_content/lite_internal_frontend/advice.py
unit_tests/caseworker/test_template_tags.py

Fix total value calculation on approve screen

---

caseworker/cases/forms/respond_to_good_query.py
caseworker/cases/forms/review_goods.py
caseworker/cases/helpers/advice.py
caseworker/cases/services.py
caseworker/templates/case/slices/goods.html
caseworker/templates/components/goods-licence-list.html
caseworker/users/services.py
exporter/applications/forms/goods_types.py
exporter/goods/forms.py
tests_common/api_client/libraries/request_data.py
ui_tests/caseworker/conftest.py
ui_tests/caseworker/pages/goods_queries_pages.py

lite-api change needed to absorb the value inputted in the new field, but this can merge as is

Add product decision comment in context of application

---

core/assets/javascripts/govuk.js
exporter/applications/components.py
exporter/applications/forms/end_use_details.py
exporter/applications/forms/parties.py
exporter/applications/forms/route_of_goods.py
exporter/applications/forms/temporary_export_details.py
exporter/applications/views/additional_documents.py
exporter/applications/views/documents.py
exporter/applications/views/end_use_details.py
exporter/applications/views/goods.py
exporter/applications/views/parties/base.py
exporter/applications/views/parties/consignees.py
exporter/applications/views/parties/end_users.py
exporter/applications/views/parties/third_parties.py
exporter/applications/views/route_of_goods.py
exporter/applications/views/temporary_export_details.py
exporter/templates/applications/additional-documents/additional-documents.html
exporter/templates/applications/case-notes.html
exporter/templates/applications/consignee.html
exporter/templates/applications/end-user.html
exporter/templates/applications/goods-locations/goods-locations.html
exporter/templates/applications/goods/index.html
exporter/templates/applications/parties/third-parties.html
exporter/templates/layouts/base.html

also added js file that we need for the site to work, which will be ultimately removed when @eadpearce's changes are merged

Make application back button go back to correct section

---

Pipfile
Pipfile.lock
caseworker/urls.py
conf/base.py
exporter/urls.py
manifest.yml

Add healthcheck endpoint

---

exporter/templates/core/hub.html

Improve content on exporter hub when feature flag is on

---

caseworker/cases/helpers/advice.py
caseworker/cases/views/goods.py
caseworker/templates/case/slices/goods.html
unit_tests/caseworker/cases/test_views.py

Reverts uktrade/lite-frontend#61

Revert "Bug: Change ?goods to ?good_ids in get param for review goods wizard"

---

.circleci/config.yml
Pipfile
Pipfile.lock
caseworker/assets/javascripts/review-good.js
caseworker/cases/forms/review_goods.py
caseworker/cases/views/goods.py
caseworker/cases/views/main.py
caseworker/templates/case/review-good-base.html
caseworker/templates/case/review-good.html
caseworker/templates/case/slices/goods.html
caseworker/templates/includes/control-list-entries.html
conf/base.py
conf/caseworker.py
conf/exporter.py
example.caseworker.env
exporter/applications/views/documents.py
exporter/core/services.py
exporter/goods/forms.py
exporter/goods/services.py
exporter/goods/views.py
exporter/templates/core/ecju-generated-documents.html
exporter/templates/core/hub.html
exporter/templates/goods/good.html
lite_content/lite_exporter_frontend/goods.py
lite_forms/templates/form.html
lite_forms/templates/forms-errors.html
unit_tests/caseworker/cases/forms/test_review_goods.py
unit_tests/conftest.py
unit_tests/exporter/goods/test_forms.py

Feature flag goods query

---

exporter/applications/services.py
ui_tests/exporter/features/edit_open_application.feature
ui_tests/exporter/features/goods.feature
ui_tests/exporter/features/submit_open_application.feature
ui_tests/exporter/pages/add_goods_page.py
ui_tests/exporter/pages/open_application/add_goods_type.py
ui_tests/exporter/step_defs/test_goods.py
ui_tests/exporter/step_defs/test_standard_application.py
unit_tests/exporter/goods/test_forms.py

This commit makes sure the browser tests pass on latest master as they have been
broken for a while.
Also fixes small bug with the removing `,` logic that always assumes the keys
"value" and "quantity" are in the post_data.

Fix browser tests

---

caseworker/templates/case/product-on-case.html
caseworker/templates/case/review-good-standard.html
exporter/applications/urls.py
exporter/applications/views/goods.py
exporter/goods/forms.py
exporter/goods/helpers.py
exporter/goods/services.py
exporter/goods/urls.py
exporter/goods/views.py
exporter/templates/applications/goods/add-good-detail-summary.html
exporter/templates/goods/good.html
lite_content/lite_exporter_frontend/goods.py
lite_content/lite_exporter_frontend/strings.py
ui_tests/exporter/conftest.py
ui_tests/exporter/features/submit_standard_application.feature
ui_tests/exporter/pages/add_goods_details.py
unit_tests/conftest.py
unit_tests/exporter/goods/test_forms.py
unit_tests/exporter/licences/test_views.py

Change to ask sporting shotgun details.
This is asked when adding a new product to the application as well as adding it to the product list.
The question comes after firearm product type and is not applicable if it is an accessory, software/technology related to firearm.
Browser tests updated to match the updated flow.

LTD-376: Sporting shotgun frontend changes

---

exporter/applications/views/goods.py
ui_tests/exporter/conftest.py
ui_tests/exporter/features/goods.feature
ui_tests/exporter/features/submit_standard_application.feature

This attempts to fix a few tests that were broken by recent changes and also fixes a small bug uncovered by fixing these changes

LTD-392 year of manufacture browser tests

---

caseworker/templates/case/product-on-case.html

Show values from good_on_application's firearms details instead of the ones
that come from the `good` directly if available

Product-on-Case template

---

ui_tests/caseworker/conftest.py
ui_tests/caseworker/pages/goods_queries_pages.py

These used to work until the goods review wizard was introduced, this updates
the tests to work again

Fix good review.feature browser tests

---

caseworker/cases/forms/review_goods.py

LTD-456: remove question mark from label

---

caseworker/cases/services.py
caseworker/cases/views/goods.py
caseworker/templates/case/product-on-case.html
caseworker/templates/case/review-good-standard.html
core/builtins/custom_tags.py
exporter/applications/forms/goods.py
exporter/applications/services.py
exporter/applications/urls.py
exporter/applications/views/goods.py
exporter/assets/javascripts/add-good.js
exporter/core/constants.py
exporter/goods/forms.py
exporter/goods/helpers.py
exporter/goods/services.py
exporter/goods/views.py
exporter/templates/applications/goods/add-good-detail-summary.html
exporter/templates/applications/goods/goods-detail-summary.html
exporter/templates/goods/good.html
lite_content/lite_exporter_frontend/goods.py
lite_content/lite_exporter_frontend/strings.py
ui_tests/exporter/conftest.py
ui_tests/exporter/features/submit_standard_application.feature
ui_tests/exporter/pages/add_goods_details.py
unit_tests/caseworker/cases/test_views.py
unit_tests/caseworker/conftest.py
unit_tests/conftest.py
unit_tests/exporter/goods/test_forms.py

Frontend changes for Firearms section 1/2 question
- Update the flow to include firearms section question
- template and content updates
- Add views to support editing the section and details
- Fix broken unit tests and browser tests

LTD-375: [FE] Firearms Section 1-2 certificate question

---

caseworker/templates/case/product-on-case.html
caseworker/templates/case/review-good-standard.html
caseworker/templates/case/review-good.html
exporter/applications/urls.py
exporter/applications/views/goods.py
exporter/goods/forms.py
exporter/goods/services.py
exporter/goods/urls.py
exporter/goods/views.py
exporter/templates/applications/goods/add-good-detail-summary.html
exporter/templates/applications/goods/goods-detail-summary.html
exporter/templates/goods/good.html
lite_content/lite_exporter_frontend/goods.py
unit_tests/exporter/goods/test_forms.py

When attaching a document related to a product we ask multiple questions in a single form. These are whether a document is available and if it is above office-sensitive. These are now split into two separate forms. This PR adds changes to the views, templates.

LTD-502: Attach product documentation

---

Pipfile
Pipfile.lock
caseworker/templates/case/tabs/final-advice.html
caseworker/templates/case/tabs/team-advice.html
caseworker/templates/case/tabs/user-advice.html
exporter/organisation/views.py

This is a cosmetic change to remove the give advice buttons if the user doesn't
have permissions to give advice on a case.

LTD-537: Hide "Give advice" button if no ability to give advice

---

exporter/applications/forms/goods.py
unit_tests/exporter/applications/forms/goods/test_goods.py

In some old goods this field is absent so check for its presence before using it.

Make number_of_items backwards compatible

---

exporter/applications/services.py
exporter/applications/views/goods.py
exporter/goods/forms.py
lite_forms/submitters.py
lite_forms/views.py
unit_tests/exporter/goods/test_forms.py

This commit fixes the broken journeys when trying to add a non-firearm product
without affecting the firearms journey

LTD-578 Allow non-firearms products to be added

---

exporter/applications/forms/goods.py
exporter/applications/views/goods.py
exporter/goods/forms.py
exporter/goods/views.py
exporter/templates/applications/goods/add-good-detail-summary.html
exporter/templates/applications/goods/goods-detail-summary.html
lite_content/lite_exporter_frontend/goods.py
lite_forms/views.py
unit_tests/exporter/applications/forms/goods/test_goods.py

In case of RFD, that covers section1 and 2 so user is not asked to
select these sections again except if it is for section5.
Update the form to match section5 content and handle the logic
to skip when user is RFD.

LTD-503: Skip firearms act question in case of RFD and handle section5

---

caseworker/cases/forms/advice.py

The component was not initialised properly in the form resulting in this bug

LTD-731: Fix display of refusal criteria

---

conf/base.py
conf/gconfig.py
core/middleware.py
unit_tests/core/test_middleware.py

Add middleware for no cache header and obfuscate server name

---

caseworker/teams/forms.py
caseworker/templates/teams/index.html

A new question is asked when creating/editing Team to determine whether the team is part of ECJU or not. This is required in reports to calculate the SLA days correctly.

LTD-718: Ask question to determine whether a team is part of ECJU or not

---

.circleci/config.yml

we inadvertently stopped running these when we merged all the repositories

Update .circle.yml to run lite_forms tests

---

lite_forms/components.py
lite_forms/templates/components.html
lite_forms/templates/components/file_upload.html
lite_forms/templates/components/multi_file_upload.html
lite_forms/tests.py

This restricts file uploads to ones that are acceptable by LITE.

[LTD-750] Restrict upload file types

---

caseworker/organisations/forms.py
caseworker/organisations/services.py
caseworker/organisations/urls.py
caseworker/organisations/views.py
caseworker/templates/organisations/organisation/details.html
caseworker/templates/organisations/organisation/members.html
exporter/core/forms.py
exporter/organisation/sites/forms.py
exporter/templates/organisation/details/index.html
exporter/templates/organisation/members/index.html
exporter/templates/organisation/members/profile.html
exporter/templates/organisation/sites/site.html
lite_forms/common.py
unit_tests/caseworker/organisations/test_forms.py
unit_tests/caseworker/organisations/test_views.py
unit_tests/conftest.py

We are collecting organisation phone number, website when registering an organisation. Also asking for site admin contact number if it is a commercial organisation.
Update forms to ask phone number and website questions and update templates to show the details.

LTD-590/591/593/594: User registration frontend changes

---

caseworker/templates/case/product-on-case.html
unit_tests/caseworker/cases/test_templates.py

Also fixes an error on the product detail page when no RFD document is uploaded

Fix "Licence required" product mismatch

---

conf/base.py
core/middleware.py
unit_tests/core/test_middleware.py

This adds `X-Robots-Tag` to the response headers.

Add x-robots-tag middlware.

---

caseworker/templates/case/slices/goods.html
unit_tests/caseworker/cases/test_templates.py

Add changes to the display the quantity along with units on the case summary page.
Add test to ensure the template is rendered correctly.

LTD-674: Display quantity of each product in the case summary page

---

exporter/auth/views.py

Reverts uktrade/lite-frontend#197

Revert "[LTD-891] Stop social auth in Great "

---

tests_common/api_client/libraries/request_data.py
ui_tests/caseworker/features/organisation.feature
ui_tests/caseworker/step_defs/test_organisation.py
ui_tests/exporter/fixtures/register_organisation.py
ui_tests/exporter/pages/register_organisation.py
ui_tests/exporter/step_defs/test_register_an_organisation.py

Once an organisation is registered then Caseworker need to review
and approve/reject it. This change adds a browser test to ensure that
the organisation is reviewed and approved.

LTD-915: Add browser test to Review and approve an Organisation

---

exporter/templates/applications/applications.html
ui_tests/exporter/conftest.py
ui_tests/exporter/features/siel_firearm_application.feature
ui_tests/exporter/pages/application_page.py
ui_tests/exporter/step_defs/test_standard_application.py

This includes a bunch of fixes so I would recommend reviewing commit-wise.

[LTD-911] Open SIEL application

---

tests_common/api_client/libraries/request_data.py
tests_common/api_client/sub_helpers/goods.py
tests_common/helpers/applications.py
tests_common/tools/utils.py
ui_tests/caseworker/conftest.py
ui_tests/caseworker/features/view_standard_application.feature
ui_tests/caseworker/step_defs/test_filter_cases.py
ui_tests/caseworker/step_defs/test_view_standard_application.py

UI test to validate the application details from the caseworker site.
The test creates an application with a product and verifies the product name and rating, End user and consignee details and intended use details.

LTD-929: Caseworker UI test to view case details

---

ui_tests/caseworker/conftest.py
ui_tests/caseworker/features/review_goods.feature
ui_tests/caseworker/step_defs/test_review_goods.py
ui_tests/caseworker/step_defs/test_view_standard_application.py

Adds a test to verify the process of product review by a caseworker.
The test creates and submit an application, caseworker during review updates the control list entry and it ensures it is updated and the product status becomes verified after review.

LTD-933: Add UI test to verify reviewing a product in an application

---

exporter/organisation/forms.py

Reverts uktrade/lite-frontend#216

Revert "Expiry validation follow-up"

---

tests_common/helpers/applications.py
ui_tests/exporter/conftest.py
ui_tests/exporter/features/siel_firearm_application.feature

Adds a test for submitting SIEL application.

[LTD-926] Submit SIEL application

---

tests_common/api_client/sub_helpers/flags.py
tests_common/api_client/sub_helpers/gov_users.py
tests_common/api_client/test_helper.py
ui_tests/exporter/conftest.py
ui_tests/exporter/features/licences.feature

Fix existing exporter test so that we have test coverage for calling finalise on the api.

Fix existing licence test

---

caseworker/cases/helpers/advice.py
caseworker/cases/views/advice.py
caseworker/cases/views/main.py
caseworker/templates/components/goods-licence-list.html
unit_tests/caseworker/cases/test_helpers.py

Depends on this PR https://github.com/uktrade/lite-api/pull/818
Finalisation screen has changed slightly to list NLR items separately

NLR doesnt prevent case finalisation

---

caseworker/advice/forms.py
caseworker/advice/templates/advice/select_advice.html
caseworker/advice/urls.py
caseworker/advice/views.py
unit_tests/caseworker/advice/views/test_select_advice_view.py

This brings in the [select advice form](https://uktrade.atlassian.net/browse/LTD-1166).
It doesn't do the checkbox under "Refuse all". We do not need it rn.

[LTD-1166] Select Advice

---

caseworker/advice/forms.py
caseworker/advice/services.py
caseworker/advice/templates/advice/refusal_advice.html
caseworker/advice/urls.py
caseworker/advice/views.py
unit_tests/caseworker/advice/views/test_refusal_advice_view.py
unit_tests/caseworker/conftest.py

This adds the `Refuse all` advice page.
This is missing something - I could not figure out how to lay out the checkboxes as per the ticket. I reckon we should circle back and fix this later.

[LTD-1170] Refusal Advice

---

caseworker/templates/case/review-good-standard.html
ui_tests/caseworker/conftest.py
ui_tests/caseworker/features/enforcement.feature
ui_tests/caseworker/features/review_goods.feature
ui_tests/caseworker/features/view_standard_application.feature

Current scenario not asserting part number and Report summary so extend the
test to assert on these values.

LTD-1294: Add additional assertions for Product review browser test

---

caseworker/templates/case/product-on-case.html
caseworker/templates/case/review-good-standard.html
exporter/goods/forms.py
exporter/templates/applications/goods/goods-detail-summary.html
exporter/templates/goods/good.html
lite_content/lite_exporter_frontend/goods.py
lite_forms/tests.py
lite_forms/views.py
unit_tests/exporter/goods/test_forms.py

LTD-1382 Require comments from applicant when no document provided

---

caseworker/advice/forms.py

They were reverse in the page where user provides advice compared to
how they are displaying where we display user advice.

LTD-1346: Display the reasons for approving and conditions in consistent order

---

tests_common/helpers/applications.py

Reverts uktrade/lite-frontend#308

Revert "Update test helper function with location changes"

---

tests_common/fixtures/apply_for_application.py
tests_common/functions.py
ui_tests/exporter/conftest.py
ui_tests/exporter/features/ecju_queries.feature

Reverts uktrade/lite-frontend#309

Revert "Remaining fixes for UI test failures"

---

ui_tests/exporter/conftest.py

Look for option text inside nested <span>

Fix exporter UI test

---

caseworker/advice/forms.py
caseworker/advice/services.py
caseworker/advice/templates/advice/advice_details.html
caseworker/advice/templates/advice/review_consolidate.html
caseworker/advice/urls.py
caseworker/advice/views.py
unit_tests/caseworker/advice/views/test_consolidate.py

I decided to be a bit clever here. The fact that I can use `get_form` to be dynamic lets me put the logic for what form gets rendered in a single view. I think it reads better than this logic being spread over 3-4 views with a lot of redirects.

[LTD-1231] Consolidate review screen.

---

caseworker/advice/forms.py
caseworker/advice/templates/advice/countersign_review_form.html
caseworker/advice/templates/advice/review_countersign.html
caseworker/advice/templatetags/advice_tags.py

This works now but please checkout this branch on your local and try it before approving.

[LTD-1487] Radio button conditional form

---

caseworker/advice/services.py
caseworker/advice/urls.py
caseworker/advice/views.py
unit_tests/caseworker/advice/views/test_consolidate_edit.py

This is the consolidate edit view. 
It has a few clever bits in how (1) it inherits from the `consolidate-review` to re-use some bits (2) gets into trouble and (3) uses `setup` method to get out of trouble.

[LTD-1564] Consolidate edit

---

.circleci/config.yml
pipeline/Jenkinsfile

Update Jenkinsfile and .cricleci so when merge to master Jenkins can trigger a circleci UI test in datadev env.  
Default ui test is set to false, so now can only triggered when true in Jenkins.

fix jenkins to circleci integration

---

caseworker/advice/forms.py
caseworker/advice/templates/advice/case_detail.html
caseworker/advice/templates/advice/view-advice.html
caseworker/advice/templatetags/advice_tags.py
unit_tests/caseworker/advice/templatetags/test_advice_tags.py
unit_tests/caseworker/advice/views/test_view_ogd_advice.py

- Spelling inconsistencies
- Button name changes
- link name changes etc

LTD-1539: Content fixes

---

caseworker/advice/constants.py
caseworker/advice/services.py
caseworker/advice/views.py

Small but gnarly. I have left comments for my 6m-later-self.

Add a method to populate countries for FCO.

---

caseworker/advice/templates/advice/case_detail.html
caseworker/advice/templates/advice/give-approval-advice.html
caseworker/advice/templates/advice/refusal_advice.html
caseworker/advice/templates/advice/review_consolidate.html
caseworker/advice/templates/advice/review_countersign.html
caseworker/advice/templates/advice/select_advice.html

Fix misaligned columns in case details sidebar

---

caseworker/advice/forms.py

We now have an updated link and also style the link correctly.

LTD-1550: Update refusal criteria link

---

caseworker/advice/forms.py
lite_content/lite_internal_frontend/picklists.py
lite_content/lite_internal_frontend/teams.py

Changes mainly affect language, style

LTD-1602: Content changes for picklists in new Advice forms

---

Dockerfile

This is so that the UI tests can be run via Docker

Install Chrome on Docker build

---

caseworker/advice/services.py
unit_tests/caseworker/advice/views/test_consolidate.py
unit_tests/caseworker/advice/views/test_consolidate_edit.py
unit_tests/caseworker/advice/views/test_edit_advice.py

To be able to generate NLR letter a final advice of NLR type is required
otherwise caseworker cannot generate the letter.

LTD-1666: Create advice of NLR type also to be able to generate NLR letter

---

caseworker/advice/forms.py
unit_tests/caseworker/advice/test_forms.py

adding specified validations and error messages as in LTD 1668

adding specified validations and error messages as in LTD 1668

---

caseworker/advice/forms.py
unit_tests/caseworker/advice/test_forms.py

Update validation error message

 LTD-1701-select-error-validation-error 

---

caseworker/advice/templates/advice/group-advice.html

LTD-1677: Add missing instructions and footnote

---

ui_tests/caseworker/conftest.py
ui_tests/caseworker/pages/application_page.py
ui_tests/caseworker/pages/case_list_page.py
ui_tests/caseworker/pages/case_page.py
ui_tests/caseworker/pages/header_page.py
ui_tests/caseworker/pages/shared.py
ui_tests/caseworker/step_defs/test_case_notes.py
ui_tests/caseworker/step_defs/test_enforcement.py
ui_tests/exporter/pages/shared.py

The intent of this PR is make steps which have been flaky in CI a bit more robust by adding implicit waits prior to interacting with them.
By adding implicit waits we also removed any hardcoded sleep within the steps.

Add implicit waits on flaky steps and remove sleeps

---

caseworker/advice/templates/advice/advice_details.html
caseworker/advice/templatetags/advice_tags.py
unit_tests/caseworker/advice/views/test_consolidate.py

The code for this wasn't correct as it was iterating all `third_parties` in the case instead of picking the relevant ones.

[LTD-1702] Fix dupe third parties

---

caseworker/advice/templates/advice/give-approval-advice.html
caseworker/advice/templates/advice/refusal_advice.html
caseworker/advice/views.py

fix back button to approve/refuse advice

LTD-1607-fix-backlink

---

caseworker/advice/services.py
caseworker/advice/views.py
caseworker/cases/helpers/case.py
unit_tests/caseworker/advice/test_services.py
unit_tests/caseworker/advice/views/test_consolidate.py
unit_tests/caseworker/advice/views/test_consolidate_edit.py
unit_tests/caseworker/advice/views/test_give_approval_advice_view.py
unit_tests/caseworker/advice/views/test_lu_consolidate.py
unit_tests/caseworker/advice/views/test_refusal_advice_view.py
unit_tests/caseworker/advice/views/test_view_my_advice_view.py
unit_tests/caseworker/advice/views/test_view_ogd_advice.py
unit_tests/caseworker/conftest.py
unit_tests/conftest.py

This removed UUID and depends on alias flags set in the DB.

 LTD-1664-alias-teams-queues 

---

caseworker/core/decorators.py
core/middleware.py
exporter/core/decorators.py

Refactoring to minimise unnecessary errors raised.

Remove error logs has permissions

---

exporter/applications/views/export_details.py

tiny bugfix after refactoring content for LTD-1372

tiny bugfix after refactoring content

---

.bandit
.circleci/config.yml
.pre-commit-config.yaml
Pipfile
Pipfile.lock
makefile

Reverts uktrade/lite-frontend#436

Revert "Move linting checks into pre-commit"

---

exporter/applications/views/export_details.py
exporter/applications/views/locations.py
exporter/applications/views/route_of_goods.py
exporter/templates/applications/goods-locations/goods-locations-summary.html

Fix locations issues ltd 1891

---

cypress/integration/caseworker/application.spec.js

This PR should cover the below scenario:
Scenario: Approve case in counter-sign
Steps:
- Access case in counter-sign queue
- Navigate to recommendtation and decision
- Approve/Submit case after adding reason of approval
- Move case forward
- Verify it's no longer in counter-sign queue and the appropriate reason of approval is present

Add additional test for counter sign approve case

---

exporter/applications/forms/export_details.py
exporter/applications/views/export_details.py
exporter/applications/views/locations.py
exporter/core/constants.py
exporter/templates/applications/goods-locations/goods-locations-summary.html
exporter/templates/applications/task-list.html

fixing Locations issues by making the whole journey into single lite forms group. Issues as shown in LTD-1891 and more.

fixing locations issues 

---

.circleci/config.yml
Pipfile.lock

This will make sure that the pip lock file is up-to-date when installing

Update pip lock file

---

caseworker/cases/apps.py
caseworker/cases/templatetags/firearm_details.py
caseworker/templates/case/includes/serial_numbers.html
caseworker/templates/case/product-on-case.html
caseworker/templates/case/review-good-standard.html
conf/caseworker.py
unit_tests/caseworker/cases/test_templatetags.py

Updates the display of serial numbers in caseworker depending on what was selected by the exporter.

Display serial numbers correctly when indicated as adding later

---

caseworker/cases/urls.py
caseworker/tau/apps.py
caseworker/tau/templates/tau/home.html
caseworker/tau/urls.py
caseworker/tau/views.py
conf/caseworker.py
unit_tests/caseworker/tau/test_home.py

This PR adds an app that will host TAU 2.0 functionality that we are looking to build.
The `home` view is just a placeholder and I fully expect it to be replaced/renamed down the line.

[LTD-1952] TAU App

---

exporter/applications/helpers/check_your_answers.py
exporter/applications/views/parties/end_users.py
unit_tests/exporter/applications/views/parties/test_end_users.py

Product review fixes
- save undertaking document description
- Error handling when editing documents
- Correct links in 'Check your answers before submitting' page
- refactoring repeating bits into a common function

LTD-1368: English translation changes review fixes

---

exporter/core/views.py

This PR is to notify exporters of missing serial number both on home page and applications list page. LTD-1441.

show notifications where there are cases with missing serials

---

ui_tests/caseworker/conftest.py
ui_tests/caseworker/features/give_advice.feature
ui_tests/caseworker/step_defs/test_give_advice.py

Moves advice specific fixtures into the advice test module and fixes an issue with the FCDO advice journey.

Relocate advice specific fixtures

---

exporter/applications/helpers/check_your_answers.py
exporter/applications/views/parties/end_users.py
exporter/templates/applications/party-summary.html

Address issues found during product review

LTD-1642: Add missing EC3 form details in check your answers page

---

exporter/applications/views/goods/add_good_firearm.py
exporter/core/helpers.py
exporter/goods/forms/firearms.py
unit_tests/exporter/applications/views/test_add_good_firearm.py

This refactors some common pieces of functionality:
- Getting file data to post to the API
- Handling errors when posting to the API from the firearms wizard
- Setting up crispy form layouts in firearm forms
- How we build the payload to create the product

Ltd 1433 certificates section

---

exporter/applications/urls.py
exporter/applications/views/goods/add_good_firearm.py
exporter/templates/applications/goods/firearms/product-summary.html
unit_tests/exporter/applications/views/test_add_good_firearm.py

This is the first summary screen currently with no edit links that captures the permanent details of the product.

LTD-2141: Add product summary screen to the new wizard

---

caseworker/tau/forms.py
caseworker/tau/templates/tau/case_detail.html
caseworker/tau/templates/tau/good_detail.html
caseworker/tau/templates/tau/goods_checkbox_option.html
caseworker/tau/templates/tau/goods_checkbox_select.html
caseworker/tau/templates/tau/home.html
caseworker/tau/templatetags/tau_tags.py
caseworker/tau/views.py
caseworker/tau/widgets.py
unit_tests/caseworker/tau/templatetags/test_get_destinations.py
unit_tests/caseworker/tau/test_home.py

Not perfect in terms of layout but it is one step closer to how we want it to be. There will be follow-up tickets to fix some of the layout issues, add the edit version of this form for assessed goods, some changes to good details etc.

[LTD-1949] TAU list view

---

exporter/applications/views/goods/add_good_firearm.py
exporter/goods/services.py

This can be reused to edit various firearm details

Add View to edit a firearm

---

ui_tests/caseworker/conftest.py
ui_tests/caseworker/features/give_advice.feature
ui_tests/caseworker/pages/advice.py
ui_tests/caseworker/pages/application_page.py
ui_tests/caseworker/pages/shared.py
ui_tests/caseworker/step_defs/test_give_advice.py
ui_tests/caseworker/step_defs/test_review_goods.py
ui_tests/caseworker/step_defs/test_view_standard_application.py

https://user-images.githubusercontent.com/24960282/161162111-75664d17-da27-4af4-be72-9823fa7b8e1b.mov
Updated video:
https://user-images.githubusercontent.com/24960282/161312483-5e75ac4f-b6f8-4791-a415-e6af9ee44a82.mov

LTD-2108-LU-countersign 

---

exporter/applications/urls.py
exporter/applications/views/goods/add_good_firearm.py
exporter/templates/applications/goods/firearms/product-summary.html
unit_tests/conftest.py
unit_tests/exporter/applications/views/conftest.py
unit_tests/exporter/applications/views/test_edit_firearm.py
unit_tests/exporter/applications/views/test_edit_good.py

I have had to add a mixin since the name is effectively editing the 'good' so edit fire arms is technically incorrect and confusing. Hence the break up from the EditfirearmsForm and mixin

LTD-2144-SIEL-Change-product-name-2

---

caseworker/tau/forms.py
caseworker/tau/templates/tau/edit.html
caseworker/tau/templates/tau/home.html
caseworker/tau/urls.py
caseworker/tau/views.py
unit_tests/caseworker/tau/test_edit.py
unit_tests/caseworker/tau/test_forms.py
unit_tests/caseworker/tau/test_home.py

This adds an edit form - linked from the assessed products on the home screen.

[LTD-2169] TAU Edit

---

caseworker/tau/templates/tau/home.html
caseworker/tau/urls.py
caseworker/tau/views.py
unit_tests/caseworker/tau/test_home.py
unit_tests/caseworker/tau/test_move_case_forward.py

When the TAU officers have assessed all the goods, they get a move-case-forward button.

[LTD-2171] Move case forward

---

exporter/applications/urls.py
exporter/applications/views/goods/add_good_firearm.py
exporter/templates/applications/goods/firearms/product-summary.html
unit_tests/conftest.py
unit_tests/exporter/applications/views/conftest.py
unit_tests/exporter/applications/views/test_add_good_firearm.py
unit_tests/exporter/applications/views/test_edit_firearm.py

i've moved out post_to_step/goto_step in attempt to reuse. 
if happy we could move to conftest and use across the other tests

TD-2147-change-grading 

---

tests_common/api_client/libraries/request_data.py
ui_tests/caseworker/features/organisation.feature
ui_tests/caseworker/step_defs/test_organisation.py

add UI test to check company details as spcecified in LTD-2032

add UI test to check company details as spcecified in LTD-2032

---

exporter/goods/forms/firearms.py

LTD-2197-change-is-replica-textarea

---

exporter/templates/applications/goods/firearms/product-summary.html

 LTD-2199-text-change 

---

exporter/applications/urls.py
exporter/applications/views/goods/add_good_firearm/views/actions.py
exporter/applications/views/goods/add_good_firearm/views/add.py
exporter/applications/views/goods/add_good_firearm/views/decorators.py
exporter/applications/views/goods/add_good_firearm/views/edit.py
exporter/applications/views/goods/add_good_firearm/views/mixins.py
exporter/applications/views/goods/add_good_firearm/views/payloads.py
exporter/core/forms.py
exporter/core/templates/core/widgets/potentially_unsafe_clearable_file_input.html
exporter/goods/forms/firearms.py
exporter/templates/applications/goods/firearms/product-summary.html
unit_tests/exporter/applications/views/conftest.py
unit_tests/exporter/applications/views/test_add_good_firearm.py
unit_tests/exporter/applications/views/test_add_good_to_application.py
unit_tests/exporter/applications/views/test_edit_firearm.py
unit_tests/exporter/applications/views/test_edit_registered_firearm_dealer.py
unit_tests/exporter/conftest.py

This has the start of the editing for RFD status but I ended up doing a lot of refactoring whilst still implementing this so I think it makes sense to pull this in before we end up in merge hell.
Highlights:
- Extracts out common functionality into mixins and base classes e.g. getting application and good objects
- Pulls out common logic for posting to services into helper classes (only section certificates at the moment)
- Add a factory fixture for creating fixtures to post to wizard steps

Ltd 2150 change firearm dealer

---

exporter/goods/forms/firearms.py

 LTD-2209-sec-grading-hint-text

---

exporter/templates/applications/goods/firearms/product-summary.html

LTD-2202 fix summary page missing product doc 'no' answer

LTD-2202 fix summary page missing product doc 'no' answer

---

exporter/templates/applications/goods/firearms/product-summary.html

fix for LTD-2213 missing 'Description' field for product document

fix for LTD-2213 missing 'Description' field for product document

---

pipeline/Jenkinsfile

LTD-1981-jenkins-tests 

---

exporter/applications/views/goods/add_good_firearm/views/add.py
exporter/applications/views/goods/add_good_firearm/views/edit.py
exporter/applications/views/goods/goods.py
exporter/applications/views/parties/end_users.py
exporter/core/templates/core/form-wizard.html
exporter/goods/views.py
unit_tests/exporter/applications/views/test_add_good_firearm.py

We don't need to show this as per the designs

LTD-2212: Remove wizard step count from the template

---

exporter/applications/views/goods/goods.py
exporter/applications/views/parties/end_users.py
exporter/core/templates/core/form-wizard.html
exporter/goods/views.py

LTD-2208 renaming previous step to back

LTD-2208 renaming previous step to back

---

caseworker/tau/services.py
caseworker/tau/templates/tau/good_detail.html
caseworker/tau/templates/tau/home.html
caseworker/tau/views.py
unit_tests/caseworker/tau/test_home.py

This displays the precedent for a un-assessed `GoodOnApplication`.

[LTD-2174] Precedent

---

exporter/templates/applications/goods/firearms/product-on-application-summary.html
exporter/templates/applications/goods/firearms/product-summary.html

changed in both summary screens

 LTD-2245-change-unsure-label 

---

exporter/templates/applications/goods/firearms/product-summary.html

LTD-2247-change-date-format 

---

caseworker/tau/templates/tau/edit.html
caseworker/tau/templates/tau/good_detail.html
caseworker/tau/templates/tau/good_table.html
caseworker/tau/templates/tau/precedent_table.html
caseworker/tau/views.py
unit_tests/caseworker/conftest.py
unit_tests/caseworker/tau/test_edit.py
unit_tests/caseworker/tau/test_home.py

This does some (1) refactoring before (2) putting it to good use. I would recommend a commit-wise review.

[LTD-2238] Show good details along edit form

---

ui_tests/caseworker/features/organisation.feature

LTD-2032 changing phone numnber to the one in the ticket

changing phone numnber to the one in the ticket

---

caseworker/tau/views.py

- Replace if queue is None with "00000000-0000-0000-0000-000000000001" so link won't break.
https://user-images.githubusercontent.com/24960282/167963121-11bc3951-a01a-4fba-8246-60b26fbfc133.mov

LTD-2292-Cases-Bug

---

caseworker/tau/forms.py
caseworker/tau/templates/tau/home.html
unit_tests/caseworker/tau/test_home.py
unit_tests/conftest.py

LTD-2290 Updates to contents fixes

---

ui_tests/caseworker/features/sanctions.feature
ui_tests/caseworker/step_defs/test_sanctions.py

LTD-2110 UI test to check sanctions

adding ui test for checking sanctions

---

conf/base.py

Reverts uktrade/lite-frontend#693

Revert "Ltd 2235 add s3 check to healthcheck"

---

tests_common/helpers/applications.py
ui_tests/caseworker/features/sanctions.feature
ui_tests/caseworker/step_defs/test_sanctions.py

altering check sanctions test

---

ui_tests/caseworker/features/sanctions.feature
ui_tests/caseworker/step_defs/test_sanctions.py

Enhance check sanction UI test to check removal

Enhance check sanction UI test to check removal

---

exporter/core/registration/constants.py
exporter/core/registration/forms.py
exporter/core/registration/payloads.py
exporter/core/registration/validators.py
exporter/core/registration/views.py
unit_tests/exporter/core/registration/test_forms.py
unit_tests/exporter/core/registration/test_registration.py

again none of this is switched on so for now it's just  draft mode.

 LTD-2398-registration-business-df-draft 

---

.circleci/config.yml

replace old ui tests with new e2e tests for jenkins UI tests job

replace old ui tests with new e2e tests

---

exporter/templates/applications/applications.html
exporter/templates/includes/breadcrumbs.html
exporter/templates/licences/licences.html
lite_content/lite_exporter_frontend/licences.py

i've updated the the bread crumb and 'my licensees' txt 
I need help to make the remaining two changes

switch-organisation-ui-fixes 

---

caseworker/core/context_processors.py
caseworker/tau/templates/tau/home.html
conf/caseworker.py
unit_tests/caseworker/core/test_context_processors.py
unit_tests/caseworker/tau/test_home.py

This tries to find a general solution to the users hitting move-case-forward from the all cases queue problem.

[LTD-2421] All cases queue

---

pipeline/Jenkinsfile

change config for lite-frontend-ui-tests Jenkins pipeline

change config for lite-frontend-ui-tests Jenkins pipeline

---

exporter/applications/views/goods/goods.py
exporter/goods/views.py
exporter/templates/applications/goods/preexisting.html
exporter/templates/goods/good.html
exporter/templates/goods/goods.html
exporter/templates/includes/control-list-entries.html
unit_tests/exporter/goods/views/test_good_detail.py

CLE column shows N/A if not verified.
Part 2 of Jira https://uktrade.atlassian.net/browse/LTD-2451
SS:

Ltd 2559 - Verified cles only in the column

---

caseworker/templates/case/includes/selection-sidebar.html
caseworker/templates/case/slices/goods.html
lite_content/lite_internal_frontend/cases.py
lite_content/lite_internal_frontend/flags.py

Changes made as requested on https://uktrade.atlassian.net/browse/LTD-2543

[LTD-2543] Reword good as product on the frontend

---

pipeline/Jenkinsfile

fixing illformed jenkinsfile

---

pipeline/Jenkinsfile

removing default value for env param

removing default value for env param

---

caseworker/tau/templates/tau/good_table.html
caseworker/tau/templates/tau/platform_table.html
caseworker/templates/case/product-on-case.html

LTD-2613-internal-cw-tau 

---

core/summaries/formatters.py
exporter/applications/views/goods/add_good_component/views/add.py
exporter/applications/views/goods/add_good_platform/views/add.py
exporter/applications/views/goods/add_good_platform/views/edit.py
exporter/core/templates/goods/forms/common/help_with_security_features.html
exporter/goods/forms/common.py
exporter/goods/forms/goods.py
unit_tests/exporter/applications/views/component/test_add_good_component.py
unit_tests/exporter/applications/views/platform/test_add_good_platform.py
unit_tests/exporter/applications/views/platform/test_summary_platform.py
unit_tests/exporter/applications/views/test_edit_platform.py
unit_tests/exporter/goods/forms/test_common.py
unit_tests/exporter/goods/views/test_platform_product_details.py

This creates a new form with the new content instead of trying to use the previous one and change the content depending onthe context in which it's used
The old form should eventually be removed as it's essentially unused but that should be as a separate piece of work

Update content for information security form

---

exporter/templates/applications/goods/software/product-summary.html

Connecting non-firearm software goods forms to goods-to-application forms.

correcting continue button to correct form

---

caseworker/cases/helpers/summaries.py
caseworker/tau/forms.py
caseworker/tau/summaries.py
caseworker/tau/templates/tau/product_summary_table.html
caseworker/tau/views.py
core/summaries/formatters.py
core/summaries/utils.py
unit_tests/caseworker/tau/test_forms.py
unit_tests/core/summaries/test_formatters.py
unit_tests/core/summaries/test_utils.py

Removed summary fields from the TAU view when those values are displayed elsewhere e.g. product name.

Ltd 2805 platform tau screen

---

exporter/applications/urls.py
exporter/templates/applications/goods/preexisting.html

add missing code to be able add an existing software product to application

add missing code to be able add an existing software product

---

core/summaries/formatters.py
cypress/fixtures/goodsToDraft.json
exporter/applications/views/goods/add_good_component/views/payloads.py
exporter/applications/views/goods/add_good_platform/views/payloads.py
exporter/applications/views/goods/common/initial.py
exporter/applications/views/goods/common/payloads.py
exporter/goods/forms/common.py
tests_common/fixtures/apply_for_application.py
unit_tests/conftest.py
unit_tests/exporter/applications/views/component/test_add_good_component_to_application.py
unit_tests/exporter/applications/views/material/test_add_good_material_to_application.py
unit_tests/exporter/applications/views/material/test_summary_material.py
unit_tests/exporter/applications/views/platform/test_add_good_platform_to_application.py
unit_tests/exporter/applications/views/software/test_add_good_software_to_application.py
unit_tests/exporter/applications/views/test_add_good_firearm_to_application.py
unit_tests/exporter/applications/views/test_add_good_to_application.py
unit_tests/exporter/applications/views/test_attach_firearm_to_application.py
unit_tests/exporter/applications/views/test_edit_component_good_on_application.py
unit_tests/exporter/applications/views/test_edit_firearm_good_on_application.py
unit_tests/exporter/applications/views/test_edit_material_good_on_application.py
unit_tests/exporter/applications/views/test_edit_platform_good_on_application.py
unit_tests/exporter/applications/views/test_edit_software_good_on_application.py
unit_tests/exporter/conftest.py
unit_tests/exporter/goods/forms/test_common.py

Requirement is to change Quantity from integer to decimal, except when unit is Items.

change quantity to decimal

---

core/summaries/reducers.py
unit_tests/conftest.py
unit_tests/core/summaries/test_reducers.py
unit_tests/exporter/conftest.py
unit_tests/exporter/goods/views/test_software_product_details.py

adding part number to software summary

adding part number to software summary

---

caseworker/tau/templates/tau/product_summary_table.html

Add product document description below product document link on TAU screen.

Ltd 2863 description in tau

---

caseworker/advice/templates/advice/case_detail.html

Clicking it will take to full details of DN record

LTD-2940: Show DN reference as hyperlink

---

exporter/applications/views/goods/software/urls.py
exporter/applications/views/goods/software/views/add.py
exporter/applications/views/goods/software/views/constants.py
exporter/applications/views/goods/software/views/edit.py
exporter/applications/views/goods/software/views/payloads.py
exporter/applications/views/goods/software/views/summary.py
exporter/goods/software/views.py
exporter/goods/urls.py
unit_tests/exporter/applications/views/goods/software/test_add_good_software.py
unit_tests/exporter/applications/views/goods/software/test_edit_software.py
unit_tests/exporter/applications/views/goods/software/test_edit_software_good_on_application.py

renaming class names involving `software`

renaming class names involving software

---

exporter/applications/views/goods/platform/urls.py
exporter/applications/views/goods/platform/views/add.py
exporter/applications/views/goods/platform/views/constants.py
exporter/applications/views/goods/platform/views/edit.py
exporter/applications/views/goods/platform/views/payloads.py
exporter/applications/views/goods/platform/views/summary.py
exporter/goods/platform/views.py
exporter/goods/urls.py
unit_tests/exporter/applications/views/goods/platform/test_add_good_platform.py
unit_tests/exporter/applications/views/goods/platform/test_edit_platform.py
unit_tests/exporter/applications/views/goods/platform/test_edit_platform_good_on_application.py

renaming class names that has `platform` in it as part of grand renaming task.

renaming class names that has platform in it

---

exporter/templates/goods/goods.html

fix rebase merge issues, within goods.html

fix rebase merge issues

---

caseworker/advice/templates/advice/case_detail.html

Small fixes to `case_details.html` template as per the changes specified in the ticket

Ltd 3084 beis follow up content typography

---

caseworker/templates/letter-templates/edit-letter-paragraphs.html
caseworker/templates/letter-templates/order-letter-paragraphs.html

there are a couple of views of the letter paragraph  belonging to the refusal letter that do not have any line breaks as expected

refusal letter formatting update

---

ui_tests/caseworker/features/view_goods.feature
ui_tests/caseworker/step_defs/test_view_goods.py

This change adds a UI test to ensure that the caseworker good detail page is working end to end.

Add a UI test for caseworker good detail page

---

caseworker/advice/templates/advice/clear_trigger_list_assesment.html
caseworker/advice/templates/advice/trigger_list_home.html
caseworker/advice/urls.py
caseworker/advice/views.py
unit_tests/caseworker/advice/views/test_trigger_list_view.py

https://user-images.githubusercontent.com/24960282/209237678-c3ab5c0c-4414-45b0-9a17-1c10a787fa79.mov

LTD-3130-Clear-Assessments-update

---

exporter/templates/applications/goods/preexisting.html
exporter/templates/goods/goods.html

This is to add the part number to the two product list screen in exporter app.

 LTD-3007-add-pn-column

---

core/builtins/custom_tags.py
unit_tests/caseworker/test_template_tags.py
unit_tests/core/builtins/test_custom_tags.py

rounding of total value in filter in case of floating point imprecision during conversion from decimal

goods total value rounding

---

caseworker/advice/templates/advice/case_detail.html
caseworker/advice/templatetags/advice_tags.py
unit_tests/caseworker/advice/templatetags/test_advice_tags.py

Adding serial numbers (firearms) to the case detail section of review. This html is used by several others so code was added to html + custom tag.

LTD-3193 add serial number section to goods in case detail

---

caseworker/advice/forms.py

BEIS Nuclear have confirmed they need this amendment to the question text
Error message is also changing to match

Amend Nuclear Cooperation Agreement question and error message

---

caseworker/advice/enums.py
caseworker/advice/forms.py
caseworker/advice/services.py
caseworker/advice/templates/advice/assessed_products.html
caseworker/advice/views.py
unit_tests/caseworker/advice/views/test_trigger_list_view.py
unit_tests/conftest.py

When asking for trigger list assessment the options that we currently provide are not correct. This updates the form with the correct options. The API is being updated in https://github.com/uktrade/lite-api/pull/1292
In this PR,
- we update the form
- update summary table
- update unit tests
- styling updates to a question label

LTD-3330-3297: Update options for trigger list question

---

caseworker/templates/queues/cases.html

Getting hotfix https://github.com/uktrade/lite-frontend/pull/1106 downstream from `uat` branch in to `dev` branch.

[LTD-3355] [Hotfix dev downstream] Fix queue view header ordering dev downstream

---

caseworker/advice/templates/advice/case_detail.html

This reverts commit 227cb258774aba73802d51d67508f2ebd8498bfa.

Revert "LTD-3324 Update serial number message in case detail template"

---

ui_tests/exporter/conftest.py
ui_tests/exporter/features/edit_standard_application.feature
unit_tests/exporter/applications/views/test_application_detail.py

I wrote these tests before realising the changes needed to be [made in the backend for this ticket](https://uktrade.atlassian.net/browse/LTD-3305)
I think it could still be useful to have some unit tests/ a UI smoke test around this as we are making changes to it
[LTD-3433](https://uktrade.atlassian.net/browse/LTD-3433)
[LTD-3433]: https://uktrade.atlassian.net/browse/LTD-3433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-3433: tests around edit button rendering

---

caseworker/tau/forms.py

Fixes for a few report summary bugs. See ticket for details.
Note this also fixes [LTD-3418](https://uktrade.atlassian.net/browse/LTD-3418)
[LTD-3394](https://uktrade.atlassian.net/browse/LTD-3394)
[LTD-3394]: https://uktrade.atlassian.net/browse/LTD-3394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LTD-3418]: https://uktrade.atlassian.net/browse/LTD-3418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Report summary bugs

---

caseworker/assets/javascripts/tau/ars.js

Fix the ability to remove an ARS entry. This works for both prefix and suffix.

Ltd 3514 prefix removal

---

caseworker/assets/javascripts/case.js
caseworker/templates/layouts/case.html

Staging release

---

caseworker/assets/javascripts/tau/__tests__/ars.test.js
caseworker/assets/javascripts/tau/ars.js
jest.config.js
package-lock.json
package.json
setupJest.js

Add tests for ARS component

---

caseworker/activities/views.py
caseworker/advice/views.py
caseworker/assets/styles/components/_cases.scss
caseworker/cases/helpers/case.py
caseworker/queues/forms.py
caseworker/queues/urls.py
caseworker/queues/views/case_assignments.py
caseworker/tau/views.py
caseworker/templates/case/case.html
caseworker/templates/layouts/case.html
unit_tests/caseworker/cases/views/test_case_assignments.py
unit_tests/caseworker/cases/views/test_case_details.py

In order to speed up the flow when wanting to allocate yourself to a case, this PR adds a button to the bar next to "Allocate case" button to allocate yourself directly to the case without an intermediate page flow.
[LTD-3586](https://uktrade.atlassian.net/browse/LTD-3586)
[LTD-3586]: https://uktrade.atlassian.net/browse/LTD-3586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allocate me button

---

caseworker/advice/services.py
caseworker/templates/includes/case-row.html
caseworker/templates/queues/cases.html

UAT fixup release for queue view customisations.

UAT release

---

caseworker/templates/includes/case-row.html
caseworker/templates/queues/cases.html

Release a fixup for customisable columns.

Release to UAT

---

ui_tests/caseworker/pages/application_page.py

Fixes a e2e test that is now consistently failing

Casenote click delay

---

caseworker/advice/forms.py

Small fixes for approval page as requested during product review; https://uktrade.atlassian.net/browse/LTD-3701

Flip around help text/picklist link for approval footnote

---

caseworker/activities/forms.py

Not all users were being returned from get_gov_users due to optional pagination not being disabled

Mentions get_gov_users removed pagination

---

caseworker/activities/templates/activities/notes-and-timeline.html
unit_tests/caseworker/activities/test_views.py
unit_tests/caseworker/conftest.py

To support N&T mention we have had to enrich the API also 
The payload object includes additional info to allow this extra data 
https://uktrade.atlassian.net/browse/LTD-3660
Accompanying API PR 
https://github.com/uktrade/lite-api/pull/1457

LTD-3660-add-mentions-nt 

---

caseworker/activities/templates/activities/notes-and-timeline.html
caseworker/assets/styles/_mentions.scss
caseworker/assets/styles/components/notes_and_timeline/_nav.scss
caseworker/assets/styles/components/notes_and_timeline/_timeline.scss
caseworker/assets/styles/styles.scss
caseworker/templates/users/mentions.html
unit_tests/caseworker/activities/test_views.py

There is an API change related to LTD-3693
https://github.com/uktrade/lite-api/pull/1461
https://uktrade.atlassian.net/browse/LTD-3693
https://uktrade.atlassian.net/browse/LTD-3719
https://uktrade.atlassian.net/browse/LTD-3720
https://uktrade.atlassian.net/browse/LTD-3721
https://uktrade.atlassian.net/browse/LTD-3723

LTD-3693-LTD-3719-LTD-3720-LTD-3721-LTD-3723-Bugs

---

caseworker/core/context_processors.py
caseworker/core/services.py
caseworker/templates/users/mentions.html
caseworker/users/services.py
caseworker/users/views/users.py
unit_tests/caseworker/conftest.py
unit_tests/caseworker/users/test_views.py

Add pagination to user mentions list page
https://uktrade.atlassian.net/browse/LTD-3695

 LTD-3695-usercase-mentions-pagination

---

caseworker/activities/templates/activities/notes-and-timeline.html
caseworker/assets/styles/_mentions.scss
caseworker/assets/styles/styles.scss
caseworker/templates/users/mentions.html

https://uktrade.atlassian.net/browse/LTD-3729
addressed full stop comment from Collin:
https://uktrade.atlassian.net/browse/LTD-3693

LTD-3729-NEW-tag-bug

---

lite_content/lite_internal_frontend/cases.py
ui_tests/caseworker/features/ecju_queries.feature

Changed "Add an ECJU query" to "Send a query to the exporter"
[LTD-3747](https://uktrade.atlassian.net/browse/LTD-3747)
[LTD-3747]: https://uktrade.atlassian.net/browse/LTD-3747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD 3747 NCSC Change button label

---

caseworker/assets/styles/_mentions.scss
caseworker/assets/styles/components/notes_and_timeline/_timeline.scss
caseworker/templates/users/mentions.html

https://uktrade.atlassian.net/browse/LTD-3753
https://uktrade.atlassian.net/browse/LTD-3750

LTD-3750-LTD-3753-UI-fixes

---

caseworker/bookmarks/services.py
caseworker/bookmarks/views.py
caseworker/queues/views/cases.py
caseworker/queues/views/forms.py
unit_tests/caseworker/bookmarks/test_services.py
unit_tests/caseworker/cases/views/test_case_bookmarks.py
unit_tests/caseworker/conftest.py
unit_tests/caseworker/queues/test_templates.py

Flags are a multi-selection in the filters, and this wasn't originally taken into account causing an issue when trying to render filters that were saved with flags. This fixes the issue.
[LTD-3816](https://uktrade.atlassian.net/browse/LTD-3816)
[LTD-3816]: https://uktrade.atlassian.net/browse/LTD-3816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bugfix for issue where saving a filter with flags will break the UI

---

caseworker/templates/users/mentions.html

change Response to respond
[LTD-3721](https://uktrade.atlassian.net/browse/LTD-3721)
[LTD-3721]: https://uktrade.atlassian.net/browse/LTD-3721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-3721 Fix casing of Respond in mentions

---

caseworker/queues/views/forms.py

Name changes to checkbox filters
[LTD-3835](https://uktrade.atlassian.net/browse/LTD-3835)
[LTD-3835]: https://uktrade.atlassian.net/browse/LTD-3835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Name changes to checkbox filters

---

caseworker/queues/views/forms.py
unit_tests/caseworker/queues/views/test_cases.py

Add Report Summary filter to the Product filter tab
[LTD-3831](https://uktrade.atlassian.net/browse/LTD-3831)
[LTD-3831]: https://uktrade.atlassian.net/browse/LTD-3831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added Report Summary filter

---

caseworker/queues/views/forms.py
unit_tests/caseworker/queues/views/test_cases.py

Change the name and filter used for the goods related description. This will now search on Product name only
[LTD-3832](https://uktrade.atlassian.net/browse/LTD-3832)
[LTD-3832]: https://uktrade.atlassian.net/browse/LTD-3832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Change field description

---

caseworker/queues/views/cases.py
caseworker/queues/views/forms.py
unit_tests/caseworker/queues/views/test_cases.py

Support exclude CLE / regime case searches
[LTD-3853](https://uktrade.atlassian.net/browse/LTD-3853)
[LTD-3858](https://uktrade.atlassian.net/browse/LTD-3858)
[LTD-3853]: https://uktrade.atlassian.net/browse/LTD-3853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LTD-3858]: https://uktrade.atlassian.net/browse/LTD-3858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Exclude cle/regime functionality added to the case search

---

caseworker/cases/forms/change_status.py
caseworker/cases/forms/done_with_case.py
caseworker/cases/forms/move_case.py
caseworker/cases/views/case_assignments.py
caseworker/cases/views/external_data.py
caseworker/cases/views/main.py
caseworker/flags/views.py
caseworker/templates/case/denial-for-case.html
caseworker/templates/case/product-on-case.html
caseworker/templates/case/remove-allocation.html
caseworker/templates/external_data/sanction-revoke.html
unit_tests/caseworker/cases/views/test_case_assignments.py
unit_tests/caseworker/cases/views/test_change_status.py
unit_tests/caseworker/cases/views/test_external_data.py
unit_tests/caseworker/flags/test_views.py

Fix up back links from pages that should link back to the case detail tab instead of the new default "quick summary" tab.
[LTD-3793](https://uktrade.atlassian.net/browse/LTD-3793)
[LTD-3793]: https://uktrade.atlassian.net/browse/LTD-3793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LTD-3793] Quick summary back button

---

caseworker/bookmarks/services.py
caseworker/bookmarks/views.py
caseworker/queues/views/cases.py
unit_tests/caseworker/bookmarks/test_services.py
unit_tests/caseworker/cases/views/test_case_bookmarks.py
unit_tests/caseworker/conftest.py

Use the case filters form itself to generate a description for the bookmark.
[LTD-3855](https://uktrade.atlassian.net/browse/LTD-3855)
[LTD-3855]: https://uktrade.atlassian.net/browse/LTD-3855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ltd 3855 saved filters form based part 2

---

caseworker/queues/views/forms.py
unit_tests/caseworker/queues/views/test_cases.py

LTD-3959-filtering 

---

caseworker/advice/forms.py
caseworker/advice/templates/advice/refusal_advice.html
caseworker/advice/templates/advice/review_consolidate.html
caseworker/assets/javascripts/advice.js
caseworker/assets/javascripts/main.js
caseworker/assets/javascripts/refusal-review-consolidate.js
caseworker/assets/styles/components/_advice.scss
docker-compose.yml
package.json
ui_tests/caseworker/step_defs/test_give_advice.py

I could not find a way to override a class in Django form for the labels. The crispy form would just override it so I just change it inside .scss instead. Any suggestion is welcome.

LTD-3964-refusal-reasons

---

.circleci/config.yml

Update CI images to non-deprecated versions.

Update ci images

---

caseworker/advice/forms.py
caseworker/advice/templates/advice/refusal_advice.html
caseworker/assets/styles/components/_advice.scss
unit_tests/caseworker/advice/test_forms.py

Waiting for Duane to come back if we are just replacing the refusal to note and functionality wise is the same. If it is, there will be no changes needed to be made additionally.
https://uktrade.atlassian.net/browse/LTD-3965

LTD-3965-replace-refusal-reason-to-note

---

caseworker/templates/includes/case-row.html

Commit that was missed from the previous release.
[LTD-3960](https://uktrade.atlassian.net/browse/LTD-3960)
[LTD-3960]: https://uktrade.atlassian.net/browse/LTD-3960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

enduser -> end_user

---

caseworker/assets/javascripts/__tests__/list-expander.test.js
caseworker/assets/javascripts/list-expander.js

These buttons are useful and should be discoverable for screen-reader users
[LTD-4021](https://uktrade.atlassian.net/browse/LTD-4021)
[LTD-4021]: https://uktrade.atlassian.net/browse/LTD-4021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-4021: Remove unnecessary aria-hidden label

---

exporter/goods/forms/common.py

This helps screen reader users to understand the purpose of the input field
[LTD-4025](https://uktrade.atlassian.net/browse/LTD-4025)
[LTD-4025]: https://uktrade.atlassian.net/browse/LTD-4025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-4025: Add accessible name for the textarea

---

package-lock.json
package.json

Update packages to upgrade `semver` to remove solve security advisory.

Udpate babel packages to update `semver`

---

exporter/urls.py
unit_tests/exporter/applications/test_summaries.py
unit_tests/exporter/applications/views/goods/firearm/test_summary_firearm.py
unit_tests/exporter/applications/views/goods/material/test_summary_material.py
unit_tests/exporter/conftest.py
unit_tests/exporter/goods/views/test_component_product_details.py
unit_tests/exporter/goods/views/test_firearm_product_details.py
unit_tests/exporter/goods/views/test_good_detail.py
unit_tests/exporter/goods/views/test_material_product_details.py
unit_tests/exporter/goods/views/test_software_product_details.py

Change it from '/goods' to '/product-list'
[LTD-4079](https://uktrade.atlassian.net/browse/LTD-4079)
[LTD-4079]: https://uktrade.atlassian.net/browse/LTD-4079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update Exporter product list url

---

caseworker/advice/templates/advice/group-advice.html

https://uktrade.atlassian.net/browse/LTD-4144

LTD-4144-adds-additional-note-text

---

caseworker/assets/styles/components/_cases.scss
caseworker/cases/helpers/case.py
caseworker/cases/views/main.py
caseworker/templates/case/slices/appeal-details.html
unit_tests/caseworker/cases/views/test_case_details.py
unit_tests/conftest.py

Add appeals detail to case details page.
[LTD-4121](https://uktrade.atlassian.net/browse/LTD-4121)
[LTD-4121]: https://uktrade.atlassian.net/browse/LTD-4121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ltd 4121 case details appeal details

---

exporter/applications/forms/appeal.py

Update label on appeal form

---

caseworker/cases/views/finalisation/forms.py
caseworker/cases/views/finalisation/letters.py

As per 
https://uktrade.atlassian.net/browse/LTD-4159
Add subtitles to the forms.

LTD-4159-fix-heading-style-inform-letter 

---

caseworker/cases/views/finalisation/forms.py

Fixes a minor typo for inform letter.
[LTD-4194](https://uktrade.atlassian.net/browse/LTD-4194)
[LTD-4194]: https://uktrade.atlassian.net/browse/LTD-4194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LTD-4194] Fix inform letter typo

---

caseworker/cases/forms/change_sub_status.py
caseworker/cases/services.py
caseworker/cases/urls.py
caseworker/cases/views/main.py
caseworker/templates/case/form.html
caseworker/templates/core/form.html
caseworker/templates/core/includes/form.html
caseworker/templates/layouts/case.html
core/decorators.py
unit_tests/caseworker/cases/forms/test_change_sub_status.py
unit_tests/caseworker/cases/views/test_change_sub_status.py
unit_tests/conftest.py

Add a view to allow sub-statuses to be edited.
At the moment there is no link to this view, I'm thinking that we should add this link once we add the sub-status onto the product details page.
[LTD-4170](https://uktrade.atlassian.net/browse/LTD-4170)
[LTD-4170]: https://uktrade.atlassian.net/browse/LTD-4170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ltd 4170 sub status UI

---

caseworker/templates/includes/case-row.html
unit_tests/caseworker/conftest.py
unit_tests/caseworker/queues/views/test_cases.py

https://uktrade.atlassian.net/browse/LTD-4173

LTD-4173-show-sub-status

---

caseworker/templates/case/tabs/quick-summary.html
unit_tests/caseworker/cases/views/test_quick_summary.py

Display the sub-status in the quick summary tab.
[LTD-4176](https://uktrade.atlassian.net/browse/LTD-4176)
[LTD-4176]: https://uktrade.atlassian.net/browse/LTD-4176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-4176 Display sub status in quick summary tab.

---

caseworker/advice/templates/advice/case_detail.html
caseworker/core/templates/goods/includes/precedent_table.html
caseworker/tau/templates/tau/firearms_accessory_table.html
caseworker/tau/templates/tau/includes/product_document.html
caseworker/tau/templates/tau/includes/section5_firearm_act_1968.html
caseworker/tau/templates/tau/product_summary_table.html
caseworker/templates/case/includes/_legacy-product-on-case-summary.html
caseworker/templates/case/includes/selection-sidebar.html
caseworker/templates/case/slices/end-user-documents.html
caseworker/templates/case/tabs/quick-summary.html
caseworker/templates/layouts/base.html
caseworker/templates/organisations/organisation/details.html
caseworker/templates/spire/application_body.html
caseworker/templates/teams/markdown-help.html
exporter/core/templates/core/form-wizard.html
exporter/core/templates/goods/forms/firearms/rfd_certificate_download_link.html
exporter/templates/applications/goods/_static-goods-details-summary.html
exporter/templates/layouts/base.html
exporter/templates/organisation/details/index.html

fixing the codeXL issue found here
https://github.com/uktrade/lite-frontend/security/code-scanning 
it handles the Potentially unsafe external link warnings once these are cleared will raise PRs for other warnings

LTD-4199-CodeQL-warning

---

caseworker/templates/case/tabs/ecju-queries.html
exporter/templates/includes/ecju-queries.html

[LTD-4667](https://uktrade.atlassian.net/browse/LTD-4667)
[LTD-4667]: https://uktrade.atlassian.net/browse/LTD-4667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update templates to not show a grey rectangle if response is empty

---

core/common/forms.py
exporter/applications/forms/appeal.py
unit_tests/core/common/test_forms.py

Wrap base form actions in a button group
[LTD-4664](https://uktrade.atlassian.net/browse/LTD-4664)
[LTD-4664]: https://uktrade.atlassian.net/browse/LTD-4664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Wrap base form actions in a button group

---

ui_tests/caseworker/step_defs/test_enforcement.py

Fix a flaky test by waiting for text to be present.

Fix flaky eu xml import UI test

---

.circleci/config.yml

Cache pipenv directories as part of CI runs to decrease the run time of tests.

Cache pipenv

---

exporter/applications/forms/hcsat.py

Ltd 4778 neither neutral hcsat

---

caseworker/assets/styles/components/_cases.scss

This ticket is to add some quick and simple style improvements that enhance the user experience of those using the sidebar filters, with more comprehensive style changes to be deferred to a later date.
[LTD-4789](https://uktrade.atlassian.net/browse/LTD-4789)
[LTD-4789]: https://uktrade.atlassian.net/browse/LTD-4789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add simple style improvements for queue view cases filters

---

caseworker/templates/layouts/base.html

[LTD-3475](https://uktrade.atlassian.net/browse/LTD-3475)
[LTD-3475]: https://uktrade.atlassian.net/browse/LTD-3475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update footer text DIT to DBT

---

lite_content/lite_exporter_frontend/applications.py
lite_content/lite_exporter_frontend/strings.py
lite_content/lite_internal_frontend/cases.py

[LTD-4766](https://uktrade.atlassian.net/browse/LTD-4766)
[LTD-4766]: https://uktrade.atlassian.net/browse/LTD-4766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-4766 Change ultimate recipient to ultimate end-user

---

lite_content/lite_exporter_frontend/declaration.py

Change 'Her Majesty' to 'His Majesty'
[LTD-4850](https://uktrade.atlassian.net/browse/LTD-4850)
[LTD-4850]: https://uktrade.atlassian.net/browse/LTD-4850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Change 'Her Majesty' to 'His Majesty'

---

core/templates/accessibility/accessibility.html

Add accessibility support paragraph to accessibility statement
[LTD-4846](https://uktrade.atlassian.net/browse/LTD-4846)
[LTD-4846]: https://uktrade.atlassian.net/browse/LTD-4846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add accessibility support paragraph to accessibility statement

---

caseworker/cases/views/main.py

Small change to ensure that the case detail page does not error for F680 cases.  More changes will follow to refine the case detail page for these applications.

[F680] Ensure caseworkers can view F680 applications

---

exporter/apply_for_a_licence/forms/triage_questions.py
exporter/apply_for_a_licence/urls.py
exporter/apply_for_a_licence/views.py
unit_tests/exporter/apply_for_a_licence/forms/test_triage_questions.py
unit_tests/exporter/apply_for_a_licence/test_urls.py

F680 exporter application

---

caseworker/activities/views.py
caseworker/advice/views.py
caseworker/cases/views/main.py

This change ensures that the correct tabs are displayed and working on the F680 case detail pages.

[F680] Improve case tabs

---

caseworker/cases/views/main.py
caseworker/templates/case/slices/f680-details.html

Improves the data shown on case details page for F680 cases.

[F680] F680 case details slices

---

caseworker/advice/services.py
caseworker/advice/views.py

Ensure OGDs can offer advice/move case forward for F680 applications.

[F680] F680 OGD advice

---

exporter/apply_for_a_licence/forms/triage_questions.py
unit_tests/exporter/apply_for_a_licence/forms/test_triage_questions.py

Update description for F680 application option

---

caseworker/advice/rules.py
caseworker/advice/services.py
exporter/templates/includes/ecju-queries.html

[LTD-4868](https://uktrade.atlassian.net/browse/LTD-4868)
[LTD-4868]: https://uktrade.atlassian.net/browse/LTD-4868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove temporary BEIS names from lite-frontend

---

caseworker/external_data/urls.py
unit_tests/caseworker/external_data/test_views.py

Amended urls.py and tests.  Is this an obscure enough change of the URL?

LTD-4923-rename url path for denials upload

---

exporter/core/organisation/forms.py
exporter/core/organisation/validators.py
exporter/templates/core/registration/confirmation-registration-corporation-abroad.html
exporter/templates/core/registration/confirmation-registration-corporation-uk.html
exporter/templates/core/registration/includes/address-details-abroad.html
exporter/templates/core/registration/includes/address-details-uk.html
unit_tests/exporter/core/organisation/test_forms.py
unit_tests/exporter/core/organisation/test_organisation_views.py
unit_tests/exporter/core/organisation/test_validators.py

###Fix new registration bugs
* title not changing
* vat number instead of registration_number
* validation errors
* where is your organisation based
* organisation telephone number
[LTD-4882](https://uktrade.atlassian.net/browse/LTD-4882)
[LTD-4882]: https://uktrade.atlassian.net/browse/LTD-4882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ltd 4882 new registration bugs

---

caseworker/cases/helpers/case.py
caseworker/cases/views/main.py
caseworker/queues/views/cases.py
core/builtins/custom_tags.py

Ensure that crypto OIEL cases can be viewed on caseworker application.

[Crypto-OIELs] Ensure crypto OIELs can be viewed on caseworker

---

caseworker/cases/views/main.py

Fixes KeyError when viewing "Recommendations and decisions" tab.

[Crypto-OIELs] Fix KeyError when viewing recommendations tab

---

caseworker/advice/rules.py
caseworker/advice/services.py
caseworker/advice/views.py
unit_tests/caseworker/advice/views/test_give_approval_advice_view.py
unit_tests/caseworker/advice/views/test_refusal_advice_view.py
unit_tests/caseworker/advice/views/test_view_my_advice_view.py

Fixes filtering advice by team under "my advice" and for FCDO
[LTD-4899](https://uktrade.atlassian.net/browse/LTD-4899)
[LTD-4899]: https://uktrade.atlassian.net/browse/LTD-4899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Filter "my advice" by team

---

exporter/core/organisation/forms.py

[newreg-fix-organisation-title](https://github.com/uktrade/lite-frontend/tree/newreg-fix-organisation-title)

newreg-fix-organisation-title 

---

caseworker/cases/services.py
caseworker/cases/views/advice.py

Use single generic mechanism for determining finalisation advice.

[Crypto-OIELs] Crypto oiel approval documents

---

caseworker/templates/external_data/denial-detail.html

Reason for refusal field to be added to Denial Details page
[LTD-4977](https://uktrade.atlassian.net/browse/LTD-4977)
[LTD-4977]: https://uktrade.atlassian.net/browse/LTD-4977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-4977-add-reason-for-refusal-to-denial-details

---

exporter/templates/core/hub.html

Exporter dashboard Help and support tile update
[LTD-4946](https://uktrade.atlassian.net/browse/LTD-4946)
[LTD-4946]: https://uktrade.atlassian.net/browse/LTD-4946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-4946-add-help-email-and-number-to-exporter-dashboard

---

caseworker/advice/services.py
caseworker/advice/templates/advice/advice_details.html
caseworker/cases/objects.py
makefile
unit_tests/caseworker/cases/views/test_case_details.py

Make it so that final Advice can be given for cases where the only party records present are "open destination" records.

[Crypto-OIELs] Crypto oiels advice

---

caseworker/cases/views/main.py

Show licences tab for Open applications

---

README.md
tests_common/api_client/libraries/request_data.py

https://uktrade.atlassian.net/browse/LTD-4839
Small changes to company to get test passed.
Also updated e2e instructions if you want to see e2e tests running locally with visible Chrome or whatever you want.

LTD-4839-duplicates 

---

exporter/core/organisation/forms.py

update to error message for county or state box on address registration form
[LTD-4987](https://uktrade.atlassian.net/browse/LTD-4987)
[LTD-4987]: https://uktrade.atlassian.net/browse/LTD-4987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-4978 Change to error text on organisation sign-up

---

exporter/goods/forms/common.py

Changed hint text to give more context as to what incorporation means
[LTD-4985](https://uktrade.atlassian.net/browse/LTD-4985)
[LTD-4985]: https://uktrade.atlassian.net/browse/LTD-4985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-4985 Hint text tweak for incorporation

---

exporter/goods/forms/common.py

Added further context to hint text about govt classification of products
[LTD-4986](https://uktrade.atlassian.net/browse/LTD-4986)
[LTD-4986]: https://uktrade.atlassian.net/browse/LTD-4986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-4986 security grading hint text

---

exporter/core/organisation/forms.py
lite_content/lite_exporter_frontend/core.py
lite_content/lite_internal_frontend/organisations.py

Changed wording for CRN title for registration page for individual, commercial, within and outside uk.  Also amended wording on edit page
[LTD-2288](https://uktrade.atlassian.net/browse/LTD-2288)
[LTD-2288]: https://uktrade.atlassian.net/browse/LTD-2288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-2288-companies-house-registration-number 

---

exporter/core/organisation/forms.py
unit_tests/exporter/core/organisation/test_forms.py

resolved optional registration number

---

exporter/core/organisation/forms.py
unit_tests/exporter/core/organisation/test_forms.py

[LTD-5009](https://uktrade.atlassian.net/browse/LTD-5009)
[LTD-5009]: https://uktrade.atlassian.net/browse/LTD-5009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-5009 Optional registration number not optional issue

---

caseworker/advice/templates/advice/case_detail.html
caseworker/templates/case/denial-for-case.html
caseworker/templates/case/slices/denial-matches.html

Swap Reference for Regime Reference on Denial Matches insert on case details page.
Also amend the wording of Exact Match to Full Match and Partial Match to Possible Match
[LTD-4952](https://uktrade.atlassian.net/browse/LTD-4952)
[LTD-4952]: https://uktrade.atlassian.net/browse/LTD-4952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ltd 4952 add denial regime ref on denial match screen and amend partial/exact match wording

---

core/accessibility/views.py
exporter/core/views.py

Remove need for login for viewing of privacy statement and accessibility statement
[LTD-5024](https://uktrade.atlassian.net/browse/LTD-5024)
[LTD-5024]: https://uktrade.atlassian.net/browse/LTD-5024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-5024-make-accessibility-statement-and-privacy-notice-visible-before-login

---

caseworker/templates/case/slices/denial-matches.html

UAT fix where incorrect reference is displayed

fix-denial-column 

---

caseworker/cases/forms/denial_forms.py
caseworker/templates/external_data/help-build-query.html

https://uktrade.atlassian.net/browse/LTD-5028

LTD-5028-denial-search-help-text 

---

caseworker/assets/javascripts/__tests__/search-products.test.js
caseworker/assets/javascripts/search-products.js
caseworker/assets/styles/components/_all.scss
caseworker/assets/styles/components/_query-search.scss
caseworker/cases/forms/denial_forms.py
caseworker/cases/views/denials.py
caseworker/search/forms.py
caseworker/templates/case/denial-for-case.html
caseworker/templates/external_data/query-error.html
caseworker/templates/search/products.html
core/forms/layouts.py
ui_tests/caseworker/pages/product_search.py
unit_tests/caseworker/cases/test_denials_view.py

ltd-5027-denial-search-validation-message 

---

exporter/core/views.py
exporter/templates/core/help_support.html
exporter/templates/layouts/base.html
exporter/urls.py
unit_tests/exporter/core/test_views.py

https://uktrade.atlassian.net/browse/LTD-4999

LTD-4999-help-support

---

exporter/templates/applications/application.html
exporter/templates/applications/applications.html
exporter/templates/applications/drafts.html
lite_content/lite_exporter_frontend/applications.py

This changes "Name" to "Your reference" in the task list and summary pages of the exporter journey. There is also a slight spacing change which was asked for in the ticket.
[LTD-5001](https://uktrade.atlassian.net/browse/LTD-5001)
[LTD-5001]: https://uktrade.atlassian.net/browse/LTD-5001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update text and styling in exporter

---

caseworker/templates/case/denial-for-case.html
caseworker/templates/external_data/help-build-query.html

Allow searching of denials based on regime ref
Corresponding API PR [here](https://github.com/uktrade/lite-api/pull/2015)
[LTD-5040](https://uktrade.atlassian.net/browse/LTD-5040)
[LTD-5040]: https://uktrade.atlassian.net/browse/LTD-5040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD 5040 allow searching on regime reg ref

---

caseworker/advice/templates/advice/case_detail.html
caseworker/advice/templatetags/advice_tags.py
caseworker/cases/views/external_data.py
caseworker/templates/case/slices/denial-matches.html
unit_tests/caseworker/cases/views/test_external_data.py
unit_tests/caseworker/cases/views/test_quick_summary.py
unit_tests/conftest.py

https://github.com/uktrade/lite-frontend/tree/LTD-4940-remove-Denial-Entity-Redundant-fields
to go with the BE changes

LTD-4940-remove-Denial-Entity-Redundant-fields 

---

caseworker/templates/case/denial-for-case.html
caseworker/templates/external_data/help-build-query.html

Fixes  following 
https://uktrade.atlassian.net/browse/LTD-5059
https://uktrade.atlassian.net/browse/LTD-5061
https://uktrade.atlassian.net/browse/LTD-5062

minor-ui-fixes 

---

caseworker/templates/case/denial-for-case.html

Update the denials template in preparation for larger changes by fixing indentation and removing unused context variable and if statements that aren't used.
[LTD-5013](https://uktrade.atlassian.net/browse/LTD-5013)
[LTD-5013]: https://uktrade.atlassian.net/browse/LTD-5013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update indentation and remove unused toggles in denials template

---

core/assets/styles/components/_pagination.scss

Tidy pagination scss file.
This a small step along the path to updating the pagination for denials search.
I am tidying this first before making the actual changes that I need to make later.
[LTD-5013](https://uktrade.atlassian.net/browse/LTD-5013)
[LTD-5013]: https://uktrade.atlassian.net/browse/LTD-5013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ltd 5013 pagination tidy scss

---

caseworker/templates/external_data/help-build-query.html

[LTD-5070-type-help-txt](https://github.com/uktrade/lite-frontend/tree/LTD-5070-type-help-txt)

 LTD-5070-type-help-txt 

---

exporter/applications/services.py
exporter/applications/templatetags/url_filters.py
exporter/applications/views/common.py
exporter/assets/javascripts/main.js
exporter/assets/javascripts/sort_by.js
exporter/templates/applications/applications.html
exporter/templates/applications/drafts.html
ui_tests/exporter/conftest.py
unit_tests/exporter/applications/tags/test_url_filters.py
unit_tests/exporter/applications/views/test_applications_list.py

https://uktrade.atlassian.net/browse/LTD-5066
https://uktrade.atlassian.net/browse/LTD-5065

LTD-5066-5065-content

---

conf/base.py
conf/caseworker.py
conf/exporter.py

https://github.com/uktrade/lite-frontend/tree/LTD-4960-application-settings

LTD-4960-application-settings 

---

exporter/applications/forms/common.py
exporter/applications/templates/edit_application_form.html
exporter/applications/views/common.py

Disable minor edit flow

---

exporter/applications/views/goods/component/views/edit.py
exporter/applications/views/goods/firearm/views/edit.py
exporter/applications/views/goods/material/views/edit.py
exporter/applications/views/goods/platform/views/edit.py
exporter/applications/views/goods/software/views/edit.py
exporter/applications/views/security_approvals/edit_views.py

Add error checking for cases where the API received a bad request back when editing a product.

Add error for failed api request

---

exporter/applications/views/common.py
unit_tests/exporter/applications/views/test_application_task_list.py

LTD: Task list is only for applications that can be edited

---

.circleci/config.yml
caseworker/cases/constants.py
caseworker/cases/helpers/case.py
core/constants.py
exporter/applications/rules.py
exporter/applications/services.py
exporter/applications/views/common.py
exporter/goods/views.py
exporter/templates/applications/application.html
ui_tests/exporter/features/edit_standard_application.feature
unit_tests/conftest.py
unit_tests/exporter/applications/views/test_application_detail.py

Initiating major edits

---

.circleci/config.yml
caseworker/cases/constants.py
caseworker/cases/helpers/case.py
core/constants.py
exporter/applications/forms/common.py
exporter/applications/rules.py
exporter/applications/services.py
exporter/applications/templates/edit_application_form.html
exporter/applications/views/common.py
exporter/applications/views/goods/component/views/add.py
exporter/applications/views/goods/component/views/edit.py
exporter/applications/views/goods/firearm/views/edit.py
exporter/applications/views/goods/material/views/add.py
exporter/applications/views/goods/material/views/edit.py
exporter/applications/views/goods/platform/views/add.py
exporter/applications/views/goods/platform/views/edit.py
exporter/applications/views/goods/software/views/add.py
exporter/applications/views/goods/software/views/edit.py
exporter/applications/views/security_approvals/edit_views.py
exporter/goods/views.py
exporter/templates/applications/application.html
ui_tests/exporter/features/edit_standard_application.feature
unit_tests/conftest.py
unit_tests/exporter/applications/views/test_application_detail.py
unit_tests/exporter/applications/views/test_application_task_list.py

Hotfix uat amendments p1

---

caseworker/cases/constants.py
caseworker/cases/helpers/case.py
core/constants.py
exporter/applications/forms/common.py
exporter/applications/rules.py
exporter/applications/services.py
exporter/applications/templates/edit_application_form.html
exporter/applications/views/common.py
exporter/applications/views/goods/component/views/add.py
exporter/applications/views/goods/component/views/edit.py
exporter/applications/views/goods/firearm/views/edit.py
exporter/applications/views/goods/material/views/add.py
exporter/applications/views/goods/material/views/edit.py
exporter/applications/views/goods/platform/views/add.py
exporter/applications/views/goods/platform/views/edit.py
exporter/applications/views/goods/software/views/add.py
exporter/applications/views/goods/software/views/edit.py
exporter/applications/views/security_approvals/edit_views.py
exporter/goods/views.py
exporter/templates/applications/application.html
ui_tests/exporter/features/edit_standard_application.feature
unit_tests/conftest.py
unit_tests/exporter/applications/views/test_application_detail.py
unit_tests/exporter/applications/views/test_application_task_list.py

Hotfix dev amendments p1

---

caseworker/cases/views/denials.py
unit_tests/caseworker/cases/test_denials_view.py

[LTD-](https://uktrade.atlassian.net/browse/LTD-5072)

LTD-5072 Added replacement for \r

---

caseworker/cases/forms/change_licence_status.py

https://uktrade.atlassian.net/browse/LTD-5339

LTD-5339-cic-copy-change

---

core/constants.py
unit_tests/caseworker/cases/views/test_case_filters.py

https://uktrade.atlassian.net/browse/LTD-5340
Draft was missing from the Licence filter so added this and a test to check they're all there

LTD-5340-add-draft-licence-filter 

---

exporter/goods/forms/goods.py
exporter/goods/validators.py
unit_tests/exporter/goods/forms/test_forms.py
unit_tests/exporter/goods/test_validators.py

[LTD-5332](https://uktrade.atlassian.net/browse/LTD-5332)
[LTD-5332]: https://uktrade.atlassian.net/browse/LTD-5332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-5332 added validator for good name

---

core/assets/javascripts/disabling-button.js
exporter/applications/forms/common.py
exporter/assets/javascripts/main.js
exporter/assets/javascripts/sort_by.js
unit_tests/conftest.py
unit_tests/core/common/test_forms.py
unit_tests/exporter/applications/forms/test_amendments.py

Disable the major edit submission button after clicking to block multiple amendments from being generated.
[LTD-5391](https://uktrade.atlassian.net/browse/LTD-5391)
[LTD-5391]: https://uktrade.atlassian.net/browse/LTD-5391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ltd 5391 disable major edit button after click

---

caseworker/templates/organisations/organisation/details.html
exporter/core/organisation/forms.py
lite_content/lite_internal_frontend/organisations.py

https://uktrade.atlassian.net/browse/LTD-5427
Just some content changes

LTD-5427-content-changes-registration 

---

exporter/core/organisation/forms.py

LTD-5427-fix-register-content 

---

caseworker/organisations/forms.py
exporter/templates/core/registration/includes/registration-details-individual.html
unit_tests/caseworker/organisations/test_views.py

https://uktrade.atlassian.net/browse/LTD-5433
Copy changes to Frontend

LTD-5433-registration-confirm-copy-change

---

core/mock_sso/views.py
exporter/mock_sso/views.py

Allow logout to work on exporter SSO by clearing session data.

Exporter mock sso logout

---

core/decorators.py
exporter/licences/views.py
exporter/templates/layouts/base.html
exporter/templates/licences/licence.html
unit_tests/core/test_decorators.py
unit_tests/exporter/licences/test_views.py

Ensure that the frontend works without passing through advice on the API.
This also tidies up the licence detail view to use the TemplateView correctly.
[LTD-5454](https://uktrade.atlassian.net/browse/LTD-5454)
[LTD-5454]: https://uktrade.atlassian.net/browse/LTD-5454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ltd 5454 licence details page

---

exporter/templates/core/hub.html
lite_content/lite_exporter_frontend/hub.py

On exporter hub/main page update Apply tile text to: 
Start a new application for a standard individual export licence (SIEL).
Update Applications tab text to:
Find drafts, make edits and view the status of submitted applications.
[LTD-5480](https://uktrade.atlassian.net/browse/LTD-5480)
[LTD-5480]: https://uktrade.atlassian.net/browse/LTD-5480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD 5480 content update for exporter dashboard

---

conf/base.py
core/auth/utils.py
core/auth/views.py
core/feedback/forms.py
core/middleware.py
exporter/auth/services.py

https://uktrade.atlassian.net/browse/LTD-5493
Fix info logs not working which was missed when going to DBT platform .

Ltd-5493-fix-infologs

---

core/common/forms.py
core/wizard/views.py
exporter/applications/forms/parties.py
exporter/applications/views/parties/consignees.py
exporter/applications/views/parties/end_users.py
unit_tests/core/wizard/test_views.py

[LTD-5514](https://uktrade.atlassian.net/browse/LTD-5514)
[LTD-5514]: https://uktrade.atlassian.net/browse/LTD-5514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add meaningful title tabs for each step of setting consignee

---

core/middleware.py
unit_tests/core/middleware/test_sso_introspection.py

Clear a users session and log them out when their refresh token has expired.
[LTD-5554](https://uktrade.atlassian.net/browse/LTD-5554)
[LTD-5554]: https://uktrade.atlassian.net/browse/LTD-5554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ltd 5554 expired signature error

---

exporter/core/organisation/constants.py
exporter/core/organisation/forms.py
exporter/core/organisation/validators.py
unit_tests/exporter/core/organisation/test_forms.py

Changes to validation and associated error messages for number fields during exporter registration
[LTD-5511](https://uktrade.atlassian.net/browse/LTD-5511)
[LTD-5511]: https://uktrade.atlassian.net/browse/LTD-5511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD 5511 EORI, UK VAT number and SIC code validation changes

---

exporter/core/organisation/constants.py
exporter/core/organisation/fields.py
exporter/core/organisation/forms.py
unit_tests/exporter/core/organisation/test_forms.py

Add validation for address lines to match HMRC 35 char limit
[LTD-5566](https://uktrade.atlassian.net/browse/LTD-5566)
[LTD-5566]: https://uktrade.atlassian.net/browse/LTD-5566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-5566 add address line validation

---

caseworker/templates/organisations/organisation/details.html
exporter/core/organisation/constants.py
exporter/core/organisation/fields.py
exporter/core/organisation/forms.py
exporter/core/organisation/validators.py
exporter/templates/core/hub.html
exporter/templates/hmrc/select-organisation.html
lite_content/lite_exporter_frontend/organisation.py
lite_content/lite_internal_frontend/organisations.py
ui_tests/caseworker/step_defs/test_organisation.py
ui_tests/exporter/features/register_an_organisation.feature
ui_tests/exporter/step_defs/test_register_an_organisation.py
unit_tests/exporter/core/organisation/test_forms.py
unit_tests/exporter/core/organisation/test_organisation_views.py
unit_tests/exporter/core/organisation/test_validators.py

https://uktrade.atlassian.net/browse/LTD-5461
This PR resolves RC number by adding 
validation rules during registration and by changing the labels.

 LTD-5461-rc-changes 

---

.circleci/config.yml
README.md

Coverage has released a new version today and it's causing our `check_coverage` job to fail on CircleCI.  If we use the `config.yml `to get it to specifically install the latest working version from yesterday (7.6.4) and the jobs work okay.
[LTD-5647](https://uktrade.atlassian.net/browse/LTD-5647)
[LTD-5647]: https://uktrade.atlassian.net/browse/LTD-5647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Code coverage change on CircleCI

---

Pipfile
Pipfile.lock
tests_common/tools/helpers.py

Remove library that's unused
[LTD-5744](https://uktrade.atlassian.net/browse/LTD-5744)
[LTD-5744]: https://uktrade.atlassian.net/browse/LTD-5744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove usage of unused allure library

---

unit_tests/exporter/goods/forms/test_forms.py

Use dynamic future year to stop tests failing

Use dynamic future year to stop tests failing

---

exporter/templates/applications/goods-locations/goods-locations.html
exporter/templates/organisation/members/index.html
exporter/templates/organisation/roles/index.html
exporter/templates/organisation/sites/index.html
unit_tests/exporter/organisation/members/test_templates.py

[LTD-5185](https://uktrade.atlassian.net/browse/LTD-5185)
[LTD-5185]: https://uktrade.atlassian.net/browse/LTD-5185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix table data to use govuk table cell class

---

caseworker/templates/case/slices/f680-details.html

Make MTCR answer use a nicer display value on caseworker side.
[LTD-5802](https://uktrade.atlassian.net/browse/LTD-5802)
[LTD-5802]: https://uktrade.atlassian.net/browse/LTD-5802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LTD-5802] Tidy up F680 MTCR answers in caseworker screen

---

exporter/templates/applications/goods-locations/goods-locations-summary.html
exporter/templates/applications/party-summary.html
exporter/templates/applications/security-approvals/security-approvals-summary.html
ui_tests/exporter/features/submit_standard_application.feature

This updates the button text to 'Save and continue' instead of 'Submit' for two of the summary views, along with some small fixes to align elements properly on the page.
[LTD-5808](https://uktrade.atlassian.net/browse/LTD-5808)
[LTD-5808]: https://uktrade.atlassian.net/browse/LTD-5808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update button labels to 'Save and continue'

---

caseworker/cases/forms/finalise_case.py
caseworker/cases/views/advice.py

Show f680 approval info instead of nlr on finalisation
[LTD-5816](https://uktrade.atlassian.net/browse/LTD-5816)
[LTD-5816]: https://uktrade.atlassian.net/browse/LTD-5816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-5816 show f680 approval info instead of nlr on finalisation

---

exporter/templates/includes/notice.html

Fix for LTD-5809
[LTD-5809](https://uktrade.atlassian.net/browse/LTD-5809)
[LTD-5809]: https://uktrade.atlassian.net/browse/LTD-5809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix margin below help text

---

lite_forms/templates/components.html

https://uktrade.atlassian.net/browse/LTD-5830
fix duplicate date hint

LTD-5171-fix-date-hint

---

exporter/templates/applications/application.html

https://uktrade.atlassian.net/browse/LTD-5820
Removing case officer

LTD-5820-remove-case-officer 

---

exporter/applications/forms/common.py

New Content changes 
https://uktrade.atlassian.net/browse/LTD-5821

LTD-5821-application-edit-content 

---

core/templates/accessibility/accessibility.html

To update the accessibility statement
[LTD-5861](https://uktrade.atlassian.net/browse/LTD-5861)
[LTD-5861]: https://uktrade.atlassian.net/browse/LTD-5861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LTD-5861] - Update accessibility statement

---

exporter/core/organisation/constants.py
unit_tests/exporter/core/organisation/test_forms.py

added SC, further conversation to be had about the rest
[LTD-5824](https://uktrade.atlassian.net/browse/LTD-5824)
[LTD-5824]: https://uktrade.atlassian.net/browse/LTD-5824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-5824 added SC, further conversation to be had about the rest

---

caseworker/cases/urls.py
caseworker/cases/views/main.py
caseworker/f680/templates/f680/case/detail.html
caseworker/f680/templates/f680/case/summary.html
caseworker/f680/tests/test_views.py
caseworker/f680/urls.py
caseworker/f680/views.py
caseworker/templates/case/base-case-summary.html
caseworker/templates/case/slices/summary.html
caseworker/templates/includes/case-row.html
conf/caseworker.py
unit_tests/caseworker/cases/views/test_case_details.py

Add a stub case detail page for F680s.  This will be enriched with F680 details as we get deeper in to the workstream, but for now this is a shell to build upon.
[LTD-5887](https://uktrade.atlassian.net/browse/LTD-5887)
[LTD-5887]: https://uktrade.atlassian.net/browse/LTD-5887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LTD-5887] Add stub F680 case detail page

---

caseworker/queues/views/cases.py
unit_tests/caseworker/queues/views/test_cases.py

https://uktrade.atlassian.net/browse/LTD-5929
Change default sort order

LTD-5929-change-default-Q-sort-order 

---

exporter/f680/constants.py
exporter/f680/forms.py
exporter/f680/payloads.py
exporter/f680/views.py
unit_tests/exporter/applications/views/test_f680s.py

https://uktrade.atlassian.net/browse/LTD-5911
Remove name from F680 creation

LTD-5911-f680-drop-name 

---

exporter/core/organisation/constants.py
unit_tests/exporter/core/organisation/test_forms.py

Added FC while we're looking for approval for the rest.
[LTD-5934](https://uktrade.atlassian.net/browse/LTD-5934)
[LTD-5934]: https://uktrade.atlassian.net/browse/LTD-5934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-5934 added FC as a valid registration number

---

caseworker/f680/document/forms.py
caseworker/f680/document/urls.py
caseworker/f680/document/views.py
caseworker/f680/templates/f680/document/document-generation.html
caseworker/f680/tests/test_views.py
caseworker/f680/urls.py
caseworker/letter_templates/services.py

https://uktrade.atlassian.net/browse/LTD-5947
WIP initial screen to start the document generation journey

 LTD-5947-doc-generation-view 

---

core/forms/templates/gds/layout/radios.html
exporter/apply_for_a_licence/forms/triage_questions.py
exporter/apply_for_a_licence/views.py
exporter/core/templates/core/form.html
exporter/templates/applications/use-spire-triage.html
ui_tests/exporter/pages/apply_for_a_licence_page.py
unit_tests/caseworker/users/test_views.py
unit_tests/conftest.py
unit_tests/exporter/apply_for_a_licence/forms/test_triage_questions.py
unit_tests/exporter/apply_for_a_licence/test_views.py
unit_tests/exporter/conftest.py

Switch licence type question to a Django form.
[LTD-5971](https://uktrade.atlassian.net/browse/LTD-5971)
[LTD-5971]: https://uktrade.atlassian.net/browse/LTD-5971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Switch licence type question to a Django form

---

core/templates/accessibility/accessibility.html
exporter/templates/core/help_support.html
exporter/templates/core/hub.html

Update the contact us phone number on dashboard tile, help and support page and accessibility statement.
[LTD-5987](https://uktrade.atlassian.net/browse/LTD-5987)
[LTD-5987]: https://uktrade.atlassian.net/browse/LTD-5987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-5987 Updated phone number

---

exporter/f680/application_sections/approval_details/forms.py
exporter/f680/application_sections/approval_details/tests/test_views.py

On 'Is product controlled under ITAR' screen change conditional textbox to appear when 'no' radio button is selected when previously it appeared when 'yes' was selected.
[LTD-5980](https://uktrade.atlassian.net/browse/LTD-5980)
[LTD-5980]: https://uktrade.atlassian.net/browse/LTD-5980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-5980 change conditional textbox from yes to no

---

exporter/f680/application_sections/approval_details/forms.py

Remove duplicate titles for 2 questions in the approval details / product flow

F680 Remove duplicate titles for 2 questions in the approval details / product flow

---

exporter/templates/f680/supporting_documents/supporting-documents.html

https://uktrade.atlassian.net/browse/LTD-6003
Fix redirect one we finish with supporting documents go to notes

LTD-6003-redirect-further-notes-form 

---

exporter/f680/application_sections/approval_details/forms.py

Noticed during Tech QA that the title of the MOD sponsor page was wrong so fixed it up here.

fix mod sponsor title

---

caseworker/f680/recommendation/forms/forms.py
caseworker/f680/recommendation/services.py
caseworker/f680/recommendation/tests/test_views.py
caseworker/f680/recommendation/views.py
caseworker/f680/rules.py
caseworker/f680/templates/f680/case/recommendation/clear_recommendation.html
caseworker/f680/templates/f680/case/recommendation/form_wizard.html
caseworker/f680/templates/f680/case/recommendation/includes/case_details.html
caseworker/f680/templates/f680/case/recommendation/includes/recommendation_details_approve.html
caseworker/f680/templates/f680/case/recommendation/includes/recommendation_details_refuse.html
caseworker/f680/templates/f680/case/recommendation/recommendation.html
caseworker/f680/templates/f680/case/recommendation/view_my_recommendation.html
caseworker/f680/tests/test_rules.py
caseworker/f680/urls.py
caseworker/f680/views.py

Once user makes recommendation then they have an option to clear it.
Add side panel with case details.
[LTD-6051]: https://uktrade.atlassian.net/browse/LTD-6051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-6051: Add option to clear recommendations

---

caseworker/activities/forms.py
caseworker/activities/mixins.py
caseworker/activities/templates/activities/includes/case_history.html
caseworker/activities/templates/activities/notes-and-timeline.html
caseworker/activities/templatetags/url_helpers.py
caseworker/activities/tests/test_templatetags.py
caseworker/activities/views.py
caseworker/f680/templates/f680/case/base.html
caseworker/f680/templates/f680/case/notes-and-timeline.html
caseworker/f680/tests/test_views.py
caseworker/f680/urls.py
caseworker/f680/views.py
caseworker/templates/queues/cases.html
caseworker/templates/users/mentions.html

To add the notes and timelines tab to F680s
[LTD-6019](https://uktrade.atlassian.net/browse/LTD-6019)
[LTD-6019]: https://uktrade.atlassian.net/browse/LTD-6019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LTD-6019] F680s Notes and Timeline

---

caseworker/f680/outcome/tests/test_views.py
caseworker/f680/outcome/views.py
caseworker/f680/recommendation/views.py
caseworker/f680/templates/f680/case/outcome/form_wizard.html
caseworker/f680/templates/f680/case/outcome/includes/security_release_request_details.html
caseworker/f680/templates/f680/includes/recommendation_table.html
caseworker/f680/views.py
core/builtins/custom_tags.py

This change shows OGD recommendations for a case during the outcome flow.  Flow visible on the jira ticket.
[LTD-6069](https://uktrade.atlassian.net/browse/LTD-6069)
[LTD-6069]: https://uktrade.atlassian.net/browse/LTD-6069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LTD-6069] Show recommendations during F680 outcome flow

---

exporter/applications/forms/common.py
exporter/applications/payloads.py
exporter/applications/services.py
exporter/applications/views/common.py
ui_tests/exporter/pages/apply_for_a_licence_page.py
unit_tests/exporter/applications/forms/test_common.py
unit_tests/exporter/applications/views/test_apply_for_a_licence.py

Use the new endpoint that was created for export licence creation.
[LTD-6034](https://uktrade.atlassian.net/browse/LTD-6034)
[LTD-6034]: https://uktrade.atlassian.net/browse/LTD-6034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ltd 6034 update licence type endpoint

---

exporter/core/organisation/constants.py
unit_tests/exporter/core/organisation/test_forms.py

https://uktrade.atlassian.net/browse/LTD-6072
confirmation that we are allowed to add the new CRN is in the parent ticket

LTD-6072 added OC to CRN prefix

---

caseworker/f680/templates/f680/case/outcome/includes/outcomes_table.html

LTD: Display validity dates in outcomes table only for approvals

---

exporter/templates/applications/case-notes.html
ui_tests/exporter/features/submit_standard_application.feature
ui_tests/exporter/pages/check_your_answers_page.py
ui_tests/exporter/step_defs/test_standard_application.py

Fix an issue where adding a note when the application is still in draft would result in an error
[LTD-6101](https://uktrade.atlassian.net/browse/LTD-6101)
[LTD-6101]: https://uktrade.atlassian.net/browse/LTD-6101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix issue where submitting a note caused an error

---

.circleci/config.yml

Bump cache key for CircleCi tests

Bump cache key for CircleCi tests

---

exporter/f680/application_sections/approval_details/forms.py
exporter/f680/application_sections/approval_details/tests/test_views.py
exporter/f680/application_sections/approval_details/views.py
exporter/templates/f680/forms/help_ITAR.html

Changes to foreign technology and ITAR question page
[LTD-6175](https://uktrade.atlassian.net/browse/LTD-6175)
[LTD-6175]: https://uktrade.atlassian.net/browse/LTD-6175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LTD-6175 Changes to foreign technology and ITAR question page

---

caseworker/cases/constants.py
caseworker/cases/objects.py
caseworker/cases/tests/test_application_manifest.py
caseworker/cases/tests/test_objects.py
caseworker/cases/views/main.py
caseworker/core/services.py
caseworker/f680/tests/test_application_manifest.py
caseworker/f680/views.py
caseworker/templates/case/form.html
caseworker/templates/layouts/case.html
core/application_manifests/helpers.py
core/constants.py
exporter/applications/tests/test_application_mainfest.py
exporter/applications/views/common.py
exporter/core/objects.py
exporter/f680/conftest.py
exporter/f680/tests/test_application_mainfest.py
exporter/f680/tests/test_views.py
exporter/templates/applications/history.html
exporter/templates/f680/application_detail.html
unit_tests/caseworker/core/test_services.py
unit_tests/conftest.py
unit_tests/exporter/applications/views/test_amendments.py
unit_tests/exporter/applications/views/test_edit_application.py
unit_tests/exporter/conftest.py
unit_tests/helpers.py

Allow an exporter to amend a submitted F680s applications by cloning the original.
[LTD-6110](https://uktrade.atlassian.net/browse/LTD-6110)
[LTD-6111](https://uktrade.atlassian.net/browse/LTD-6111)
[LTD-6110]: https://uktrade.atlassian.net/browse/LTD-6110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LTD-6111]: https://uktrade.atlassian.net/browse/LTD-6111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LTD-6110] - F680 application Amend by Copy

---

caseworker/f680/outcome/tests/test_views.py
caseworker/f680/outcome/views.py

Basic de-duplication is done on all refusal reasons of the selected entities and prepopulated in the field.
[LTD-6178](https://uktrade.atlassian.net/browse/LTD-6178)
[LTD-6178]: https://uktrade.atlassian.net/browse/LTD-6178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ltd-6178: Prepopulate refusal reasons when deciding refuse outcome

---

exporter/core/views.py
exporter/templates/core/hub.html

To display the correct amount of notifications on the home page.
[LTD-6113](https://uktrade.atlassian.net/browse/LTD-6113)
[LTD-6113]: https://uktrade.atlassian.net/browse/LTD-6113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LTD-6113] - Fix user notifications on home page

---

exporter/applications/helpers/summaries.py
unit_tests/exporter/applications/views/test_delete_application.py
unit_tests/exporter/applications/views/test_surrender_application.py
unit_tests/exporter/applications/views/test_withdraw_application.py

Fix withdraw, surrender and delete views for case that don't have a sub type.
[LTD-6210](https://uktrade.atlassian.net/browse/LTD-6210)
[LTD-6210]: https://uktrade.atlassian.net/browse/LTD-6210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix deleting applications that don't have a case sub_type

---

caseworker/queues/views/forms.py
unit_tests/caseworker/queues/views/test_cases.py

Add case type filter to the queue view to enable showing SIELs or F680 cases.
[LTD-6160](https://uktrade.atlassian.net/browse/LTD-6160)
[LTD-6160]: https://uktrade.atlassian.net/browse/LTD-6160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LTD-6160] Add case type filter to queue view

---

exporter/templates/f680/forms/declaration.html
exporter/templates/f680/forms/subtitle_declaration.html
lite_content/lite_exporter_frontend/core.py
ui_tests/exporter/step_defs/test_login_logout.py

https://uktrade.atlassian.net/browse/LTD-6230
Some Content changes off the back of F680

LTD-6230-f680-content-changes

---

exporter/templates/f680/forms/declaration.html
exporter/templates/f680/forms/subtitle_declaration.html
lite_content/lite_exporter_frontend/core.py
ui_tests/exporter/step_defs/test_login_logout.py

https://uktrade.atlassian.net/browse/LTD-6239

LTD-6239-content-fixes

---

.circleci/config.yml

[Fix] Circle ci config when called by the api
