Pipfile, Pipfile.lock, conf/base.py, exporter/templates/licences/licences.html, exporter/templates/licences/nlrs.html
Fix for "ValueError: Missing staticfiles manifest entry for
'shared/lite-frontend/javascripts/accordian.js'" seen in Sentry
also make sure django extensions is in pipfile and make sure it's detected correctly
=> Assets fix: Refer to accordian.js via new path

core/builtins/custom_tags.py, exporter/core/helpers.py
The datetimes use current timezone by default (always aware) and the format
is failing to parse this resulting is no time displayed in UI.
=> LTD-136: Fix parsing of datetime in template tags

ui_tests/exporter/pages/exporter_hub_page.py
This makes the tests less flaky if the buttons are out of the view port then
make the webdriver try to scroll to the right position before trying to click
=> TEST: Scroll to element before clicking

ui_tests/caseworker/pages/goods_queries_pages.py
Scroll to picklist element before trying to click it, so that if it is off
screen it doesn't fail
=> TEST: Fix for flaky caseworker test

exporter/apply_for_a_licence/forms/open_general_licences.py, exporter/core/services.py, exporter/licences/filters.py, exporter/licences/urls.py, exporter/licences/views.py, exporter/templates/core/hub.html, exporter/templates/licences/nlrs.html, unit_tests/caseworker/conftest.py, unit_tests/exporter/conftest.py, unit_tests/exporter/licences/test_views.py
the licences view was four views mushed into one. I've seperated them.
=> Remove extra form field from licences filter + refactor exporter licences list page

caseworker/templates/components/goods-licence-reissue-list.html, ui_tests/caseworker/step_defs/test_finalise_case.py
The value is actually the total value, not the unit value.
API changes done to reflect that, this changes updates the test.
Another change is related to template error complaining about `javascript` block not being recognised.
=> Fix assertion on case finalise

caseworker/cases/helpers/advice.py, caseworker/cases/views/goods.py, caseworker/templates/case/slices/goods.html, unit_tests/caseworker/cases/test_views.py
This query parameter was triggering the cloudfround WAF and causing requests to
be blocked.
=> Bug: Change ?goods to ?good_ids in get param for review goods wizard

caseworker/cases/forms/respond_to_good_query.py, caseworker/templates/case/tabs/ecju-queries.html, core/assets/javascripts/query-response.js, exporter/applications/views/goods.py, exporter/ecju_queries/forms.py, exporter/ecju_queries/services.py, exporter/ecju_queries/urls.py, exporter/ecju_queries/views.py, exporter/goods/forms.py, exporter/goods/views.py, exporter/templates/ecju-queries/query-document-delete.html, exporter/templates/ecju-queries/respond_to_query.html, exporter/templates/includes/ecju-queries.html, exporter/urls.py, lite_content/lite_exporter_frontend/ecju_queries.py, tests_common/fixtures/apply_for_application.py, ui_tests/exporter/conftest.py, ui_tests/exporter/features/ecju_queries.feature, ui_tests/exporter/pages/respond_to_ecju_query_page.py, ui_tests/exporter/step_defs/test_ecju_queries.py, ui_tests/exporter/step_defs/test_goods.py
Changes to support document uploads when responding to an ECJU query or pre-visit questionnaire or Compliance action.
- create new templates, views as required
- Add new content strings
- Add browser tests
Updated query response page showing uploaded documents,
Once the query is closed,
=> LTD-305: Attach documents to ECJU query response

exporter/applications/views/goods.py
The back_url is being considered as good_pk causing this bug.
=> Provide correct good_pk to document grading form

exporter/applications/views/goods.py, exporter/goods/views.py, exporter/templates/goods/delete-document.html, ui_tests/exporter/features/goods.feature, ui_tests/exporter/pages/add_goods_page.py, ui_tests/exporter/pages/goods_page.py, ui_tests/exporter/step_defs/test_goods.py
When `draft_pk` is missing in kwargs it returns `None` but it was being converted to string using `str(kwargs.get("draft_pk"))` which assigns the value `"None"` to it resulting in this bug.
Fixed the existing browser test and extended it to be able to test this.
=> LTD-434: Cannot add new product to draft application

caseworker/templates/case/product-on-case.html, exporter/applications/views/goods.py, exporter/goods/forms.py, exporter/goods/helpers.py, exporter/goods/services.py, exporter/goods/views.py, exporter/templates/applications/goods/add-good-detail-summary.html, exporter/templates/goods/good.html, lite_content/lite_exporter_frontend/goods.py, ui_tests/exporter/conftest.py, ui_tests/exporter/features/submit_standard_application.feature, ui_tests/exporter/pages/add_goods_details.py, ui_tests/exporter/pages/add_goods_page.py, ui_tests/exporter/pages/product_summary.py, ui_tests/exporter/pages/standard_application/goods.py, ui_tests/exporter/step_defs/test_goods.py, ui_tests/exporter/step_defs/test_standard_application.py
To accurately categorise firearms products additional product types are introduced.
In the v3 Firearms flow Product type is the first screen (instead of Product category) as we will only be allowing Firearms products in the first version.
Moreover we cannot completely implement the flow in this PR because there are other tickets for the rest of the steps in the flow so this PR completes the flow to the extent possible. As we complete other tickets this needs to be adjusted.
The main difference is with respect to first four product types (Firearms, Ammunition, Components for firearms and Components for ammunition) where the next steps capture additional/new details (future tickets). So for now the next steps for all types are same as in current flow.
When adding a new product, after …
=> LTD-398: Accurately categorise Firearms related products

exporter/applications/views/goods.py
The old check was looking at the entire value of the dict rather than the key so
it would always return false
=> Look in item_category.key to figure out category

exporter/goods/forms.py, exporter/goods/services.py
If a form containing calibre or year of manufacture was submitted we were
getting the wrong validation error from the serializer saying that the value was
`invalid` instead of `null`.
This sets empty strings to null for both calibre and year of manufacturer so
that you get the right validation error back from the API
related API change: https://github.com/uktrade/lite-api/pull/663
=> LTD-392 Validation Fix for Firearm Details

exporter/applications/views/goods.py, exporter/goods/forms.py, exporter/goods/services.py, exporter/goods/views.py, exporter/templates/applications/goods/add-good-detail-summary.html, exporter/templates/goods/good.html, ui_tests/exporter/conftest.py, ui_tests/exporter/features/submit_standard_application.feature, ui_tests/exporter/pages/standard_application/good_details.py
Fixes issues found during review,
- When editing sporting shotgun either from Product summary or Product detail, we currently ask few additional questions instead of going directly to summary screen. Similarly for other fields
- Clicking back on sporting shotgun and product type again causes endless loop
- Changing product type from eg ammunition to firearms, it is possible to proceed with some questions having invalid value eg firearms replica - we are temporarily not allowing editing product type
=> Firearms navigation fixes

caseworker/cases/forms/review_goods.py, caseworker/cases/views/goods.py, unit_tests/caseworker/cases/forms/test_review_goods.py, unit_tests/caseworker/cases/test_views.py, unit_tests/conftest.py
This adds a new question to the good review form for standard applications that
allows caseworker to indicate if a good review sets precedent.
=> LTD-456 allow caseworker to indicate a good review sets precedent

caseworker/templates/case/product-on-case.html, caseworker/templates/case/review-good-base.html, caseworker/templates/case/review-good-standard.html, caseworker/templates/case/slices/goods.html, caseworker/templates/search/results_cases.html, exporter/applications/helpers/check_your_answers.py, exporter/applications/views/goods.py, exporter/goods/forms.py, exporter/goods/helpers.py, exporter/goods/services.py, exporter/goods/views.py, exporter/templates/applications/goods/add-good-detail-summary.html, exporter/templates/applications/goods/goods-detail-summary.html, exporter/templates/applications/goods/index.html, exporter/templates/applications/goods/preexisting.html, exporter/templates/goods/good.html, exporter/templates/goods/goods.html, tests_common/api_client/libraries/request_data.py, ui_tests/exporter/conftest.py, ui_tests/exporter/features/submit_standard_application.feature, ui_tests/exporter/pages/add_goods_page.py, ui_tests/exporter/pages/standard_application/goods.py, unit_tests/exporter/applications/forms/goods/test_goods.py, unit_tests/exporter/goods/test_forms.py
We now have product name, changes update various templates, filter options and also show in search results.
For existing products where `name` is not available, `description` is taken as name instead.
Updated browser tests.
=> LTD-285: Add product name to FE

exporter/applications/views/goods.py, exporter/assets/javascripts/add-good.js, exporter/goods/forms.py, exporter/goods/views.py
Firearms section certificate upload form fixes
- display the title as per the selected section
- don't clear the selected file on validation errors
- populate the selected filename when editing
Save selected file details temporarily in session and clear once
the request is completed successfully.
We setup `upload_handlers` to upload the file to S3. This gets processed as and when we read `request.POST` and the file
gets uploaded to S3 but if there is a validation error we use the saved details from session and populate the fileupload field with the previously selected file name. If the user wishes to replace then another file can be selected. This is required both when initially adding the certificate or when editing it from the summary screen.
While editing if user changes the section …
=> Firearms section certificate upload form fixes

caseworker/flags/forms.py, caseworker/flags/views.py, caseworker/templates/flags/flagging-rules-list.html
Frontend changes to specify exclusion entries for flags.
Flag will be applied if the goods doesn't contain any of the clc entries specified in the exclusion entries.
=> LTD-307: Update flagging rules to include exclusion entries

exporter/applications/views/goods.py
This fixes a bug with the serialisation of a new good when being added to an
application, there was an issue that if the user added a firearm certificate
then the control list entries would be lost. Fixing that bug in `lite-api`
also uncovered another bug in that only the first control list entry was
being sent to lite-api instead of the full list.
This commit makes sure the full list of `control_list_entries` is saved to the
session so it can be played back later.
=> LTD-507 Control List Entries cleared when adding new product to app

caseworker/routing_rules/forms.py, core/assets/javascripts/filter-checkbox-list-flags.js, core/assets/javascripts/routing-rules-flags.js
Design changes for the way flags are added and edited in routing rules
A routing rule can be applied if the case contain certain flags and does not contain some other flags. The UI allows setting up these two conditions and had to make sure a flag is included in either of the condition but not both. This change updates the design and fixes some of the inconsistencies in previous implementation.
All of the changes are in javascript mostly to show/hide controls, enable/disable and check/uncheck flags.
=> LTD-536: Routing rules flags section updates

conf/exporter.py, exporter/goods/forms.py, exporter/goods/services.py, unit_tests/exporter/goods/test_forms.py
This commit puts the recent limiting of adding products behind a feature flag
called FEATURE_FLAG_ONLY_ALLOW_FIREARMS_PRODUCTS. If this flag is not set then
all types of products can be added, however many of those scenarios are broken.
Enabling those broken flows allows up to identify where those things are broken
and raise bugs to fix them.
=> Re-enable adding of non firearm products

core/builtins/custom_tags.py
When a draft application is copied and End user has not uploaded document
then the status should be "In progress".
Currently we are only checking if the party is valid and marking as saved even though
there is no End user document uploaded. This should be marked as "In progress" if
no document is available.
=> Fix End user status correctly as in progress

core/builtins/custom_tags.py, unit_tests/core/builtins/test_custom_tags.py
This fixes the highlight_text filter so that XSS is not possible.
Fix for LTD-754: https://uktrade.atlassian.net/browse/LTD-754
=> LTD-754 Persistent XSS

conf/base.py, core/middleware.py, exporter/applications/forms/locations.py, exporter/applications/views/locations.py, exporter/templates/applications/goods-locations/goods-locations.html, unit_tests/core/test_middleware.py
The `return_to` parameter is used to set back-links in the application journey.
This adds a middleware to the application that validates if the `return_to` parameter is:
1. A valid URL
2. A relative URL
Would recommend reviewing commit-wise.
=> [LTD-751] Add middleware to validate `return_to` links

caseworker/organisations/views.py, lite_forms/templates/components/autocomplete.html
This is a example commit to show how to make autocomplete widget support using
the initial value from the form's data
=> Make autocomplete widget support reusing existing values

conf/base.py, core/middleware.py, unit_tests/core/test_middleware.py
During pen tests, we found that even when a user account was terminated on the SSO, the user would still be able to access LITE using browser cookies.
Other DIT services get around this by using introspection middleware. This middleware hits the introspection endpoint on the SSO service and caches the response for a small amount of time.
We are doing something very similar for LITE.
P.S. It's not introspection technically because we are not using the `/o/introspect` endpoint from the SSO service. In the case of `staff-sso`, it is because this endpoint requires a different token. For the case of `directory-sso`, I haven't been able to find an endpoint for introspection.
=> [LTD-775] Session Termination

Pipfile, Pipfile.lock, caseworker/auth/views.py, caseworker/templates/layouts/base.html, caseworker/urls.py, conf/base.py, conf/caseworker.py, core/feedback/forms.py, core/feedback/notify.py, core/feedback/templates/feedback/form.html, core/feedback/templates/feedback/thanks.html, core/feedback/urls.py, core/feedback/views.py, example.caseworker.env, example.exporter.env, exporter/auth/views.py, exporter/templates/layouts/base.html, exporter/urls.py, unit_tests/caseworker/conftest.py, unit_tests/caseworker/feedback/test_views.py, unit_tests/exporter/conftest.py, unit_tests/exporter/feedback/test_views.py
This does 3 things -
1. Adds user email to the session. This is used in the feedback loop.
2. Adds a `feedback` app with 2 views. The first view renders a feedback form. The second view says thank you. In between the 2 views, user feedback (along with user email) is sent to a specified email inbox for triage via Notify.
3. Adds a Beta banner with a link to the feedback.
The tests cover most code paths. The only assumption is for `send_email_notification` to throw a subclass of `RequestException` when it fails. I have checked this. It does. 
I haven't included any tests for the beta banner. This is because I have chosen to put it in the template without any conf switches. I feel that it is unlikely that we will need to remove it quickly i.e. with just a config change instead of a PR.
P.S. …
=> [LTD-755] User Feedback

caseworker/external_data/forms.py
Upload currently failing with the error that "File was not opened in read mode".
We are using FILE_UPLOAD_HANDLERS which defaults to S3FileUploadHandler.
This is creating a S3Boto3StorageFile instance in write mode so when
we try to read it from this, it is complaining that it is not opened in read mode.
Fix this by reading it from the s3 object that is uploaded.
=> LTD-801: Fix denials upload failure

exporter/applications/forms/goods.py, exporter/applications/services.py, exporter/applications/views/goods.py, exporter/goods/services.py, exporter/goods/views.py, exporter/templates/goods/good.html, unit_tests/exporter/goods/test_views.py
Remove application specific details (Year of manufacture and Identification markings) from the product detail page on exporter side.
Noticed adding a product to product list is broken because we are sending kwargs as positional arguments resulting in incorrect values for some of the variables, fixed as part of this change.
=> LTD-508: Remove application specific details from Product detail page

caseworker/templates/layouts/base.html, exporter/templates/layouts/base.html
We haven't done cookie consent so we shouldn't use GA.
This PR means that not using GA = remove the GA key from env vars.
=> Remove GA code if there is no GA key.

caseworker/cases/views/main.py, caseworker/flags/forms.py, lite_content/lite_internal_frontend/flags.py
[LTD-878](https://uktrade.atlassian.net/browse/LTD-878) Users should be able to block cases from being finalised
(ATM, they can block cases from being approved only)
This has 3 parts -
1. [lite-api](https://github.com/uktrade/lite-api/pull/768) - I think this is where the business logic lives. This is the important [commit](https://github.com/uktrade/lite-api/pull/768/commits/877b1fa92775c8b5952d58df638afc7e2bd56825). The rest is me renaming a field.
2. [lite-content](https://github.com/uktrade/lite-content/pull/282) - Because I renamed the field, the header in this CSV needed to be updated.
3. [lite-frontend](https://github.com/uktrade/lite-frontend/pull/196) - There was some logic here that needs updating. Hopefully for presentation only. I also renamed a class to reflect the change.
I …
=> Change BlocksApproval to BlocksFinalising.

exporter/auth/views.py
Great SSO is rolling out social auth. We do not want people who e.g. login to Great using LinkedIn to be able to access LITE. This PR proposes changes that do this.
ATM, I get the following when logging in using an email (test user) -
```
2021-05-26T11:21:52.11+0100 [APP/PROC/WEB/0] ERR {"asctime": "2021-05-26 11:21:52,112", "levelname": "WARNING", "message": "Authenticating exporter with Great SSO: {'id': 80159, 'email': 'test+3a1e062c0c96412583ee25ee5fab8215@ci.uktrade.io', 'hashed_uuid': '3b9df322c39bbe86967ce8e76c0557e3f72baae2b4eb30e98a37c24ff9b319fe', 'social_login': False, 'user_profile': {'first_name': 'Automated', 'last_name': 'Test', 'job_title': 'AUTOMATED TESTS', 'mobile_phone_number': '5347428247784', 'segment': None, 'profile_image': None, 'social_account': 'email'}}", …
```
=> Stop great social

core/client.py, unit_tests/core/test_api_client.py
So we PaaS attached Zipkin headers to all requests hitting a service. Unless these headers are already there.
So when a user e.g. browser to a Case in the FE, we get the headers for free. What is left is to attach these headers onto the API calls so that we can trace each request as it makes its way through the services.
=> Forward Zipkin headers to API.

ui_tests/exporter/conftest.py, ui_tests/exporter/features/siel_firearm_application.feature, ui_tests/exporter/step_defs/test_standard_application.py
Add test scenarios that verify the filling of End use, Locations and Route of goods section in Application.
Most of the steps are reused and additional steps are added to assert things.
All of these scenarios are very similar hence included in the same PR. We could add Consignee and End user sections also but since they are related to each other they will be done as a separate PR.
=> LTD-920-921-922: Add UI test that verifies the End use, Locations and Route of goods sections in application

ui_tests/caseworker/conftest.py, ui_tests/caseworker/features/view_standard_application.feature, ui_tests/caseworker/step_defs/test_view_standard_application.py
When an application is submitted a document is auto generated with the
application details. This test verifies that this document is available
and that the internal caseworker can download this document.
=> LTD-939: Add ui test to verify caseworker viewing application document

exporter/applications/helpers/date_fields.py, exporter/applications/views/goods.py, exporter/core/validators.py, exporter/goods/services.py, exporter/organisation/views.py, ui_tests/exporter/features/siel_firearm_application.feature, unit_tests/exporter/applications/views/test_goods.py, unit_tests/exporter/organisation/test_views.py
Hello team. I need your help with this. Here is the situation -
**Context:**
In this ticket, we wanted to ensure that the expiry date entered as part of the firearm certificate was (1) not in the past and (2) not > 5y into the future. @eadpearce had a run at it and decided that we should put this validation in the FE. 
(This has repercussions that I don't want to get into here so DM if you want to chat about this)
There are 4 different views that ask users to upload a firearm certificate. So I chose to put the validation logic in a [function](https://github.com/uktrade/lite-frontend/pull/225/commits/04ceb4eda8cc36d80072fe8da49853668e1be146) and call it in these [4 views](https://github.com/uktrade/lite-frontend/pull/225/commits/c3057c4cb22ca60eb659cd864f9f4429ee7813ad).
**Problem**
It was …
=> Ltd 855 expiry validation 2

caseworker/routing_rules/forms.py
This removes the "system flags" from the dropdown when a user is trying to create a routing rule.
=> [LTD-989] Remove system flags from routing rule dropdown.

caseworker/cases/services.py, ui_tests/caseworker/features/routing_rules.feature
System flags are applied/removed by the system depending on the case attributes so
defining a routing rule using these flags results in inconsistent behaviour.
To avoid this remove these flags from being selected by the user.
=> LTD-1055: Remove System flags from being selected when creating a routing rule

caseworker/cases/views/goods.py, caseworker/templates/case/slices/goods.html, unit_tests/caseworker/cases/test_views.py
When there are multiple products on an application we select the ones to be
reviewed and click "Review" button. The review page is provided the list
if ids of the underlying "Good" instance in "GoodOnApplication".
This works ok if the same Good is added once but if the user used the same
"Good" to add multiple products to the application then we are always
selecting the first "GoodOnApplication" instance that matches with the given
Good id hence displaying incorrect quantity value in the review page.
=> LTD-1107: Provide GoodOnApplication id as key when reviewing the product

caseworker/cases/helpers/advice.py, caseworker/flags/views.py, unit_tests/caseworker/flags/test_views.py
This form allows user to assign specific flags to a product on application and it
receives a list of ids. These were product ids (Good model) but when we fixed an
issue with review goods form this has changed to ids of GoodOnApplication.
Because of this the backend is not able to find relevant object and throwing
'not found' error as response. Fix this by extracting the relevant Good ids
in the form.
=> LTD-1276: Fix product flags form to provide good id to assign flags correctly

caseworker/templates/case/tabs/licences.html
Because description is optional and can be empty
=> LTD-1418: Display name instead of description under licences tab

Pipfile, Pipfile.lock
CircleCI tests occasionally fail due to package inconsistency (E.g. `metadata exception`). This solves that
=> Explicitly state importlib-metadata version to fix some tests

caseworker/advice/forms.py, caseworker/advice/services.py, caseworker/advice/views.py, caseworker/teams/services.py, unit_tests/caseworker/advice/views/test_countersign.py
Update form to select the queue to be returned to in case countersign
is refused. Case gets moved to the selected queue if countersigning is
refused.
=> LTD-1238: Add option to return to advisor when countersign is refused

caseworker/advice/forms.py, caseworker/advice/services.py, caseworker/advice/views.py, core/forms/templates/forms/checkbox_option.html, unit_tests/caseworker/advice/views/test_edit_advice.py, unit_tests/caseworker/advice/views/test_give_approval_advice_view.py, unit_tests/caseworker/advice/views/test_refusal_advice_view.py
This one does a bunch of interesting things. E.g. -
1. Checks for `FCO` users and renders a different form for them by overriding the `get_form` method.
2. It adds a method to `CaseMixin` that returns the list of countries for which advice has not been given (yet).
=> [LTD-1386] Country Select for FCDO users

caseworker/advice/templates/advice/view-advice.html, caseworker/advice/urls.py, caseworker/advice/views.py, unit_tests/caseworker/advice/views/test_view_ogd_advice.py
Started this as `LTD-1232` but it seemed that it would be uncontroversial to address `LTD-1230` here as well.
As usual, I have taken some liberties in deviating from designs where I felt that I could keep the functionality and address the semantics in a follow-up ticket.
=> Add views for countersign and consolidate advice.

caseworker/advice/forms.py, caseworker/advice/services.py, caseworker/advice/templates/advice/view_my_advice.html, caseworker/advice/views.py, unit_tests/caseworker/advice/views/test_view_my_advice_view.py
We were using system flags to ensure that the case is only moved to countersigning queue when we have advice for all destinations.
While working on it, I realized - the routing is run when the user presses the `I am Done` button. What if we could hide/disable the button until we have advice for all the destinations?
If we could do this (this PR), we don’t need any routing changes or create new system flags, etc.
Just one little thing that is bothering me - when this button is disabled, we should probably display a message that tells users why it is disabled.
=> [LTD-1342] Move case forward

tests_common/helpers/applications.py
The way we provide location data is changed recently hence updating the
helper function otherwise tests fail.
=> Update test helper function with location changes

caseworker/advice/services.py, caseworker/advice/templates/advice/advice_details.html, caseworker/advice/templates/advice/review_countersign.html, caseworker/advice/templates/advice/view_countersign.html, caseworker/advice/urls.py, caseworker/advice/views.py, core/builtins/custom_tags.py, unit_tests/caseworker/advice/views/test_countersign.py
A case with e.g. 2 destinations and 2 goods, has 4 distinct **advice-subjects**. 
As a result, when we save `approval-all` or `refuse-all` advice, we create 4 advice records - one for each subject and send it to the API. 
P.S. This is important and will come in handy when we tackle variable advice.
The flip side to this is that e.g. the countersigner is having to process advice for each subject separately whereas according to the designs, he/she should be able to process the advice from a given advisor as a whole.
What we need to do is to somehow group advice from the same user but different destinations and products into the same block for the purpose of countersigning.
This PR fixes this & hopefully improves on a few other minor things E.g. -
* I have put in a new template …
=> Fix countersign review.

caseworker/advice/forms.py, caseworker/advice/templates/advice/review_countersign.html, caseworker/advice/templates/advice/view_countersign.html, caseworker/advice/views.py
We have a few views that render a list of user-advice with formsets. Each form in the formset renders a `ChoiceField` of queues that are accessble to the user.
This PR introduces `QueueFormset` so that we can re-use some of the code for this in other places.
=> [LTD-1231] Refactor Formset View

caseworker/advice/templates/advice/view_my_advice.html
Also it is not required as per design.
=> LTD-1508: Remove dummy back link on View advice page

caseworker/advice/forms.py, caseworker/advice/templates/advice/advice_details.html, caseworker/advice/templates/advice/approve-advice-details.html
Two simple bug fixes,
- Footnote added when giving advice is not displayed when viewing the advice
It is also included when reviewing and viewing the countersigned advice
- Update dummy refusal criteria link with the correct link
=> LTD-1505-1507: Add missing footnote and correct refusal criteria link

caseworker/templates/case/review-good-standard.html
This attribute is not a boolean, it has three choices so yesno is
not the correct tag for this. Currently any value other than False
is displayed as grading required which is not correct. Fix by
removing the yesno tag.
=> LTD-1502: Fix the tag for displaying PV grading value in Review good page

caseworker/advice/templates/advice/select_advice.html
Fix it to take it to advice overview page, currently it is behaving as
browser back button so user is stuck in a loop
=> LTD-1526: Fix back link in select advice page

caseworker/advice/services.py, caseworker/advice/templates/advice/advice_details.html, unit_tests/caseworker/advice/views/test_countersign.py
When the countersigner doesn't agree with the recommendation the case is
sent back to advisor along with the queue it needs to go back but this
was unassigning the case from it's current set of queues. We only want
it to be unassigned from the countersigning queue and it fixes this.
=> LTD-1529: Retain case queues when countersigning is refused

caseworker/advice/views.py, unit_tests/caseworker/advice/views/test_give_approval_advice_view.py, unit_tests/caseworker/advice/views/test_refusal_advice_view.py
Only exclude a destination when it has already been advised on by the current user's team.
=> Consider team when filtering destinations

caseworker/advice/templates/advice/case_detail.html, caseworker/advice/templatetags/advice_tags.py, unit_tests/caseworker/advice/templatetags/test_advice_tags.py
Currently when displaying security grading we are looking for pv_grading_details
which is actually a dict, we should be using is_pv_graded which is a string and
the values of all products are joined and displayed as a comma separated value.
If the product is security graded we should also display the actual grading
instead of yes/no so a follow up is required to display more details.
=> LTD-1571: Fix display of security grading value in case details summary

caseworker/advice/templates/advice/view_countersign.html, caseworker/advice/views.py
Small one. It does 2 things on the `/countersign` screen -
1) It only shows the `Edit recommendation` button if you wrote the recommendation. This is a bit gnarly because of multiple advice objects etc. I have tried to get around this by using sets.
2) It puts the `move-case-forward` machinery in here. I have no idea how or why it was missing up until now.
=> [LTD-1586] Countersign move

caseworker/advice/services.py, unit_tests/caseworker/advice/views/test_consolidate.py, unit_tests/caseworker/advice/views/test_consolidate_edit.py, unit_tests/caseworker/advice/views/test_edit_advice.py
If the licence is being issued for an application and it contains
NLR items then we have to generate NLR letter besides the main licence
document. The NLR letter is only generated if there is a final advice
for NLR items also.
To keep it consistent with Advice1.0, post NLR advice for other
advice levels as well.
=> LTD-1595: Post advice for NLR items also

caseworker/advice/templates/advice/view-advice.html
Currently when there are no recommendations on the case and the user tries
to countersign or consolidate then we display the Give advice button which
is not ideal. Disable this for countersign, consolidate.
=> LTD-1559: Only give an option to give advice when there are no recommendations

caseworker/advice/views.py, unit_tests/conftest.py
Some of the LU countersign required are of flag level "destination" so while
determining whether LU countersign required or not check flags of all levels.
Currently we are only checking flags of "Case" level and thus determining
that countersigning is not required even though the flag is applied to the case.
=> LTD-1594: Check flags of all levels to determine if LU countersign required or not

example.caseworker.env, example.exporter.env
This is to stop the tests or local development from connecting to s3 when uploading files
=> Add memory or temp upload handlers as defaults in env

caseworker/advice/services.py, unit_tests/caseworker/advice/views/test_consolidate.py, unit_tests/caseworker/conftest.py
When LU consolidates they need to review advice given by OGDs, in this
case FCDO and MOD-ECJU. Currently we first filter them by "user" level
and filter according to the teams but the consolidated advice given by
MOD will be at "team" level hence not available for review by LU.
Fix this by including the "team" level advice if LU is consolidating.
=> LTD-1591: Show MOD-ECJU advice also for LU consolidation

caseworker/advice/templates/advice/group-advice.html
Correct attribute was not used hence we were displaying the default message
=> LTD-1629: Fix display of reasons provided for the advice

caseworker/advice/views.py, unit_tests/caseworker/advice/views/test_consolidate.py
This adds `no_licensen_required` to the list of advice types that are approve-like in this context.
=> Add no_license_required to approval types.

caseworker/advice/templates/advice/advice_details.html, caseworker/advice/templates/advice/group-advice.html
If there are multiple paragraphs in advice reason, licence condition, footnotes etc
then they are getting removed and presented as a single block of text which makes
it very difficult for the user to read and understand.
=> LTD-1647: Restore paragraph breaks for advice fields in templates

caseworker/advice/forms.py, caseworker/advice/templates/advice/review_countersign.html
Users after submitting recommendation they have move the case forward so
that it is routed to correct team. If the case is not moved forward then it
will still remain in their queue. This is a two step process. Having the
label as just submit may cause confusion as it has already been submitted
to other teams so change the label to make it more clear.
=> LTD-1646: Change submit button label to underline two step process

caseworker/advice/views.py, unit_tests/caseworker/advice/views/test_consolidate_edit.py
With conflicting user-level advice, a final proviso advice meant that `consolidate_edit` view was rendering a `ConsolidateSelectAdvice` form instead of `ConsolidateApprovalForm`.
=> [LTD-1665] Mixed advice renders the wrong consolidate form

caseworker/advice/templates/advice/view_my_advice.html
Adds the navigation menu to the view recommendations screen.
=> LTD-1698: Add missing tab navigation

caseworker/advice/forms.py, unit_tests/caseworker/advice/views/test_edit_advice.py, unit_tests/caseworker/conftest.py
In the updated refusal criteria some are deprecated so skip them so that
user cannot select these items.
Previous refusal advice may be referring to these deprecated items so only
skip in the form but display them as is when viewing the advice.
=> LTD-1733: Skip inactive refusal criteria items

caseworker/templates/case/product-on-case.html, caseworker/templates/case/review-good-standard.html, exporter/applications/services.py, exporter/core/helpers.py, exporter/goods/forms.py, exporter/goods/services.py, exporter/goods/views.py, exporter/templates/applications/goods/add-good-detail-summary.html, exporter/templates/applications/goods/goods-detail-summary.html, lite_content/lite_exporter_frontend/goods.py, unit_tests/caseworker/cases/test_views.py, unit_tests/exporter/applications/views/test_add_good.py, unit_tests/exporter/applications/views/test_add_good_to_application.py, unit_tests/exporter/goods/test_forms.py, unit_tests/exporter/goods/views/test_good_detail.py, unit_tests/exporter/goods/views/test_single_form_views.py
This updates the question posed as to whether a product has serial numbers or not. Originally this was a boolean choice, whereas now the exporter can choose to indicate that their product has serial numbers but would like to provide them at a later date.
There are some additional changes to some of the affected HTML files to tidy up their indentation which was inconsistent and sometimes confusing, the [ first commit](https://github.com/uktrade/lite-frontend/pull/445/commits/ffff340ac2ae476c7360bc0923367a7d8bbf588a) has the bulk of the core changes without the HTML indentation changes.
=> Ltd 1358 serial number question updates

caseworker/cases/helpers/case.py, caseworker/core/services.py, core/constants.py, exporter/applications/helpers/check_your_answers.py, exporter/applications/services.py, exporter/applications/urls.py, exporter/goods/forms.py, exporter/goods/services.py, exporter/goods/views.py, unit_tests/exporter/applications/helpers/test_check_your_answers.py, unit_tests/exporter/goods/test_forms.py, unit_tests/exporter/goods/views/test_single_form_views.py
Adds a form view, and link to said form view from the application details page, to allow serial numbers to be added later.
There are two different cases where we want to allow exporters to update serial numbers, either because they've explicitly said they would like to do it later or because they've said they could add them straight away yet only added a few of them.
=> Enter serial numbers later

caseworker/cases/views/main.py
remove routes section in details of caseworker side, as it is replaced by new locations code
=> remove routes section in details of caseworker side

exporter/applications/helpers/check_your_answers.py, exporter/goods/services.py, unit_tests/exporter/applications/views/test_add_good_to_application.py
Fixes an issue with serial numbers incorrectly being copied when adding a preexisting product and selecting the serial numbers to be deferred on the new product.
=> Ltd 1976 serial numbers being remembered across products

cypress/integration/caseworker/application.spec.js, cypress/support/commands.js
The intent of this PR is to prevent us from having to go through sso via client side, adding credentials in the browser and then navigating to internal domain.
The way we workaround all these steps and manage successfully authenticate to the app is by:
- submit a GET to sso login url and extract the csrftoken
- submit a POST to sso login with correct body/header and csrftoken from the first step
- persist the sessionId cookie generated by the POST
All the above is done within less than a second which means we save quite some time compared to previous way we were logging in.
=> Improve the way we login into sso

core/auth/views.py, core/middleware.py
GOV.UK only has a token valid for 3 mins. 
So when we run introspect which happens for every call. When the call gives a 401 it results in a forced logout. 
This now uses a renews using the refresh token on every call if it expires so we obtain a new one which is valid for a further 3 mins. 
It's added more complexity to the code since we still have to handle GREAT/SSO using the same middleware which doesn't support openid and had longer living tokens so refresh isn't required. 
I'm also surprised no tests have broken, which means we have no unit test coverage for middleware a task for another day.
=> LTD-1956-fix-introspect-forced-logout 

exporter/applications/forms/parties.py, unit_tests/exporter/applications/forms/test_parties.py
Remove the logic that hides the GB filter. This is due to the NI changes. 
Assumption here is that it was hardcoded filter so this filter is no required on this form.
=> LTD-2064-NI-Remove-logic-hide-GB 

caseworker/cases/helpers/case.py, caseworker/cases/views/main.py, caseworker/templates/case/slices/end-user-documents.html, core/builtins/custom_tags.py, unit_tests/core/builtins/test_custom_tags.py
Add new section to Case summary page to display the details of documents uploaded by End-user in the internal site.
When documents are available and uploaded,
When not available,
=> LTD-1369: Show End-user documents on the internal site Case details page

caseworker/templates/case/slices/destinations.html, caseworker/templates/case/slices/end-user-documents.html, exporter/core/views.py
Case summary page has a new section to show End-user documents. This is
added as part of English translation document changes but currently we also
show these details in destinations table on the same page so the designs
are updated to show all parties documents in this new section and remove
it from the destinations table.
=> LTD-1369: Show all parties documents in one place

caseworker/cases/views/main.py, caseworker/templates/case/slices/end-user-documents.html, exporter/applications/forms/parties.py, exporter/applications/helpers/parties.py, exporter/applications/helpers/task_lists.py, exporter/applications/urls.py, exporter/applications/views/parties/end_users.py, exporter/core/constants.py, exporter/core/helpers.py, exporter/templates/applications/party-summary.html, exporter/templates/layouts/task-list.html, unit_tests/conftest.py, unit_tests/exporter/applications/views/parties/test_end_users.py
An exporter may need to provide End-user EC3 document depending on goods starting location, destination and product type.
End-user journey is updated to ask for this document if the above conditions are met.
We only need this if goods are starting from NI, going to EU and firearms type is not software or technology related.
User can either upload a document or give an explanation for not having it. But both of these are optional.
The details required to determine (location, destination, type) are not all captured in one place, since user can complete these details in any order it is not possible to determine this requirement when user entering end-user details because he may not have added product details or starting location etc hence we display a banner notifying the user that he may …
=> LTD-1642: Provide option to upload EC3 document

ui_tests/caseworker/conftest.py, ui_tests/caseworker/features/enforcement.feature, ui_tests/caseworker/step_defs/test_enforcement.py
Enforcement checks are done on parties of an application. We first export
the data in an xml file and after the checks are performed another file
is imported which contains data to update the application based on the
checks.
In this test we generate the file to be imported based on the parties
data and once imported we assert that the application is updated or not.
=> LTD-2035: Add ui test that verifies enforcement check by importing the file

conf/exporter.py, exporter/applications/templatetags/additional_documents.py, exporter/applications/views/goods/add_good_firearm.py, exporter/applications/views/goods/goods.py, exporter/core/constants.py, exporter/core/helpers.py, exporter/organisation/services.py, exporter/organisation/views.py, exporter/templates/applications/additional-documents/additional-documents.html, unit_tests/exporter/applications/views/test_add_good_firearm.py
This updates the flow for when the exporter is asked to add and/or validate their RFD certificate.
In particular this is to handle the following:
- When an exporter marks their firearm certificate as invalid we remove it from the organisation
- When an exporter marks their firearm certificate as valid we also attach it as a supporting document
- When an exporter adds a new firearm certificate we add it to the organisation and attach it as a supporting document
- The system attached firearm certificate is not able to be deleted by the user
=> Remove the rfd certificate if user marks it as invalid

exporter/applications/urls.py, exporter/applications/views/goods/add_good_firearm.py, exporter/core/templates/goods/forms/firearms/product_document_download_link.html, exporter/goods/forms/firearms.py, exporter/goods/services.py, exporter/templates/applications/goods/firearms/product-summary.html, unit_tests/conftest.py, unit_tests/exporter/applications/views/conftest.py, unit_tests/exporter/applications/views/test_edit_firearm.py
Add view to edit product document options i.e., 1. editing product document, 2. editing document sensitivity option, 3. editing document availability option.
The questions 2 and 3 trigger subsequent questions so they are implemented as separate mini-wizards.
The common bits are refactored into a Document specific class and also generic wizard common bits are moved to another class with the idea being this serves as common base for the remaining wizards.
Add unit tests to cover various combinations,
- uploading new document deletes existing one
- marking document as sensitive deletes any existing document
- marking document not available deletes any existing document
- marking document available but sensitive deletes any existing document
=> Add view to support editing of product document

caseworker/tau/forms.py, caseworker/tau/templates/tau/home.html, caseworker/tau/views.py, unit_tests/caseworker/tau/test_edit.py, unit_tests/caseworker/tau/test_forms.py, unit_tests/caseworker/tau/test_home.py
Adds the `is_wassenaar` field that is chucked to the API which sets the corresponding flag. 
It is a boolean field for now but as we introduce more regimes, it may end up becoming a `MultipleChoiceField`. Didn't want to jump the gun though so keeping it simple for now.
P.S. Also fixed a small bug in the first commit.
=> [LTD-2170] Regimes

exporter/applications/views/parties/end_users.py
One of the entry point for this wizard is when user edits the End-user
document availability option. That form is a single template view so it
uses a different template_name and the same is being used in the wizard
also which causes management form errors so explicity override again
to use the correct name in this wizard.
=> LTD-2266: Use the correct template for the wizard

.circleci/config.yml, ui_tests/caseworker/step_defs/test_enforcement.py
HAWK keys are environment specific so this PR enables the lookup of keys with an environment suffix in the format:
```
LITE_INTERNAL_HAWK_KEY_env
LITE_EXPORTER_HAWK_KEY_env
```
where `env` is substituted with the real environment name, e.g. `devdata`.
This is necessary so that the UI tests running in Circle can use the appropriate HAWK key for the environment being tested.
=> LTD-2274: Allow for env specific HAWK keys

exporter/goods/forms/firearms.py, unit_tests/exporter/goods/forms/test_firearms.py
Handles additional potential error messages that pertain to errors coming from the Python `datetime` module.
We will also full back to a user friendly message if there are any that we can't find an appropriate message for.
=> Expand validation messages for date field

ui_tests/exporter/conftest.py, ui_tests/exporter/features/submit_standard_application.feature, ui_tests/exporter/step_defs/test_standard_application.py
Add UI test that verifies the functionality of adding serial numbers later.
Application is initially submitted without adding serial numbers then user is prompted to add them using a banner.
The test checks for the presence of banner and after all serial numbers are provided then it checks that banner is no longer shown.
=> LTD-2201: Add UI test for adding serial numbers later

caseworker/tau/templates/tau/firearms_table.html, caseworker/tau/views.py
This is meant as a short-term fix to get links to certain documents in TAU2.0.
I think I painted myself in a corner with the `GoodsMultipleSelect` widget - in that it's template doesn't have `queue_pk` and `case_pk` and therefore I cannot do a `{% url "cases:document" queue_pk case_pk document.id %}`.
This alleviated the problem but as Kevin suggested, given that we are not planning on reusing the widget, we should just `{% include good_field.html %}` instead.
=> [LTD-2175] Links to documents

exporter/applications/services.py, exporter/applications/views/goods/add_good_firearm/views/summary.py
There is a point in time where an uploaded document is being virus scanned asynchronously.
It's highly likely that the user has been presented with a summary screen whilst this asynchronous task is occurring and as such the document won't have been marked safe yet. In this case we still want to display the name of the file even though we can't provide the download link.
This allows us to explicitly retrieve unsafe documents as well as safe ones but makes it an explicit flag to maintain backwards compatibility with anything that was expecting the old behaviour of unsafe documents being already filtered out.
=> Allow unsafe application documents to be retrieved

ui_tests/conftest.py, ui_tests/exporter/features/submit_standard_application.feature
This just skips the tests that will fail for now because trying to write a test that works with the feature switch is going to be too complex
What we will do for now is temporarily skip the test but have a fixed test waiting in the wings, when we first deploy the tests will be skipped but we can then follow up with deploying the fixed test
=> Skip tests that are affected by firearms 2.0 changes

caseworker/advice/templates/advice/case-tabs.html, caseworker/cases/helpers/case.py, caseworker/cases/views/main.py, caseworker/tau/templates/tau/case_tabs.html, caseworker/tau/templates/tau/home.html, caseworker/templates/case/slices/goods.html, ui_tests/caseworker/features/review_goods.feature
1. Put TAU 2.0 in a tab
2. Remove "Review goods" button (which links to TAU 1.0) on the case details tab
3. Remove checkboxes because they are useless without the "Review goods" button
Update - scratch (3) because we have "Edit goods flags" button as well, I have 2xC with Jess and it seems we need to keep the checkboxes for now.
=> [LTD-2369] Add product assessment tab and remove TAU 1.0 links

exporter/core/templates/core/form-wizard.html
The issue here was that the when the user would hit enter the browser would select the first submit button as the button to submit
In our case the first submit button is actually the "back" button
Wrapping the back button in its own separate form rectifies this issue
=> Make "enter" on keyboard take user to next step instead of previous

.circleci/config.yml, docker-compose.api.yml
While working on LTD-2359, realised that current lite-db image, that we use to run e2e tests, is hosted in GCP public registry. Although data is anonymised, we don't want to expose our database over public domain. So moving this to private gcp registry instead.
You can check in circle ci logs for this entry, that downloads image from newer location:
`Status: Downloaded newer image for eu.gcr.io/*******************/lite-db:latest`
=> use lite-db image within private gcp registry

.circleci/config.yml, docker-compose.api.yml, makefile, pipeline/Jenkinsfile
Current automated tests that we run in parallel of manual regression tests are running against LITE API latest master image. What we want is to run a specified FE release against a specified API release, using Release Tags that we create during deployment.
This PR fixes that issue. Process is that when we create a Github Release Tag, GCR event is triggered that builds an image that is tagged with the release string. This image will be used during the setup of UI e2e tests.
=> Fix Jenkins UI tests job to run against a specified LITE API

caseworker/templates/case/tabs/final-advice.html, caseworker/templates/case/tabs/team-advice.html, caseworker/templates/case/tabs/user-advice.html, exporter/templates/core/hub.html, unit_tests/caseworker/cases/test_templates.py
This change adds aria-label tags to call out disabled content as "unavailable" for screen readers.  As part of this work, some tests using beautiful soup needed updating to still work if the `class` attribute was missing from a tag.
=> [LTD-1990] Add aria-label tags to explain disabled content for screen readers

caseworker/cases/helpers/case.py
We want to remove I'm done button for LU users if the case is only
on Licensing unit post circulation queue. The current code uses
queue alias to determine this but it is checking whether alias is
valid before taking this value. This condition is actually not
required because the problem with this is that alias is not defined
for all queues, eg if it is on team leader to countersign queue for
which the alias is not defined then the current code filters this
out and removes the button in this case also which is not correct.
=> LTD-2483: Fix I'm done button for LU users

exporter/applications/services.py, exporter/applications/views/goods/add_good_firearm/views/add.py, unit_tests/exporter/applications/views/test_add_good_firearm_to_application.py
There is an issue where we are receiving a 400 back from the API, however the details of the error message are getting swallowed up due to the 400 only raising a generic exception
In the actual usage of this function in the wizard there is already a decorator in place to handle checking of the status code and raising a more appropriate error and log providing us with more information as to what actually happened
=> Remove raising potential exception coming from API when posting firearms on application

exporter/applications/views/goods/add_good_firearm/views/attach.py, exporter/applications/views/goods/add_good_firearm/views/payloads.py, unit_tests/exporter/applications/views/test_attach_firearm_to_application.py
This handles the case where a good was made prior to the low RFI changes and didn't have the relevant section 5 details attached to it.
This copies those details to the original good if required. Essentially it's upgrading these goods to contain information that wasn't necessary before.
=> Ltd 2601 error when attaching an existing product

caseworker/templates/case/slices/goods.html, ui_tests/caseworker/features/give_advice.feature
- Remove "status" column so users assess all products every time.
- Rename Rating => Control entry
- Rename ARS => Report summary
- Move flags column to the end so that Report summary comes first
- Hyperlink product name and remove "View full product details" link
=> LTD-2373: Product details table changes

caseworker/activities/templates/activities/notes-and-timeline.html, caseworker/activities/views.py, caseworker/advice/templates/advice/view-advice.html, caseworker/advice/templates/advice/view_countersign.html, caseworker/advice/templates/advice/view_my_advice.html, caseworker/advice/views.py, caseworker/cases/helpers/case.py, caseworker/cases/views/main.py, caseworker/tau/templates/tau/clear_assessments.html, caseworker/tau/templates/tau/home.html, caseworker/tau/views.py, caseworker/templates/includes/case-tabs.html, caseworker/templates/layouts/case.html
This fixes the case where the incorrect URL was being used for the product assessment page depending on what case page you were currently on.
The issue was that the main case details page had additional logic to decide what URLs were used when rendering the tabs, whereas the new pages we've created (that are separate from the original case details) used much simpler logic to display the tabs.
The old tabs would change the tab URL depending on some additional logic being run whereas the tabs for the new pages assumed that the URLs were always static for any given tab.
To solve this I've reused the logic and tabs template across all of the pages that display the case tabs.
=> Ltd 2647 fix advice tab destination

exporter/applications/helpers/task_lists.py, unit_tests/exporter/applications/views/test_application_task_list.py
The ultimate recipients task should be displayed whenever the user selects that their product will be onward exported
This is different from the original logic which used to just use the `is_good_incorporated` flag
This now checks the `is_onward_exported` flag as well but also retains the previous logic in cases where there are products that have been or are still made using just the original flag
=> Ltd 2803 onward exporter ultimate end user

core/builtins/custom_tags.py, unit_tests/caseworker/cases/test_templates.py, unit_tests/core/builtins/test_custom_tags.py
The original function was catering for some eventualitites that we've now removed:
- the quantity and unit are always on the good_on_application model
- these values are never null
- all units can have their ending `s` removed to make the singular
=> Update logic for displaying pluralise quantity

.circleci/config.yml, docker-compose.caseworker.yml, docker-compose.exporter.yml
The tests are run within a Docker container so we need to save these out to the host system to get them uploaded
=> Save screenshot artifacts on UI test failures

ui_tests/caseworker/pages/application_page.py
This is to hopefully solve an intermittent UI test.
In the case notes UI there is a button that is not enabled until text is input. My guess is that this isn't being enabled quickly enough for the tests so I've changed the wait to explicitly wait for the button to be enabled before it's clicked.
=> Wait for notes button to be enabled before progressing with tests

exporter/applications/views/goods/add_good_component/views/add.py, exporter/applications/views/goods/add_good_firearm/views/add.py, exporter/applications/views/goods/add_good_material/views/add.py, exporter/applications/views/goods/add_good_platform/views/add.py, exporter/applications/views/goods/add_good_software/views/add.py, exporter/applications/views/goods/common/actions.py
We have code duplicated across multiple product wizards that handles logic for uploading the product document.
Through creating the wizards we have moved away from having individual chunks of logic in each wizard and moved over to creating `Action` classes that groups together the specific logic for a certain step or steps, however the product document code was never ported over to using an `Action` object. This pull request now rectifies this.
=> Refactor out product document upload into an action

caseworker/tau/forms.py, unit_tests/caseworker/tau/test_forms.py
The new regimes UI is behind a feature switch, however the TAU forms validation wasn't taking this into account and so when the new regimes field was missing it was still expecting a value to be posted and was causing a hidden error to occur.
This now changes the TAU forms to take this feature switch into account and correctly ignore the regimes field if it isn't meant to be present.
=> Stop regimes being a required field on TAU form if feature flag is off

caseworker/templates/case/pills/goods.html
Use the name of the product in the product hover over.
Description is no longer always included on a good so we need to use name instead.
=> Use name in product summary hover

caseworker/advice/services.py, unit_tests/caseworker/advice/test_services.py
The option to give recommendation is only available if the user's current queue matches with the queue the case is currently on. We match this based on queue alias.
As part of routing changes we added new queues so include their aliases in this check so that users processing a case on these queues can give their recommendation.
Also removed MOD-WECA alias which we no longer need.
=> LTD-2941: Enable MOD-DI Direct and FCDO CPACC users to give their recommendation

core/summaries/summaries.py, unit_tests/caseworker/tau/test_forms.py, unit_tests/core/summaries/test_summaries.py, unit_tests/exporter/applications/views/goods/test_good_detail_summary_check_your_answers.py, unit_tests/exporter/goods/views/test_software_product_details.py
Use old key for software product category.
We have updated the name from "software" to "technology" except for how the Good.item_category is stored and so this still needs to use the old key.
=> Ltd 3024 software summary page

caseworker/advice/templates/advice/case_detail.html
We are onboarding new OGD and they are expecting to see these additional details in the side panel when giving recommendation on a Case.
=> LTD-3021: Update side panel on Advice view to include regime and EUU document

exporter/applications/views/goods/common/edit.py, exporter/applications/views/goods/common/steps.py, exporter/applications/views/goods/component/views/edit.py, exporter/applications/views/goods/firearm/views/edit.py, exporter/applications/views/goods/material/views/edit.py, exporter/applications/views/goods/platform/views/edit.py, exporter/applications/views/goods/software/views/edit.py, exporter/core/wizard/steps.py, exporter/core/wizard/views.py, exporter/goods/services.py
This is the first part of probably a few PRs to refactor out how we handle wizards with a focus on consolidating functionality that's commonly reused into a new concept of a `Step`.
This first PR transitions three such forms over across all of the product types.
These three forms were picked as they are simple enough but also require `initial_data` changes, custom payload changes and `form_kwargs` changes which are the key things that we are trying to consolidate for reuse.
=> Edit view refactoring

caseworker/advice/services.py, unit_tests/caseworker/advice/test_services.py
Users from BEIS teams can give recommendation for the cases in their queues.
=> Enable Make recommendation button for BEIS teams

exporter/templates/includes/ecju-queries.html, unit_tests/conftest.py, unit_tests/exporter/applications/views/ecju_queries/test_ecju_query_team_name.py
GIVEN I am a user belonging the BEIS nuclear control team 
WHEN I navigate to a case
AND I click on the queries tab
THEN I am able to send a query to the exporter on the case 
AND my name is displayed as “BEIS Nuclear”
-----
*note*: I wonder if we have to do this more than twice if it would be worth having a `display_name` field or similar for team names?
=> LTD-3051: shorten BEIS Nuclear team name

caseworker/advice/forms.py
There is a tiny typo on the below screen (in the queue ‘FCDO Cases to Review’). Licensing Unit is written ‘Licencing Unit’ but should be ‘Licensing Unit’.
=>  LTD-3099-typo 

caseworker/advice/templates/advice/assessed_products.html, caseworker/advice/views.py
The queue variable being used in the template was wrong in one place, this now uses the correct queue variable throughout and also changes this in the view context to make it consistent.
=> Use correct queue variable in template

exporter/applications/forms/parties.py, exporter/goods/forms/common.py, exporter/goods/forms/firearms.py, exporter/goods/forms/goods.py, exporter/organisation/forms.py, lite_content/lite_exporter_frontend/goods.py, lite_content/lite_exporter_frontend/strings.py, unit_tests/exporter/applications/views/test_add_good.py
Please see parent issue for full details: LTD-3196
Wherever we have guidance text accompanying a file upload, we should make clear to the user that only certain file types are accepted.
=> LTD-3210 Update guidance text for file uploads to include list of acceptable file types

docker-compose.yml
This enables caseworker and exporter to build correctly on M1 macs
=> Specify platform linux/amd64 in docker-compose

caseworker/templates/includes/case-row-flags.html, caseworker/templates/includes/case-row.html, caseworker/templates/queues/cases.html, lite_content/lite_internal_frontend/cases.py, unit_tests/caseworker/queues/test_templates.py
On the 'all cases view'
Remove the 'Products' flags column and put the flags into the 'Flags' column
https://uktrade.atlassian.net/jira/software/c/projects/LTD/boards/204?modal=detail&selectedIssue=LTD-3188
=> LTD-3188: combine product and regular flags column

caseworker/queues/views.py, caseworker/templates/queues/cases.html, unit_tests/caseworker/queues/test_views.py
Add tabs beneath the filters on the cases views (both all cases and for specific queues), one tab shows all cases (with whatever filters have been applied) the other tab shows cases that have an ECJU Query that has NOT been responded to by the user.
***NOTE: this PR is just for the tabs, and a PR to add the `count` to the deselected tab will be upcoming. (as well as potentially no longer 'hiding' cases with open queries on the queue search)***
corresponding API PR to apply the query param= https://github.com/uktrade/lite-api/pull/1247 
all cases view:
team queue view:
=> View cases with open queries tab

caseworker/queues/services.py, caseworker/queues/views.py, caseworker/templates/queues/cases.html, core/client.py, ui_tests/caseworker/features/queues.feature, ui_tests/caseworker/pages/case_list_page.py, ui_tests/caseworker/step_defs/test_queues.py, unit_tests/caseworker/queues/test_views.py
waiting on https://github.com/uktrade/lite-frontend/pull/1049  on the frontend and this API PR to merge so that the e2e tests can pass https://github.com/uktrade/lite-api/pull/1249#pullrequestreview-1253367975 
This PR adds the `count` of cases for the unselected tab on the queues view.
=> LTD-3189 open queries count

caseworker/queues/views.py, caseworker/templates/queues/cases.html, caseworker/templates/queues/search-tabs.html, lite_content/lite_internal_frontend/cases.py, ui_tests/caseworker/features/queues.feature, ui_tests/caseworker/pages/case_list_page.py, ui_tests/caseworker/step_defs/test_queues.py, unit_tests/caseworker/queues/test_views.py
[LTD-3239](https://uktrade.atlassian.net/jira/software/c/projects/LTD/boards/204?modal=detail&selectedIssue=LTD-3239)
The frontend for the cases/queues view is going to have several tabs that aim to filter out cases. We have already introduced the 'all cases' and 'open queries' tabs, but now that one more is being added ('my cases') we need to change the way the logic for filtering is handled (it's not either/or anymore).
[Together with this backend PR](https://github.com/uktrade/lite-api/pull/1260) I'm proposing:
_on the frontend_
1. instead of a param for each tab (e.g. `only_open_queries`) we have a param whose value is the selected tab e.g. `selected_tab=open_queries`
2. in the view, to get a count for each tab, we the tab names and make a HEAD request to get the count like we do …
=> LTD-3239: Add a 'my cases' tab/filter

core/feedback/urls.py
This fixes the warning shown below:
```lite-frontend-caseworker-1               | ?: (urls.W002) Your URL pattern '/thanks/' [name='thanks'] has a route beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.```
=> Fix url pattern warning

caseworker/assets/styles/components/_cases.scss, caseworker/cases/forms/case_assignment.py, caseworker/cases/services.py, caseworker/cases/urls.py, caseworker/cases/views/case_assignments.py, caseworker/templates/case/remove-case-assignment.html, caseworker/templates/case/slices/summary.html, lite_content/lite_internal_frontend/cases.py, unit_tests/caseworker/cases/views/test_case_assignments.py
This change adds the ability for case adviser assignments to be removed from a case.  It depends on the lite-api PR: https://github.com/uktrade/lite-api/pull/1276
Screenshots can be found in a comment on the Jira ticket: https://uktrade.atlassian.net/browse/LTD-3234
=> [LTD-3234] Add case adviser removal functionality to case detail page

docs/pull_request_template.md
add a suggested template to prompt more detail in a PR.
Should be auto available once merged into master. Documentation: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
=> add PR template

caseworker/assets/styles/components/_activity_updates.scss, caseworker/assets/styles/components/_all.scss, caseworker/templates/includes/case-row.html, caseworker/templates/queues/cases.html, lite_content/lite_internal_frontend/cases.py
add recent activity column to cases page
-enhanced cases templates to include extra data from the api
compared getting data via api using several queries and this appeared to be the quickest when run on local environment.
We needed last 2 audit activities per case but the case_id could be an action object or target object. Alternatives tried:
using union to get correct results from the fb
using filter to get last 2 activities per action and target (total 4) and filtering down to 2
a few different methods of massaging the data after retrieving results
=> add case activity to cases page

caseworker/cases/views/main.py, caseworker/external_data/services.py, caseworker/templates/case/denial-for-case.html, unit_tests/caseworker/cases/test_views.py, unit_tests/caseworker/conftest.py
[Ticket](https://uktrade.atlassian.net/jira/software/c/projects/LTD/boards/204?modal=detail&selectedIssue=LTD-3294) 
The Denials search was only returning the first 10 results, this adds pagination to the view. 
Relies on this API change for the e2es to pass: https://github.com/uktrade/lite-api/pull/1291
=> [LTD-3294] add pagination to denials search

caseworker/advice/templates/advice/case_detail.html
This change updates the display of serial numbers in the advice side panel to only show the list of numbers if there is at least one serial number present, otherwise it shows `Not added yet`.
The way this is done is by reusing the serial numbers template tag that is used elsewhere in the advice app.
Therefore the new if statement logic for this template satisfies the criteria for display given in the ticket, namely:
```
We’re currently showing serial numbers for all sub-firearm category products (so things like accessories where we don’t capture serial numbers on the application form') but it should just be:
firearms
ammunition
components for ammunition
components for firearms
```
=> LTD-3324 Update serial number message in case detail template

caseworker/templates/queues/cases.html
This fix ensures that the "Case updates"/"Case allocation" headers are in the correct order.
Screenshots can be seen on the jira; https://uktrade.atlassian.net/browse/LTD-3355
=> [LTD-3355] Fix queue view header ordering

core/forms/templates/forms/filter_radios.html
This change fixes up the new case officer allocation page.  The page was raising a ValueError; https://sentry.ci.uktrade.digital/organizations/dit/issues/71096/?environment=uat&project=153&query=is%3Aunresolved
This is because we have a strict staticfiles manifest and the leading "/" character was throwing this manifest off.  Locally - with `DEBUG=True` - our staticfiles lookups are more permissive.
https://uktrade.atlassian.net/browse/LTD-3361
=> [LTD-3361] Fix case officer allocation

caseworker/queues/views.py, unit_tests/caseworker/queues/test_views.py
There is some logic on both the front [and backend](https://github.com/uktrade/lite-api/blob/dev/api/cases/views/search/views.py#L114) around whether cases with open queries should be `hidden` on a queue view. With the introduction of different tabs adding different rules this logic is getting a bit confusing.
This PR is to put in a quick a fix for the issue where the `cases to review/all cases` tab count was including cases that should be hidden when the user is on a different tab, and hopefully clarifies the rules around when we should be 'hiding' open queries. 
There's logic in two places on the API around the `include_hidden` param - maybe the API should handle it more, and the frontend only pass 'true' for hidden if it's on the form? 
I would suggest as this maybe isn't a priority …
=> [LTD-3354] show correct tab count for 'all_cases' tab

caseworker/assets/styles/components/_activity_updates.scss, caseworker/queues/views.py, caseworker/templates/includes/case-row.html, unit_tests/caseworker/queues/test_views.py
This change fixes the case updates column for queue view as follows;
- Boldifies the "Last Action"/"Previous Action" spans.
- Makes the HTML more semantic by using one `<li>` per update.
- Shows `additional_text` for each update if it exists.
- Limits both `additional_text`/`text` for each update to show up to two lines.
- Adds tests.
**Update;**  There's also a fair chunk of overlap with the work ongoing here with some extra content tweaks in https://uktrade.atlassian.net/browse/LTD-3365 - so I've absorbed those changes in to the final commit.
Screenshots can be found here; https://uktrade.atlassian.net/browse/LTD-3364
=> [LTD-3364] Fix queue view limit case updates lines

caseworker/cases/helpers/case.py, caseworker/queues/views.py, caseworker/templates/includes/case-row.html, unit_tests/caseworker/conftest.py, unit_tests/caseworker/queues/test_views.py
When I am on the Licensing Unit pre-circulation OR Licensing Unit post-circulation queues
And I’m looking at the list of cases
And a case has an assigned case officer
And no assigned case advisers 
Then I only see the information for the assigned case officer
And NOT the information for case advisers 
When I am on any other queue
Then I see the information for BOTH the case advisers and case officer
[Link to story](https://uktrade.atlassian.net/jira/software/c/projects/LTD/boards/204)
=> Hide the 'Not allocated' message for unassigned case advisers on LU Post/Pre-circ

tests_common/functions.py, ui_tests/caseworker/conftest.py, ui_tests/caseworker/features/give_advice.feature, ui_tests/caseworker/features/routing_rules.feature
Add the new report summary prefix into the existing happy path UI test (MOD approve advice and routing rule journeys) to exercise that in addition to the report summary subject.
[LTD-3321](https://uktrade.atlassian.net/browse/LTD-3321)
[LTD-3321]: https://uktrade.atlassian.net/browse/LTD-3321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added prefix into the MOD approve advice journey

lite_forms/templatetags/custom_tags.py, unit_tests/caseworker/cases/test_views.py, unit_tests/lite_forms/templates/test_custom_tags.py
We encountered a bug in the denials search, where duplicate keys were
being removed in the pagination as it was converting the params to a
regular dict. This commit uses a QueryDict which allows for duplicate
params.
[Link to story](https://uktrade.atlassian.net/jira/software/c/projects/LTD/boards/204?modal=detail&selectedIssue=LTD-3356)
=> LTD-3294: enable duplicate keys in pagination

caseworker/tau/views.py, unit_tests/caseworker/tau/test_edit.py
This bug was caused by a TAU assessment being saved prior to the prefix/subject work. This meant that the code was expecting a subject (since it is mandatory in an assessment) but there was not one due t it predating the change.
This PR contains a test that demonstrated the bug and the change to fix it.
Also in this a TODO was resolved in the happy path test that was missed during the main piece of work.
[LTD-3392](https://uktrade.atlassian.net/jira/software/c/projects/LTD/boards/204?modal=detail&selectedIssue=LTD-3392)
[LTD-3392]: https://uktrade.atlassian.net/browse/LTD-3392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ltd 3392 report summary subject bug

caseworker/templates/includes/case-row.html, unit_tests/caseworker/queues/test_views.py
if a case officer is not assigned on an case/ on any queue it will show
as 'Not allocated'
[Link to story](https://uktrade.atlassian.net/jira/software/c/projects/LTD/boards/204?modal=detail&selectedIssue=LTD-3398)
=> LTD-3400: fix case officer display for LU

caseworker/templates/includes/case-row-flags.html
This fixes the issue where case level flags were not hidden by the flag expander; they were missing a required class.
https://uktrade.atlassian.net/browse/LTD-3402
=> Ensure case-level flags are hidden in flag expander

ui_tests/caseworker/conftest.py
We have a flaky end-to-end test where, I believe, that after selecting the template the page is taking longer to return than our timeout allows
In this case I am increasing the timeout to hopefully make this test less flaky
In the long term we may want to look at whether there are other issues causing this page to be slow but we should see how this small change works before committing to more extensive work
=> Increase the timeout for form submission step in e2e tests

caseworker/advice/templates/advice/case_detail.html, unit_tests/caseworker/advice/views/test_select_advice_view.py
[LTD-3396](https://uktrade.atlassian.net/browse/LTD-3396)
This change fixes the serial numbers display bug by passing the correct object into the template.
In this context we should be using `good.firearm_details` and not `good.good.firearm_details` as the former relates to `good_on_application` and the latter relates to `good`.
Also, two tests are added to make sure the display is correct: when there are serial numbers present, they should display, and when they are not present and `serial_numbers_available` is `LATER`, then the message `Not added yet` should display in place of the serial numbers.
[LTD-3396]: https://uktrade.atlassian.net/browse/LTD-3396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-3324 Fix serial numbers display in select advice view

caseworker/assets/javascripts/tau/ars.js, caseworker/assets/styles/overrides/_autocomplete.scss, caseworker/tau/forms.py, docs/pull_request_template.md, unit_tests/caseworker/tau/test_forms.py
Fixed these bugs:
1. Could not edit a prefix to remove it.
2. No error displayed if an invalid value was added for prefix.
The latter was also solved for report summary.
[JIRA-3395](https://uktrade.atlassian.net/browse/LTD-3395)
=> Fix to allow user to clear the prefix during edit

caseworker/advice/templates/advice/view_my_advice.html, caseworker/tau/templates/tau/home.html, caseworker/tau/views.py, caseworker/templates/case/slices/summary.html, caseworker/templates/layouts/case.html, unit_tests/caseworker/activities/test_views.py, unit_tests/caseworker/advice/views/test_advice_view.py, unit_tests/caseworker/advice/views/test_edit_advice.py, unit_tests/caseworker/advice/views/test_view_ogd_advice.py, unit_tests/caseworker/cases/test_permissions.py, unit_tests/caseworker/tau/test_home.py, unit_tests/conftest.py, unit_tests/exporter/applications/views/conftest.py
The “allocate yourself” banner was showing on case sub-pages, for TAU, advice, and notes, even after you have allocated yourself to a case.  
This was happening because the rules `can_user_change_case` and `can_user_move_case_forward` are checked in several templates to decide whether to render buttons/forms and require a `user` key to be present in the context, which some didn't have.
This PR uses the already-present `current_user` from the caseworker `context_processor`, so we don't need to add or use a different value in these templates.
I don't know how useful the context-checking tests really are, but it was a quick way for me to check every view when developing. I've added some frontend-y tests to `test_permissions.py` - possibly have been optimised with parameters at the expense of …
=> LTD-3372: use `current_user` to check assessment permissions

caseworker/core/rules.py, unit_tests/caseworker/core/test_permissions.py
Hotfix into UAT which is blocking deployment for case allocation.
When we have multiple assigned users from a queue on a case the banner was persisting. This is because the code assumed only one list and return on the first iteration. We now loop through all assigned users for muliple queue until we have ex the exhausted the complete list
LTD-](https://uktrade.atlassian.net/browse/LTD-)](https://uktrade.atlassian.net/browse/LTD-3432
=> LTD-3432-banner-persisting-bug 

caseworker/assets/javascripts/tau/ars.js, caseworker/tau/forms.py, unit_tests/caseworker/tau/test_forms.py
This updates the validation for report summary to take into account whether the assessment is being marked as not requiring CLEs.
If no CLEs are required then the report summary subject can be blank.
[LTD-3421](https://uktrade.atlassian.net/browse/LTD-3421)
[LTD-3421]: https://uktrade.atlassian.net/browse/LTD-3421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ltd 3421 report summary validation

caseworker/tau/templates/tau/home.html
On the "Assessed Products" table a product with no report summary is showing up as "None". Change this to blank the field out instead.
[LTD-3439](https://uktrade.atlassian.net/browse/LTD-3439)
[LTD-3439]: https://uktrade.atlassian.net/browse/LTD-3439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Blank out report_summary field if it is None

caseworker/advice/services.py, caseworker/advice/templates/advice/advice_details.html, caseworker/advice/templates/advice/view-advice.html, caseworker/advice/views.py, unit_tests/caseworker/advice/views/test_countersign.py, unit_tests/caseworker/advice/views/test_countersign_view.py, unit_tests/caseworker/advice/views/test_view_my_advice_view.py, unit_tests/caseworker/conftest.py
Update the various advice views to display LU countersignatures where appropriate. This should be anywhere final advice is displayed if this is an LU case.
[LTD-3413](https://uktrade.atlassian.net/browse/LTD-3413)
[LTD-3413]: https://uktrade.atlassian.net/browse/LTD-3413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Multiple countersignatures for LU

caseworker/queues/views.py, caseworker/templates/layouts/case.html, unit_tests/caseworker/queues/test_views.py
When a user clicks the 'Allocate case' button from a case detail page,
we would like them to be returned to that case after they have completed
the journey to assign either a case officer or a case adviser.
This commit passes the `return_to` param from the button through the
different forms used.
[LTD-3407](https://uktrade.atlassian.net/browse/LTD-3407)
[LTD-3407]: https://uktrade.atlassian.net/browse/LTD-3407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-3407: return user to `return_to` url in allocate case journey

caseworker/tau/forms.py, caseworker/tau/templates/tau/edit.html, caseworker/tau/templates/tau/home.html, unit_tests/caseworker/tau/test_edit.py, unit_tests/caseworker/tau/test_home.py
This was producing malformed HTML (a form within a form) that eventually caused the submit button to be rendered in the wrong place after we moved it out of the crispy form
=> Stop crispy forms from generating its own form tag

caseworker/assets/javascripts/tau/ars.js, caseworker/assets/styles/overrides/_autocomplete.scss
Remove 'blur' on autoselected item.
Added proper copy. Fixed pointer.
Minimise the "empty" option if the prefix or subject dropdowns are empty.
[LTD-3416](https://uktrade.atlassian.net/browse/LTD-3416)
[LTD-3416]: https://uktrade.atlassian.net/browse/LTD-3416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Report Summary Improvements

ui_tests/exporter/features/edit_standard_application.feature
Ensure the 'edit' button is visible to exporters when an application is `under_review`
[LTD-3433](https://uktrade.atlassian.net/browse/LTD-3433)
[LTD-3433]: https://uktrade.atlassian.net/browse/LTD-3433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-3305: ui test to check `under_review` application has edit button

conf/base.py, core/middleware.py, unit_tests/core/middleware/test_http_error.py, unit_tests/core/middleware/test_no_cache.py, unit_tests/core/middleware/test_return_to.py, unit_tests/core/middleware/test_sso_introspection.py, unit_tests/core/middleware/test_x_robots_tag.py
There are many cases where we make a service call and then check for an invalid response by running `raise_for_status`. When this fails we then get a HTTPError thrown and this ends up in Sentry.
The problem with the above is that in some cases the API is returning a 400 _and_ some text in the payload that would be important for us to know about, however just surfacing the HTTPError ends up hiding the response we are getting from the API.
This adds a middleware that adds a logger call of the response text which will end up in the breadcrumbs of the Sentry exception when we receive these errors.
=> Http error middleware

caseworker/advice/templates/advice/advice_details.html, caseworker/advice/templates/advice/view-advice.html, caseworker/advice/views.py, unit_tests/caseworker/advice/views/test_consolidate.py, unit_tests/caseworker/advice/views/test_countersign.py, unit_tests/caseworker/advice/views/test_countersign_view.py, unit_tests/caseworker/advice/views/test_view_my_advice_view.py, unit_tests/caseworker/conftest.py
New message box for rejected countersignature detail. 
Refactoring to support this. 
Also removal of rejected countersignatures from the display of countersignatures in the advice view further down.
In addition, as per comments, we only show the accepted countersignatures if there were no rejections (i.e. the case where the caseworker accepts the advice but the supervisor rejects it will prevent the accepted countersignatures from being displayed to avoid confusion)
Detail in this ticket:
[LTD-3482](https://uktrade.atlassian.net/browse/LTD-3482)
[LTD-3482]: https://uktrade.atlassian.net/browse/LTD-3482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LU Countersignature Rework.

caseworker/advice/services.py, caseworker/advice/views.py, unit_tests/caseworker/advice/test_services.py, unit_tests/caseworker/advice/views/test_consolidate_edit.py
We added new put method in API to support updating of final level Advice. This is the consolidated advice by LU.
Previously updates were supported by that involved deleting existing objects and creating new ones in place of them instead of actually updating original objects. Previous method has unintended effects in terms of cascade deletes.
In this PR, FE is updated the use the new method for updating consolidated advice.
This is required for LU countersigning work hence restricted to LU team only to limit regressions (if any). It can easily be expanded to other advice levels/teams.
[LTD-3503](https://uktrade.atlassian.net/browse/LTD-3503)
[LTD-3503]: https://uktrade.atlassian.net/browse/LTD-3503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-3503: Use put method to update consolidated advice by LU

caseworker/advice/templates/advice/advice_details.html, caseworker/advice/templates/advice/approve-advice-details.html, caseworker/advice/templates/advice/group-advice.html, caseworker/advice/templates/advice/refuse-advice-details.html, caseworker/advice/templates/advice/view-advice.html, caseworker/assets/styles/components/notes_and_timeline/_case-note.scss, ui_tests/caseworker/pages/advice.py
Changed cookie banner to recommendation-and-decision, removed some inconsistent three quarters classes and fixed the border not appearing and being inline
* Good test case: GBSIEL/2022/0000203/P
[LTD-](https://uktrade.atlassian.net/browse/LTD-3353)
=> Cookie banner css removing padding when above 2000px

caseworker/advice/forms.py, caseworker/advice/templates/advice/advice_details.html, caseworker/advice/templates/advice/view_countersign.html, caseworker/advice/views.py, unit_tests/caseworker/advice/views/test_consolidate.py, unit_tests/caseworker/advice/views/test_countersign.py, unit_tests/caseworker/advice/views/test_countersign_edit.py, unit_tests/caseworker/advice/views/test_countersign_view.py
Previously we were not showing countersignatures where there is rejected advice in favour of a warning message that there is a rejection. This is fine for most use cases, but it is required that the countersigner can see any rejected advice (for example any rejected advice that they have made) in addition to any previous approved countersignatures.
This PR implements the updated designs in the ticket.
[LTD-3521](https://uktrade.atlassian.net/browse/LTD-3521)
[LTD-3521]: https://uktrade.atlassian.net/browse/LTD-3521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> New designs implemented

caseworker/assets/javascripts/tau/ars.js
This is a regression. You used to be able to blank out the report summary prefix and save. This ticket is to make that work again.
Issue is that caseworker would validate the prefix id against the value of the field to ensure they match, but when the prefix field was blanked out, the javascript would not blank out the prefix id and so cause the validation error. 
The fix explicitly blanks out the originalInput value when blanking out the prefix, to ensure that the prefix value and stored id match (as empty)
[LTD-3514](https://uktrade.atlassian.net/browse/LTD-3514)
[LTD-3514]: https://uktrade.atlassian.net/browse/LTD-3514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cannot blank out the report summary prefix.

caseworker/advice/templates/advice/view_countersign.html
As per designs it should read as 'Edit message to case officer'
[LTD-3537](https://uktrade.atlassian.net/browse/LTD-3537)
[LTD-3537]: https://uktrade.atlassian.net/browse/LTD-3537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-3537: Update button text to reflect the design

caseworker/assets/javascripts/case.js, caseworker/templates/layouts/case.html
Document title should be set to the subheader that the user has selected (defaulting to details)
"lite-tabs__tab--selected" is used to select the appropriate header and add an event listened to each header
Also moved the inline JS to a case.js file
[LTD-1688](https://uktrade.atlassian.net/browse/LTD-1688)
[LTD-1688]: https://uktrade.atlassian.net/browse/LTD-1688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Subheader in document title for case pages

caseworker/assets/styles/components/_cases.scss, caseworker/templates/includes/case-row.html
To either inline the status text or reduce grey space with styling.
Reducing grey space without client side css was not possible.
Inline text has been implemented but there were issues so a min width was implemented. Making the text inline caused the column width to increase regardless of overflow settings etc. The only known alternative css is to use an absolute position (so parent ignores child width) which renders overflow css pointless so not really an option.
At less than 900px screen width the status on 2 rows has minimal additional grey space and the other columns look a lot better for the extra real estate.
Less liked alternative solution: slice the text to a set length before rendering, ie. Final Review Seco..., but as in the example the actual status could be unclear .
Ideally …
=> inline status text for cases view

ui_tests/caseworker/features/give_advice.feature, ui_tests/exporter/features/licences.feature
Once the routing changes to activate LU Countersign routing is merged then we will re-enable them with fixes
=> Skip failing E2E tests temporarily

tests_common/api_client/sub_helpers/cases.py, ui_tests/caseworker/features/give_advice.feature, ui_tests/caseworker/pages/advice.py, ui_tests/caseworker/step_defs/test_give_advice.py, ui_tests/exporter/conftest.py, ui_tests/exporter/features/licences.feature
We temporarily disabled failing E2E tests to merge routing changes that activates Countersign rules.
They are all merged now so we can re-enable them.
The refuse test is still skipped because we need additional fix which we are doing it as a follow-up so it will be re-enabled later.
One of the exporter test is also skipped at the moment but we are adding fix in this PR (in progress) so will update the PR once that is ready.
=> Re-enable and fix failing E2E tests

ui_tests/caseworker/features/give_advice.feature, ui_tests/caseworker/pages/advice.py
This was skipped temporarily while releasing LU Countersigning changes. Additional steps added as required by routing.
=> Re-enable refusal test

exporter/licences/services.py, exporter/licences/views.py, unit_tests/exporter/licences/test_views.py
This fixes the paging on the licences page.
The issue was that the page parameter wasn't being passed through to the API correctly.
[LTD-3590](https://uktrade.atlassian.net/browse/LTD-3590)
[LTD-3590]: https://uktrade.atlassian.net/browse/LTD-3590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix paging for licences page

caseworker/cases/helpers/filters.py, unit_tests/caseworker/queues/views/test_cases.py
This updates the control list entry filter so that it's a free text field as opposed to an autocomplete input.
The autocomplete field was creating a select box which contained ~3000 control list entries. This select box was then being progressively enhanced via JS and it was this progressive enhancement that was causing some users' browsers to become unresponsive.
Our initial thoughts were to make this input smarter by getting it to do a realtime lookup of the CLE based on what the user was typing, however we decided it was more likely that the user already knew the exact CLE they were searching for so the extra work involved to make this input smarter is probably not worth the effort.
[LTD-3101](https://uktrade.atlassian.net/browse/LTD-3101)
[LTD-3101]: …
=> Switch control list entry filter to text input from autocomplete

exporter/goods/forms/common.py
As specified in the comments of the ticket, the subtitle was displaying the wrong values
=> LTD-3371 corrected subtitle

caseworker/queues/views/forms.py
Case filters now use django-form components so id is slightly different
=> Update CLE filter id in the unit test

caseworker/advice/services.py
There are merge conflicts when preparing staging release.
Merging `uat` onto `dev` to bring it in a state that we can merge without conflicts.
=> Merge UAT onto dev to resolve conflicts

caseworker/templates/includes/case-row.html, caseworker/templates/queues/cases.html
Fixes a bug in the queue view where Regime/Control list entry/Report summary columns would not be properly managed by the customiser component.  This was due to a rename of the keys during the original PR which was not applied everywhere properly.
=> Fix queue view customiser show/hide bug

caseworker/templates/includes/case-row.html, caseworker/templates/queues/cases.html
Fix an issue where the "Destination" column was not toggleable from the queue view customiser JS component.
=> Fix queue view customiser destination show/hide bug

caseworker/templates/users/mentions.html, caseworker/users/services.py, caseworker/users/urls.py, caseworker/users/views/users.py, unit_tests/caseworker/users/test_views.py
https://uktrade.atlassian.net/browse/LTD-3622
New screen to support user mentions.
For those evil eyed you will noticed this isn't Feature flagged. This is because of my new view of having smart feature flags where necessary (or i'm just being lazy). So my argument is no FF is needed because this is internal users only with no link you would have to guess the URL and even then the page would be empty because the creation is feature flagged.
=> LTD-3622-show-user-mentions-list-2

caseworker/advice/forms.py, caseworker/queues/views/forms.py, core/forms/layouts.py, core/forms/templates/forms/expanding_fieldset.html, ui_tests/caseworker/conftest.py, ui_tests/caseworker/features/give_advice.feature
This change hides some supplemental fields for the "Recommend an approval" page by placing them within a GDS "details" component.  This adheres to the designs in the Jira here; https://uktrade.atlassian.net/browse/LTD-3676
[LTD-3676](https://uktrade.atlassian.net/browse/LTD-3676)
[LTD-3676]: https://uktrade.atlassian.net/browse/LTD-3676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-3676] Rationalise approval screen

ui_tests/caseworker/conftest.py, ui_tests/caseworker/pages/application_page.py
This fixes flakiness in clicking the submit button during the case notes test and advice tests.  It swaps out selenium driver's `click()` for a javascript "scroll to"/"click"
=> Replace selenium submit clicks with JS

caseworker/activities/templates/activities/notes-and-timeline.html, caseworker/activities/views.py, unit_tests/caseworker/activities/test_views.py
This turns the routing tab in N&T into a filter for activity. 
Since this displays the correct text as per N&T and no live mentions data is required. 
https://uktrade.atlassian.net/browse/LTD-3705
=> LTD-3705-mentions-grouping 

caseworker/advice/rules.py, caseworker/advice/services.py, caseworker/advice/templates/advice/view-advice.html, caseworker/advice/templates/advice/view_my_advice.html, caseworker/advice/views.py, caseworker/cases/helpers/case.py, caseworker/core/context_processors.py, caseworker/core/rules.py, caseworker/queues/middleware.py, caseworker/queues/services.py, caseworker/tau/templates/tau/edit.html, caseworker/tau/templates/tau/home.html, caseworker/templates/case/slices/summary.html, caseworker/templates/case/tabs/additional-contacts.html, caseworker/templates/case/tabs/documents.html, caseworker/templates/case/tabs/ecju-queries.html, caseworker/templates/case/tabs/quick-summary.html, caseworker/templates/layouts/case.html, caseworker/users/middleware.py, conf/caseworker.py, unit_tests/caseworker/advice/test_rules.py, unit_tests/caseworker/advice/views/test_advice_view.py, unit_tests/caseworker/cases/views/test_external_data.py, unit_tests/caseworker/core/test_rules.py, unit_tests/caseworker/external_data/test_views.py, unit_tests/caseworker/queues/test_middleware.py, unit_tests/caseworker/users/test_middleware.py
This PR adds a button "Allocate to me and approve" to the new quick summary tab on the case detail page.  The quick summary tab is still feature flagged.
In order to re-use the logic for showing/hiding the "Make recommendation" button, it was necessary to absorb this logic in to django rules.  This meant the following changes;
- Logic for showing "Make recommendation" on the "view advice" template has been reworked such that there is a single predicate `can_user_make_recommendation` using a django rule.
- Previously, this logic was distributed throughout views/context helpers so the old logic has been extracted.
- It was necessary for the new rules function to be based on `user`, `case` AND `queue`.  Django rules functions can only take two arguments, so the decision was made to refactor …
=> [LTD-3673] Quick summary "allocate and approve" button

caseworker/advice/services.py, unit_tests/caseworker/advice/views/test_consolidate_edit.py
(LU) edited their recommendation and added conditions later on. Initially there was no conditions. These conditions were originally added by some other team (MoD) so they edited their final advice and added these conditions later.
If you add conditions then the advice type becomes PROVISO but in this case it is still as APPROVE which is why they are not showing up in the document
=> LTD-3696-Condition-bug-fix

caseworker/queues/middleware.py, unit_tests/caseworker/queues/test_middleware.py
Hotfix to resolve issue where logged out users would get a 500 error page when going to a queue page e.g. /queues/00000000-0000-0000-0000-000000000001/
Prior to this fix, the middleware would not handle an exception raised by `get_queue()` when the requesting user was logged out.
=> Ensure failed get_queue() call does not prevent user logins

caseworker/assets/styles/components/_cases.scss, caseworker/cases/helpers/case.py, caseworker/templates/case/tabs/quick-summary.html
This PR achieves two things;
- Adds a customiser to the quick summary page so that users can chose which rows to show/hide.
- Addresses feedback for the quick summary page from UCD review.
[LTD-3748](https://uktrade.atlassian.net/browse/LTD-3748)
[LTD-3672](https://uktrade.atlassian.net/browse/LTD-3672)
[LTD-3748]: https://uktrade.atlassian.net/browse/LTD-3748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LTD-3672]: https://uktrade.atlassian.net/browse/LTD-3672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-3748] Quick summary customiser and feedback

caseworker/templates/users/profile.html, ui_tests/caseworker/conftest.py
Various "give advice" E2E tests would occasionally fail in a weird spot after trying to click on a previously created case.  After some thorough debugging it seemed like the preceeding step to change team/queue was occasionally not being applied fully; so that the test would be looking for the case on the wrong queue.
This change firms up the "change team and queue" step so that it waits for the submission to complete and asserts that the team/queue was changed correctly.
=> Fix flaky E2E tests

caseworker/queues/views/cases.py, unit_tests/caseworker/queues/views/test_cases.py
Ensure that `return_to` parameter cannot continue growing on successive "Apply filters" calls on queue view page.
https://uktrade.atlassian.net/browse/LTD-3819
=> Limit queue view return_to parameter

caseworker/assets/javascripts/case-filters.js, caseworker/bookmarks/views.py, caseworker/queues/views/cases.py, caseworker/queues/views/forms.py, ui_tests/caseworker/features/review_goods.feature, ui_tests/caseworker/features/view_standard_application.feature, unit_tests/caseworker/bookmarks/test_views.py, unit_tests/caseworker/cases/views/test_case_bookmarks.py, unit_tests/caseworker/cases/views/test_case_filters.py, unit_tests/caseworker/queues/test_templates.py, unit_tests/caseworker/queues/views/test_cases.py
Adjust queue view filters "Case" accordion section as follows;
- Switch widgets for a number of inputs.
-  Add ability to filter by "Assigned queues" and "Permanent or temporary".
- Reword a number of filter field labels.
[LTD-3796](https://uktrade.atlassian.net/browse/LTD-3796)
[LTD-3796]: https://uktrade.atlassian.net/browse/LTD-3796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-3796] Queue view filters case

Pipfile.lock
Update Pipfile.lock to flush outdated `parse` dependency hash and allow CI tests to pass again.
=> Update Pipfile.lock to flush outdated dependency hash

caseworker/assets/javascripts/case-filters.js, caseworker/queues/views/forms.py, unit_tests/caseworker/queues/views/test_cases.py
Improve "Applicant" queue view filters accordion as follows;
- Drop "exporter site address" filter field.
- ~~Add "Organisation country" filter field (autocomplete); which depends on the following backend PR https://github.com/uktrade/lite-api/pull/1476~~
- Add "Shipping from" select field; maps to `goods_starting_point` on backend PR https://github.com/uktrade/lite-api/pull/1476
- Rename other applicant field labels.
[LTD-3798](https://uktrade.atlassian.net/browse/LTD-3798)
[LTD-3798]: https://uktrade.atlassian.net/browse/LTD-3798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-3798] Applicant filters

caseworker/queues/views/forms.py, unit_tests/caseworker/queues/views/test_cases.py
This change achieves the following;
- Removes unnecessary "Misc" section from queue view filters.
- Rationalises "Party" section in queue view filters (including adding ability to exclude cases with sanction/denial matches)
[LTD-3799](https://uktrade.atlassian.net/browse/LTD-3799)
[LTD-3799]: https://uktrade.atlassian.net/browse/LTD-3799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-3799] Parties filters

caseworker/bookmarks/services.py, caseworker/queues/views/cases.py, unit_tests/caseworker/bookmarks/test_services.py
This change fixes a bug where user's were unable to use saved filters on anything other than their default queue.  Saved filter links now use a base URL of the current request path.
[LTD-3856](https://uktrade.atlassian.net/browse/LTD-3856)
[LTD-3856]: https://uktrade.atlassian.net/browse/LTD-3856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-3856] Ensure bookmark links retain current queue

caseworker/queues/views/cases.py, unit_tests/caseworker/queues/views/test_cases.py
Ensure that `assigned_queues` filter is stripped out for searches on user team queues; this should only be possible for system queue searches.  The form does not show this field for system queues, but it was possible for a user to search by it on non-system queues by using a saved filter.  This has now been remedied.
[LTD-3857](https://uktrade.atlassian.net/browse/LTD-3857)
[LTD-3857]: https://uktrade.atlassian.net/browse/LTD-3857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-3857] Ensure assigned queues filter is only applied for system queue searches

caseworker/queues/views/cases.py, caseworker/templates/queues/case-filters.html, unit_tests/caseworker/queues/views/test_cases.py
Ensure that queue view filters submissions are always POST.  Add POST handling to view and redirect to GET with `csrfmiddlewaretoken` stripped out.
[LTD-3884](https://uktrade.atlassian.net/browse/LTD-3884)
[LTD-3884]: https://uktrade.atlassian.net/browse/LTD-3884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-3884] Ensure csrfmiddlewaretoken is not visible after queue view form submission

core/assets/javascripts/filter-bar.js
Re-instates the filter-bar javascript so that filters are hidden by default on a number of pages.  This was removed in error during saved filters work.
[LTD-3900](https://uktrade.atlassian.net/browse/LTD-3900)
[LTD-3900]: https://uktrade.atlassian.net/browse/LTD-3900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Re-instate erroneously removed javascript

caseworker/bookmarks/services.py, caseworker/queues/views/forms.py, unit_tests/caseworker/bookmarks/test_services.py, unit_tests/caseworker/queues/views/test_cases.py
Add ability for caseworkers to filter queue view cases by those which have a total value below the "Max total value" filter value.
[LTD-3827](https://uktrade.atlassian.net/browse/LTD-3827)
[LTD-3827]: https://uktrade.atlassian.net/browse/LTD-3827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-3827] Add max total value filter to queue view

makefile
Prints out the full report, including step names and error step, when running e2e tests
[LTD-3852](https://uktrade.atlassian.net/browse/LTD-3852)
[LTD-3852]: https://uktrade.atlassian.net/browse/LTD-3852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Show step names when outputting e2e report

caseworker/assets/javascripts/case-filters.js, caseworker/queues/views/cases.py, caseworker/queues/views/forms.py, unit_tests/caseworker/bookmarks/test_views.py, unit_tests/caseworker/cases/views/test_case_bookmarks.py, unit_tests/caseworker/cases/views/test_case_filters.py, unit_tests/caseworker/queues/test_templates.py, unit_tests/caseworker/queues/views/test_cases.py
- Adjust presentation of checkboxes in queue view party filters.
- Make queue view country filter an auto-completed multi-select.
[LTD-3899](https://uktrade.atlassian.net/browse/LTD-3899)
[LTD-3899]: https://uktrade.atlassian.net/browse/LTD-3899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-3899] Queue view parties filters amends

caseworker/cases/helpers/case.py, unit_tests/caseworker/cases/views/test_quick_summary.py
Ensure that report summary is displayed on quick summary page for a case where report summary is only recorded in the `GoodOnApplication.report_summary` field and NOT in the new prefix/subject fields.
[LTD-3904](https://uktrade.atlassian.net/browse/LTD-3904)
[LTD-3904]: https://uktrade.atlassian.net/browse/LTD-3904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-3904] Ensure report summaries for older cases show on quick summary page

caseworker/templates/case/tabs/quick-summary.html, ui_tests/caseworker/features/view_case_quick_summary.feature, ui_tests/caseworker/step_defs/test_view_case_quick_summary.py
Adds a simple E2E test for the new quick summary tab.
[LTD-3743](https://uktrade.atlassian.net/browse/LTD-3743)
[LTD-3743]: https://uktrade.atlassian.net/browse/LTD-3743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-3743] Add E2E test for quick summary page

caseworker/activities/templates/activities/includes/activity-entry-activity.html, caseworker/activities/templates/activities/includes/activity-entry-user.html, caseworker/activities/templates/activities/notes-and-timeline.html, caseworker/templates/case/tabs/quick-summary.html, caseworker/templates/includes/case-row.html
Ensure that different locations where we display Notes+Timeline activity entries use the same templates so that we have less repetition sprinkled throughout the codebase.
This fixes an issue where custom mentions presentation of activity entries was not being used for the quick summary page/queue view page.
[LTD-3792](https://uktrade.atlassian.net/browse/LTD-3792)
[LTD-3792]: https://uktrade.atlassian.net/browse/LTD-3792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-3792] Make activity entry presentation more DRY

caseworker/assets/styles/components/_cases.scss, caseworker/templates/case/tabs/quick-summary.html
Add numbering to product names on quick summary page; the ordering of products from the API is consistent across details/product assessment pages so these numbers tally.
[LTD-3843](https://uktrade.atlassian.net/browse/LTD-3843)
[LTD-3843]: https://uktrade.atlassian.net/browse/LTD-3843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-3843] Ensure quick summary product names are numbered

caseworker/queues/views/cases.py, caseworker/templates/external_data/denial-detail.html, caseworker/templates/queues/cases.html, unit_tests/caseworker/queues/views/test_cases.py
Achieves two things;
- Ensures that the back button on the denial detail page returns to the case detail tab rather than the quick summary tab.
- Improves the logic for whether the filters sidebar is visible by default on the queue view page; this should only show if the caseworker has applied some filtering. Previously, it would show if any GET parameters were present; so a user would go to the second page and the filters sidebar would pop open. 
[LTD-3952](https://uktrade.atlassian.net/browse/LTD-3952)
[LTD-3952]: https://uktrade.atlassian.net/browse/LTD-3952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-3952] Denials match back button

caseworker/bookmarks/services.py, caseworker/bookmarks/views.py, caseworker/queues/views/cases.py, caseworker/queues/views/forms.py, unit_tests/caseworker/bookmarks/test_services.py, unit_tests/caseworker/queues/test_templates.py
Now that we are instantiating the case filters form, potentially, multiple times to create bookmark descriptions this makes sure that we only need to retrieve API data once for countries and queues.
[LTD-3855](https://uktrade.atlassian.net/browse/LTD-3855)
[LTD-3855]: https://uktrade.atlassian.net/browse/LTD-3855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ltd 3855 saved filters form based part 4

codecov.yml
This is to ensure that codecov has collected the three expected coverage reports before it reports
In some cases it will report early which will show a significant dip in coverage against a PR
This change waits until there are three uploads which correspond to:
- exporter unit tests
- caseworker unit tests
- core unit tests
=> Update the number of builds required to report code coverage

caseworker/tau/templates/tau/ammunition_table.html, caseworker/tau/templates/tau/components_for_ammunition_table.html, caseworker/tau/templates/tau/firearms_accessory_table.html, caseworker/tau/templates/tau/product_summary_table.html, caseworker/tau/templates/tau/software_related_to_firearms_table.html
The `<th>` element should be used instead of `<td>` for table headers as screen readers use this.
[LTD-4027](https://uktrade.atlassian.net/browse/LTD-4027)
[LTD-4027]: https://uktrade.atlassian.net/browse/LTD-4027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4027 Fix table markup

caseworker/advice/constants.py, caseworker/advice/services.py, unit_tests/caseworker/advice/views/test_consolidate_edit.py
Currently when LU edits their recommendation (final-level) then we are updating all products as either approve/refuse depending on their decision. This includes NLR products also which means if application has any NLR products they will also be recorded as approve/refuse after they edit recommendation.
This is a problem as it is final level advice because they are no longer treated as NLR and they will be added to the licence document also.
Fix this by filtering NLR products and recording the type as NLR correctly for all NLR products. We have existing tests so update them to include NLR products.
[LTD-4042](https://uktrade.atlassian.net/browse/LTD-4042)
[LTD-4042]: https://uktrade.atlassian.net/browse/LTD-4042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …
=> LTD-4042: Consider NLR products when LU edits their recommendation

caseworker/queues/views/cases.py, caseworker/templates/layouts/base.html, caseworker/templates/queues/cases.html, unit_tests/caseworker/queues/views/test_cases.py
This is one of the DAC accessibility changes for the Page Titled requirement
[LTD-4049](https://uktrade.atlassian.net/browse/LTD-4049)
[LTD-4049]: https://uktrade.atlassian.net/browse/LTD-4049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4049 Fix page title for queue view when selected tab is changed

exporter/templates/core/hub.html, unit_tests/core/test_templates.py
Wrapping them in h2 tags helps screen reader to identify text boundaries correctly to make it accessible and separate introductory data with actual content.
[LTD-1984](https://uktrade.atlassian.net/browse/LTD-1984)
[LTD-1984]: https://uktrade.atlassian.net/browse/LTD-1984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-1984: Wrap introductory text in h2 tags for screen reader use

.circleci/config.yml
Cache pre-commit artefacts so they don't need to be redownloaded on each lint run.
=> Cache pre-commit cache in circleci runs

caseworker/queues/forms.py
When assigning LU case officer typing into the input field filters the options available for the users to select. This is not very clear for screen reader users so as per suggested solution update help text so that it clear for them before they start interacting with the input field.
[LTD-4026](https://uktrade.atlassian.net/browse/LTD-4026)
[LTD-4026]: https://uktrade.atlassian.net/browse/LTD-4026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4026: Update help text to clarify the functionality to screen reader users

caseworker/templates/case/slices/destinations.html
This is temporarily hiding this button to see if this solves the issue where the old countersigning method is used.
We believe that this button is only used to make changes to the flags so that LU countersigning kicks in, which is the old process.
At present we don't believe that this functionality is used for anything else but we are leaving the button commented out in case we need to bring this back quickly (or possibly someone can just edit the HTML via dev tools and use it if absolutely required).
[LTD-4011](https://uktrade.atlassian.net/browse/LTD-4011)
[LTD-4011]: https://uktrade.atlassian.net/browse/LTD-4011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Hide "edit destination flag" button

lite_forms/templates/forms-errors.html
In case of form errors keyboard focus should be taken to the error summary but because of a typo to the value of data-module field it is incorrectly taken to other elements on the page. This causes issues for screen reader users as they are not made aware of the error(s).
[LTD-4036](https://uktrade.atlassian.net/browse/LTD-4036)
[LTD-4036]: https://uktrade.atlassian.net/browse/LTD-4036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4036: Correct typo for data-module field to focus on error summary

core/cookies/templates/cookies/banner.html
It is a heading but not marked as such so screen readers cannot pick this up correctly
[LTD-4059](https://uktrade.atlassian.net/browse/LTD-4059)
[LTD-4059]: https://uktrade.atlassian.net/browse/LTD-4059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4059: Mark cookie banner heading correctly

caseworker/assets/javascripts/list-expander.js
As per recommended solution a hidden span is added to explain the purpose of the button.
[LTD-LTD-4068](https://uktrade.atlassian.net/browse/LTD-LTD-4068)
=> LTD-4068: Add accessible name for the button that expands list of flags

lite_forms/templates/components/pagination.html
Add accessible names for the page number links in pagination.
As per suggested solution also include this under `nav` section indicating screen reader users that this is used for navigation.
[LTD-4060](https://uktrade.atlassian.net/browse/LTD-4060)
[LTD-4060]: https://uktrade.atlassian.net/browse/LTD-4060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4060: Add accessible labels for the page number links in pagination

caseworker/assets/javascripts/queues-menu.js, caseworker/templates/queues/cases.html
Also do not switch focus to input element after clicking the link. This confuses screen reader users and doesn't allow them to navigate to the content.
[LTD-4062](https://uktrade.atlassian.net/browse/LTD-4062)
[LTD-4062]: https://uktrade.atlassian.net/browse/LTD-4062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4062: Remove content from the heading structure

caseworker/assets/styles/components/_flags.scss
The contrast ratio of these colors should atleast be 4.5:1, this is achieved by choosing darker background or changing text color.
Update the colors to the values specified by design team to get the required contract ratios.
[LTD-2021](https://uktrade.atlassian.net/browse/LTD-2021)
[LTD-2021]: https://uktrade.atlassian.net/browse/LTD-2021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-2021: Use high contrast colors for flags for improved accessibility

exporter/templates/core/hub.html
This was missed in previous iteration
[LTD-4072](https://uktrade.atlassian.net/browse/LTD-4072)
[LTD-4072]: https://uktrade.atlassian.net/browse/LTD-4072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4072: Add missing h2 for Applications tile

caseworker/cases/services.py, caseworker/cases/urls.py, caseworker/cases/views/generate_document.py, unit_tests/caseworker/cases/views/test_generate_document.py, unit_tests/caseworker/conftest.py, unit_tests/caseworker/queues/views/test_cases.py, unit_tests/caseworker/queues/views/test_queues_case_assignments.py
This change adds a new view to the caseworker frontend which calls the new API endpoint for sending generated documents to exporters (https://github.com/uktrade/lite-api/pull/1531)
This is not yet visible/callable by lite users; it will be wired up when we are ready to release the inform letter functionality.
[LTD-4056](https://uktrade.atlassian.net/browse/LTD-4056)
[LTD-4056]: https://uktrade.atlassian.net/browse/LTD-4056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-4056] View to send generated letters

caseworker/assets/styles/overrides/_back-link.scss
Back links are currently displayed in white color against a dark background. When they are cllicked the focus color is yellow and it makes it difficult to read as the text is white. To improve the contrast the text color is changed to black when the link is in focus.
[LTD-2022](https://uktrade.atlassian.net/browse/LTD-2022)
=> LTD-2022: Fix contrast of back links

ui_tests/caseworker/features/give_advice.feature
We have a change in lite-api to stop LU countersigning refused cases; https://github.com/uktrade/lite-api/pull/1534
This meant that the "lu refuse advice" E2E test broke.
This PR:
- Updates the test so that it works with the new lite-api feature branch
- Disables the test for now, so that we can merge lite-api
A follow-up PR will re-enable the test when we have merged the change to lite-api.
[LTD-3975](https://uktrade.atlassian.net/browse/LTD-3975)
=> [LTD-3975] Temporarily deactivate LU refuse advice UI test

caseworker/assets/javascripts/queues-menu.js
This is to make sure that the queue link is accessible via a keyboard and a blank href stops keyboard input.
[LTD-4109](https://uktrade.atlassian.net/browse/LTD-4109)
=> Set a href value for queue menu link

ui_tests/caseworker/features/give_advice.feature
Now API is updated (https://github.com/uktrade/lite-api/pull/1534), lu refuse advice UI test can be re-enabled.
[LTD-3975](https://uktrade.atlassian.net/browse/LTD-3975)
=> [LTD-3975] Re-activate LU refusal UI test after API update

ui_tests/caseworker/step_defs/test_give_advice.py
Fix flaky end-to-end step that selects refusal criteria. This waits for the element to be visible first before selecting it.
=> Wait for element when adding refusal criteria

caseworker/advice/views.py, caseworker/cases/views/advice.py, caseworker/cases/views/generate_document.py, unit_tests/caseworker/cases/views/test_generate_document.py
https://uktrade.atlassian.net/browse/LTD-4129
This is to hide the inform document from the finalisation screen.  Can't be feature flagged since we are looking to migrate documents away from this screen long term.
=>  LTD-4132-remove-inform-on-finialization-screen 

caseworker/advice/templates/advice/decision_documents.html, unit_tests/caseworker/advice/views/test_consolidate.py
Ensure that inform letter status field progresses from "Ready to send" to "Sent" and wire up generated document send functionality.
[LTD-3938](https://uktrade.atlassian.net/browse/LTD-3938)
=> [LTD-3938] Inform letter send

exporter/applications/views/parties/end_users.py, unit_tests/exporter/applications/views/parties/test_end_users.py
Extra change to fix a missing exporter page title left off LTD-4063. 
[LTD-4147](https://uktrade.atlassian.net/browse/LTD-4147)
[LTD-4147]: https://uktrade.atlassian.net/browse/LTD-4147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix PartyReuseForm page title

exporter/applications/rules.py, exporter/applications/views/common.py, exporter/templates/applications/application.html, unit_tests/conftest.py, unit_tests/exporter/applications/test_rules.py, unit_tests/exporter/applications/views/conftest.py, unit_tests/exporter/applications/views/test_appeal.py, unit_tests/exporter/applications/views/test_application_detail.py
Exporters can appeal a refusal decision within 28 days.
Provide an option in exporter dashboard to start the appeal process.
[LTD-4115](https://uktrade.atlassian.net/browse/LTD-4115)
=> LTD-4115: Add option to start appeal if an application is refused

caseworker/templates/teams/markdown-help.html
Addressee.name is referenced in the help with formatting/variable options
It looks like applicant.name was added in and has caused confusion as to why the applicant's name wasn't pulling through
[LTD-4108](https://uktrade.atlassian.net/browse/LTD-4108)
=> changed applicant to addressee

core/assets/styles/overrides/_panel.scss, exporter/applications/services.py, exporter/applications/urls.py, exporter/applications/views/common.py, exporter/templates/applications/appeal-confirmation.html, lite_forms/templates/confirmation.html, unit_tests/exporter/applications/views/test_appeal.py
Add a confirmation page for the exporter once they have appealed their refusal.
[LTD-4125](https://uktrade.atlassian.net/browse/LTD-4125)
[LTD-4125]: https://uktrade.atlassian.net/browse/LTD-4125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Display confirmation page after creating an appeal

exporter/applications/services.py, unit_tests/exporter/applications/views/test_appeal.py
Uses the correct API endpoint URL to get appeal details.
[LTD-4125](https://uktrade.atlassian.net/browse/LTD-4125)
[LTD-4125]: https://uktrade.atlassian.net/browse/LTD-4125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update URL for appeal endpoint

exporter/applications/rules.py, exporter/templates/applications/application.html, unit_tests/exporter/applications/test_rules.py
Fixes a bug where we display this button even after User started an appeal
[LTD-4157](https://uktrade.atlassian.net/browse/LTD-4157)
[LTD-4157]: https://uktrade.atlassian.net/browse/LTD-4157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4157: Appeal refusal button display checks

caseworker/cases/views/generate_document.py, unit_tests/caseworker/cases/views/test_generate_document.py
Ensure that sending an inform letter results in the correct wording displayed in the success message.  This makes use of a newly added "document" data structure in the "send generated document" endpoint as added in this companion PR: https://github.com/uktrade/lite-api/pull/1568
[LTD-4160](https://uktrade.atlassian.net/browse/LTD-4160)
[LTD-4160]: https://uktrade.atlassian.net/browse/LTD-4160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-4160] Improve message wording when inform letter sent

example.caseworker.env, example.exporter.env
This is a really minor nit - but it was preventing me using a script to do the setup.
Makes sure the lines that start "comment the above..." to be comments themselves, so one less config.
In this way, the settings still need fixing by the user, but we avoid anything that make python_dotenv complain it can't parse the file itself.
=> Parts of the example configs aren't parsable, convert those to comments.

caseworker/templates/case/slices/summary.html, lite_content/lite_internal_frontend/cases.py, unit_tests/caseworker/cases/views/test_case_details.py
Add sub-status to case details page.
At this point I've not added the link to actually change the status to keep this PR small. We should add another ticket and add this link separately.
[LTD-4175](https://uktrade.atlassian.net/browse/LTD-4175)
[LTD-4175]: https://uktrade.atlassian.net/browse/LTD-4175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add sub-status to case details page

Pipfile, Pipfile.lock
bandit(v1.6.2) requires Gitpython(v3.1.32) which has below vulnerability, https://github.com/uktrade/lite-frontend/security/dependabot/62
Upgraded bandit to 1.6.3 which uses a Gitpython(v3.1.36)
[LTD-4198](https://uktrade.atlassian.net/browse/LTD-4198)
[LTD-4198]: https://uktrade.atlassian.net/browse/LTD-4198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4198: Upgrade Gitpython to address a security issue flagged by dependabot

caseworker/templates/case/tabs/quick-summary.html
Minor fix to ensure that sub-status row is customisable on case quick summary page.
[LTD-LTD-4215](https://uktrade.atlassian.net/browse/LTD-LTD-4215)
=> [LTD-4215] Enable customisation of sub-status in case quick summary tab

caseworker/core/services.py, unit_tests/caseworker/cases/views/test_change_status.py
LU users have a requirement to manually set the status as 'Finalised' at the end of an appeal process.
By default 'Finalised' status cannot be set manually so allow this option only for LU users that have additional permissions which are checked in the API.
[LTD-4203](https://uktrade.atlassian.net/browse/LTD-4203)
[LTD-4203]: https://uktrade.atlassian.net/browse/LTD-4203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4203: Expose finalise status for LU users

caseworker/cases/forms/change_sub_status.py, unit_tests/caseworker/cases/views/test_change_sub_status.py
Use "None" as label for unsetting sub-status.
[LTD-4218](https://uktrade.atlassian.net/browse/LTD-4218)
[LTD-4218]: https://uktrade.atlassian.net/browse/LTD-4218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add "None" as the label for a blank sub-status on form

caseworker/templates/case/form.html
Set the back button for sub-status as the case details page.
This uses a base form template that I've changed the default to be the case details page as I think this will make the most sense for it in general, if anything deviates from that then it can be overridden explicitly there.
[LTD-4214](https://uktrade.atlassian.net/browse/LTD-4214)
[LTD-4214]: https://uktrade.atlassian.net/browse/LTD-4214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Set back link to details page for case form template

core/assets/styles/components/_case-note.scss, core/assets/styles/overrides/_checkboxes.scss, core/assets/styles/overrides/_form-group.scss, core/assets/styles/overrides/_radios.scss, package-lock.json, package.json
This upgrades lite-frontend to use govuk-frontend v4.8.0 which is a recent release for govuk-frontend including the crown logo changes.
The GOV.UK team released v5.0.0 after v4.7.0 so this was tried initially but as there are many breaking changes that may take time to resolve, we have opted for v4.8.0 which is the latest release for the 4.x series. 
[LTD-4702](https://uktrade.atlassian.net/browse/LTD-4702)
Below is my original draft PR description:
> My current plan to do the upgrade is to move lite-frontend through all major and minor (skipping patch) released versions of govuk-frontend, one version per commit, and seeing that the full test suite passes at each commit.
> 
> If there are no problems, then great.
> 
> If there are problems on a commit when it is tested, these can be fixed …
=> LTD-4702 Upgrade lite-frontend to use govuk-frontend v4.8.0

ui_tests/exporter/features/ecju_queries.feature, ui_tests/exporter/pages/application_page.py, ui_tests/exporter/step_defs/test_ecju_queries.py
This is a test scenario for the red dot notification persisting when the user has not yet responded to the query, and then being cleared when the query has been responded to.
[LTD-4683](https://uktrade.atlassian.net/browse/LTD-4683)
[LTD-4683]: https://uktrade.atlassian.net/browse/LTD-4683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add UI tests for exporter red dot notification persisting until responded 

exporter/applications/forms/end_use_details.py, exporter/applications/forms/export_details.py, exporter/applications/forms/route_of_goods.py
This fixes an issue that we noticed with certain exporter forms (lite_forms) where radios were not displaying correctly if one of the radio options had an associated textarea. Those forms had the class `govuk-radios--inline` set when the lite form was created, and removing this has fixed the issue. Other existing forms where that class was set but where the radio options were a simple choice (i.e. no textarea) have not been changed.
[LTD-4803](https://uktrade.atlassian.net/browse/LTD-4803)
[LTD-4803]: https://uktrade.atlassian.net/browse/LTD-4803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4803 Fix radios not showing correctly in exporter journey

core/client.py, unit_tests/core/test_api_client.py
The API uses the content disposition in case where we are sending streaming responses so we need to match that on the frontend.
[LTD-4668](https://uktrade.atlassian.net/browse/LTD-4668)
[LTD-4668]: https://uktrade.atlassian.net/browse/LTD-4668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Match API Hawk response when receiving streaming response from API

caseworker/advice/services.py, caseworker/advice/views.py, exporter/templates/includes/ecju-queries.html, unit_tests/caseworker/advice/views/test_advice_view.py, unit_tests/caseworker/conftest.py, unit_tests/conftest.py, unit_tests/exporter/applications/views/ecju_queries/test_ecju_query_team_name.py
As BEIS no longer exists, and the BEIS Chemical and BEIS Nuclear teams are now part of DESNZ, we need to change the queue names, team names, flag names shown to users in LITE.
Note that the lite-routing changes that enable this in [LTD-4764](https://uktrade.atlassian.net/browse/LTD-4764) changed the names but not the aliases. This means that there is code in lite-frontend which still use aliases such as `BEIS_NUCLEAR` which is as expected. 
[LTD-4824](https://uktrade.atlassian.net/browse/LTD-4824)
[LTD-4824]: https://uktrade.atlassian.net/browse/LTD-4824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LTD-4764]: https://uktrade.atlassian.net/browse/LTD-4764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
=> LTD-4824 Update DESNZ team, queue, flag names in frontend

caseworker/queues/views/forms.py, unit_tests/caseworker/queues/views/test_cases.py
Adds a filter for "Case type" to the queue view - to allow caseworkers to view F680s or SIELs.
=> [F680] Queue view case type filter

exporter/applications/helpers/check_your_answers.py, unit_tests/exporter/applications/views/conftest.py, unit_tests/exporter/applications/views/test_application_summary.py
This fixes an issue where ultimate end users were not showing in the exporter application summary ("Check your answers" page). 
For some applications where an exporter has added incorporated goods, in the good on application, it is possible that `is_good_incorporated` can be `False` but `is_onward_incorporated` can be `True`.
Previously the way that ultimate end users were toggled on and off for this page was just by checking the value of `is_good_incorporated`.
We would like to check for the presence of `application["ultimate_end_users"]` but as this can be unreliable (as we don't delete this data if an application is edited) it is best to check both of `is_good_incorporated` and `is_onward_incorporated`. If either of these booleans are true then we consider that the application has …
=> Fix ultimate end user missing from exporter application summary

caseworker/external_data/example.csv
I chose the columns based on the fields of the `DenialEntity` model: https://github.com/uktrade/lite-api/blob/dev/api/external_data/models.py#L30
Also I looked at the csv extract of real denials data I took from the spire replica to double check fields as well as understand what the data typically looks like.
[LTD-4895](https://uktrade.atlassian.net/browse/LTD-4895)
[LTD-4895]: https://uktrade.atlassian.net/browse/LTD-4895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4895 Rewrite existing example denial data csv

package.json
The desnz js file was not getting built and this was causing errors in prod e.g. [sentry link removed]
This change updates the `build_caseworker` script which is what generates the built js files, which should fix the issue once this makes its way to prod environment. We can test on UAT first by running through a DESNZ caseworker journey to verify this fixes the issue.
[LTD-4925](https://uktrade.atlassian.net/browse/LTD-4925)
=> Update build_caseworker script to build desnz js file

lite_content/lite_exporter_frontend/applications.py
[LTD-4946](https://uktrade.atlassian.net/browse/LTD-4926)
=> Ltd 4926 spell out ECJU in first use in lite

core/builtins/custom_tags.py, lite_content/lite_exporter_frontend/strings.py, unit_tests/core/builtins/test_custom_tags.py
This change ensures that third party/consignee document uploads are signalled as optional on the exporter application flow.
To prevent an erroneous "In progress" state on the consignee entry of the task list, the `get_parties_status_optional_documents` template tag was updated.  The addition to that tag is not ideal, but ideally we will have a much more programmatic/DRY way of doing task lists/completion statuses as we move more towards django forms in the exporter flows in future.
[LTD-4888](https://uktrade.atlassian.net/browse/LTD-4888)
[LTD-4888]: https://uktrade.atlassian.net/browse/LTD-4888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-4888] Ensure consignee/third party document upload is optional

caseworker/core/context_processors.py, caseworker/external_data/views.py, unit_tests/caseworker/external_data/test_views.py
These are the frontend changes required to enable the denials CSV upload functionality along with some minor edits.
There is a corresponding PR in lite-api.
[LTD-4896](https://uktrade.atlassian.net/browse/LTD-4896)
[LTD-4896]: https://uktrade.atlassian.net/browse/LTD-4896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4896 Add basic CSV upload functionality

caseworker/advice/services.py, caseworker/advice/templatetags/advice_tags.py, caseworker/advice/views.py, ui_tests/caseworker/features/give_advice/mod_approve_advice.feature, unit_tests/caseworker/advice/conftest.py, unit_tests/caseworker/advice/test_services.py, unit_tests/caseworker/advice/views/test_consolidate.py, unit_tests/caseworker/advice/views/test_consolidate_edit.py, unit_tests/caseworker/advice/views/test_view_ogd_advice.py, unit_tests/caseworker/advice/views/test_view_ogd_advice_countersign.py, unit_tests/caseworker/conftest.py
Use team field directly from the advice objects as opposed to looking up through the user.
This pairs with API changes that always store the team at a point in time instead of changing if the user changes team.
[LTD-4899](https://uktrade.atlassian.net/browse/LTD-4899)
[LTD-4899]: https://uktrade.atlassian.net/browse/LTD-4899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Filter advice by team not user.team

caseworker/external_data/example.csv
This adds the `entity_type` column to the example csv as we want users to be able to set this directly in their data upload. Also, the columns specific to Denial have been moved to the left and columns specific to DenialEntity have been moved to the right - this is what we did for our demo to them so we should reflect that in our example csv file.
[LTD-4949](https://uktrade.atlassian.net/browse/LTD-4949)
[LTD-4949]: https://uktrade.atlassian.net/browse/LTD-4949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4949 Update denials upload example csv

caseworker/advice/constants.py
Ensures that the "Move case forward" button appears for open applications after OGD offers advice.
=> [Crypto-OIELs] Crypto oiels fixup ogd move case forward

caseworker/core/context_processors.py, caseworker/external_data/urls.py, unit_tests/caseworker/external_data/test_views.py
This renames the denials upload url back to what we had before as it is no longer a hidden url but something we want to release to users. The Denial records link is also added back to the menu bar so that users can find their way to the Denials upload page.
[LTD-4948](https://uktrade.atlassian.net/browse/LTD-4948)
[LTD-4948]: https://uktrade.atlassian.net/browse/LTD-4948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4948 Add link to Denial records to caseworker menu bar

caseworker/cases/views/main.py, caseworker/templates/case/denial-for-case.html
https://uktrade.atlassian.net/browse/LTD-4993 
Adds Party Denial Details on the screen together with ability to highlight. Highlight is depended on API change which has a PR but it won’t break without that change.
=> LTD-4993-add-dn-highlighting-party-details 

exporter/core/organisation/forms.py
Change wording when registering a commerical org to make clear which SIC org should use
[LTD-4984](https://uktrade.atlassian.net/browse/LTD-4984)
[LTD-4984]: https://uktrade.atlassian.net/browse/LTD-4984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4984 clarify SIC usage for multiple SICs when registering a commercial org

caseworker/external_data/example.csv, caseworker/templates/case/denial-for-case.html, caseworker/templates/external_data/denial-detail.html, unit_tests/caseworker/cases/test_views.py
Change Entity Type to Party Type on denial matches page and denial details page, and in the CSV.  There is a corresponding API PR here: https://github.com/uktrade/lite-api/pull/1978
[LTD-4982](https://uktrade.atlassian.net/browse/LTD-4982)
[LTD-4982]: https://uktrade.atlassian.net/browse/LTD-4982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ltd 4982 change entity type label to party type

makefile
When running E2E tests the current timeout to wait for containers to come up is 5 min.
We have couple of data migrations recently related to Denials and adding new ones related to Report summaries which are pushing it over 5min limit. These migrations are already optimised as possible but we may exceeding the timeout slightly so increase the timeout to allow for these changes.
=> Add a longer grace period for bringing up containers in E2E tests

caseworker/assets/styles/components/_case-note.scss
Removing case notes transition animation.
Animations often cause flakiness during tests and it's also better for accessibility to not have animations if not necessary.
=> Removing case notes transition animation

tests_common/api_client/libraries/request_data.py, ui_tests/caseworker/features/organisation.feature, ui_tests/caseworker/step_defs/test_organisation.py
Allow company details test to specify unique company house number to allow the tests to fully pass.
=> Allow company details test to specify unique company house number

ui_tests/caseworker/pages/advice.py
Fix flaky test cases which manifest with errors about selecting refusal criteria.
>       And I click the recommendations and decision tab
>        And I click "Review and combine"
>        And I click refuse
>        And I click continue
>        And [FAILED] I select refusal criteria "1a, 1b, 1c, 1d, 1e, 1f"
It turns out that this is because selenium has sporadic issues with clicking the "refuse" radio button when it is "below the fold".  This is probably something to do with the way that our GDS styling positions the radio input/label.
This fix rectifies that issue by firstly scrolling to the bottom of the page in question before clicking the button, ensuring that the button is wholly visible within the browser view.
=> Fix flaky refusal E2E tests

exporter/core/organisation/forms.py
Minor change to error text on organisation sign-up.
Branch incorrectly labeled at 4987
[LTD-4978](https://uktrade.atlassian.net/browse/LTD-4978)
[LTD-4978]: https://uktrade.atlassian.net/browse/LTD-4978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-4978 change org signup region error text

caseworker/external_data/example.csv
removed spire_entity_id from example csv
Corresponding API PR: https://github.com/uktrade/lite-api/pull/1987
[LTD-5005](https://uktrade.atlassian.net/browse/LTD-5005)
[LTD-5006](https://uktrade.atlassian.net/browse/LTD-5006)
[LTD-5005]: https://uktrade.atlassian.net/browse/LTD-5005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LTD-5006]: https://uktrade.atlassian.net/browse/LTD-5006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-5005 and LTD-5006 remove spire_id and reference from CSV upload

conf/base.py, exporter/applications/forms/parties.py, exporter/core/constants.py, exporter/goods/forms/common.py, exporter/goods/forms/firearms.py, exporter/goods/forms/goods.py, exporter/organisation/forms.py, lite_content/lite_exporter_frontend/goods.py, lite_content/lite_exporter_frontend/strings.py, lite_forms/tests.py, unit_tests/exporter/applications/views/test_add_good.py
This updates the list of acceptable mime types in lite-frontend which is what is used to determine if an uploaded file is acceptable or not. This has been tested locally by uploading an odt document, and on the demo environment where I was able to upload an odt document as an exporter and then submit this application and see that the document can be downloaded from the caseworker side.
[LTD-4928](https://uktrade.atlassian.net/browse/LTD-4928)
[LTD-4928]: https://uktrade.atlassian.net/browse/LTD-4928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Allow ODT file uploads in exporter

exporter/templates/core/hub.html, lite_content/lite_exporter_frontend/hub.py
Removes the old link for guidance on LITE document digital signatures that showed at the top of the exporter hub page. This is being replaced by the new link in the "Help and support" tile: https://github.com/uktrade/lite-frontend/blob/dev/exporter/templates/core/hub.html#L169 
[LTD-5018](https://uktrade.atlassian.net/browse/LTD-5018)
[LTD-5018]: https://uktrade.atlassian.net/browse/LTD-5018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove link from exporter dashboard

exporter/core/organisation/validators.py, unit_tests/exporter/core/organisation/test_validators.py
This updates the website validation for exporter organisation registration to allow website URLs that don't have a URL scheme prefix e.g. "https://". This is because user research has shown that exporters will often type a website address that looks like "www.example.com" and this would cause the Django URL validator to throw a ValidationError as it is expecting something like "https://www.example.com" which is a full URL including the scheme prefix. 
Rather than change the form data that is entered, the value stored in LITE is kept the same, but the validator function has an extra step to check if the entered website string is a valid URL with the "https://" prefix added. If so, then the value is considered valid and no error is raised. …
=> Update website field validation

exporter/core/templates/goods/forms/common/help_with_control_list_entries.html, exporter/goods/forms/common.py
Adds hint text and updates the help text for the control list entry question in exporter to make it clearer to exporters what to do if their product does not have a control list entry.
[LTD-4987](https://uktrade.atlassian.net/browse/LTD-4987)
[LTD-4987]: https://uktrade.atlassian.net/browse/LTD-4987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Amend control list entry question

caseworker/cases/forms/denial_forms.py, caseworker/cases/views/denials.py, unit_tests/caseworker/cases/test_denials_view.py
This ensures that we aren't using the current page URL as the submission action which allows us to reset the paging params
[LTD-5058](https://uktrade.atlassian.net/browse/LTD-5058)
[LTD-5058]: https://uktrade.atlassian.net/browse/LTD-5058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add an explicit form action for denials search form

exporter/core/organisation/forms.py, exporter/core/organisation/validators.py, unit_tests/exporter/core/organisation/test_forms.py, unit_tests/exporter/core/organisation/test_validators.py
Previously the exporter organisation registration form was changed to allow incomplete URLs such as `example.com` to pass a custom validator used for the `website` field. However this still causes a problem when the data reaches the backend as the model and db uses `URLField` and so an error just appears in the backend instead.
With this change the custom validator is no longer used and instead a `clean_website` method does something similar for the `RegisterAddressDetailsBaseForm`, including that when a URL does not have a scheme prefix such as `https://`, the `clean_website` method prepends this to the form data and then this is checked using the standard Django URL validator, raising a `ValidationError` if it fails that validator. 
This is probably better than changing the backend and …
=> Add https to incomplete URLs in org registration

exporter/applications/forms/edit.py, exporter/applications/views/end_use_details.py, exporter/applications/views/parties/consignees.py, exporter/applications/views/security_approvals/views.py, exporter/templates/applications/consignee.html, exporter/templates/applications/security-approvals/security-approvals-summary.html, lite_content/lite_exporter_frontend/applications.py, lite_forms/templates/summary-list.html, lite_forms/views.py, tests_common/functions.py, ui_tests/exporter/conftest.py, ui_tests/exporter/features/submit_standard_application.feature, unit_tests/exporter/applications/views/parties/test_consignees.py, unit_tests/exporter/applications/views/security_approvals/test_security_approvals_views.py, unit_tests/exporter/applications/views/test_end_use_details.py
These changes are part of the Assisted Digital work to make parts of LITE Exporter easier to understand. Screenshots of the changes have been added to the ticket.
[LTD-5042](https://uktrade.atlassian.net/browse/LTD-5042)
[LTD-5042]: https://uktrade.atlassian.net/browse/LTD-5042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update exporter summary pages and button text

caseworker/cases/views/denials.py, caseworker/templates/case/denial-for-case.html, caseworker/templates/case/slices/destinations.html, core/assets/styles/components/_pagination.scss, core/builtins/custom_tags.py, core/templates/components/pagination.html, unit_tests/caseworker/cases/test_denials_view.py, unit_tests/core/builtins/test_custom_tags.py
Allow pagination to work with forms that have to send their payload via a post.
This in cases where the payload itself shouldn't be shared in the URL, as it would with a `get`, so this provides the means to do this via the current `pagination` template tag.
[LTD-5013](https://uktrade.atlassian.net/browse/LTD-5013)
[LTD-5013]: https://uktrade.atlassian.net/browse/LTD-5013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ltd 5013 allow pagination to post as forms

exporter/core/organisation/forms.py
This adds hint text to the website field in the exporter organisation registration form.
[LTD-5101](https://uktrade.atlassian.net/browse/LTD-5101)
[LTD-5101]: https://uktrade.atlassian.net/browse/LTD-5101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update org website field hint text

caseworker/tau/templates/tau/firearms_accessory_table.html, core/summaries/formatters.py, exporter/core/templates/goods/forms/common/help_with_ultimate_end-users.html, exporter/goods/forms/common.py, unit_tests/conftest.py, unit_tests/exporter/applications/views/goods/component/test_summary_component.py, unit_tests/exporter/applications/views/goods/firearm/test_summary_firearm.py, unit_tests/exporter/applications/views/goods/material/test_summary_material.py, unit_tests/exporter/applications/views/goods/platform/test_summary_platform.py, unit_tests/exporter/applications/views/goods/software/test_summary_software.py, unit_tests/exporter/goods/forms/test_common.py
The onward exported question has been changed to ask about ultimate end-users instead, as this is more correct. There are sometimes cases where a good is onward exported to an ultimate end-user in the same country, and the existing question wording means exporters cannot answer properly if that is their situation.
Because the question is still asking about goods being onward exported just in a different way, it seems fine to keep the `is_onward_exported` variable the same and not change that in other places. 
[LTD-5053](https://uktrade.atlassian.net/browse/LTD-5053)
[LTD-5053]: https://uktrade.atlassian.net/browse/LTD-5053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update is_onward_exported question text

.pre-commit-config.yaml
This adds a pre-commit hook to check and remove unused imports using autoflake. The setup is identical to the example given in the README for autoflake here: https://github.com/PyCQA/autoflake
This isn't associated with a Jira ticket, this is just solving an annoyance that is quite common where you make a quick change on a PR and then the only CI check to fail is the unused imports check.
=> Add autoflake unused imports pre-commit hook

exporter/core/organisation/forms.py
Updates the field label for SIC code as this should be spelled out in full on its first usage in LITE.
[LTD-5123](https://uktrade.atlassian.net/browse/LTD-5123)
[LTD-5123]: https://uktrade.atlassian.net/browse/LTD-5123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update SIC code text

.circleci/config.yml, docker-compose.api.yml
This change ensures that logs from the API container will be uploaded as a circleci artifact when running the E2E tests on circleci.
=> Ensure api container logs are saved as artifacts to E2E circleci jobs

exporter/applications/forms/parties.py, unit_tests/exporter/applications/forms/test_parties.py
Adds the same help text and validation to the end user website form and party website form (this means it will update for adding an ultimate end-user, third party, consignee) as was already done for the exporter org registration form. 
[LTD-5124](https://uktrade.atlassian.net/browse/LTD-5124)
[LTD-5124]: https://uktrade.atlassian.net/browse/LTD-5124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update party website forms to use same help text and validation

caseworker/templates/case/slices/freedom-of-information.html, core/builtins/custom_tags.py, unit_tests/caseworker/cases/test_templates.py
Updates the FOI question and answer shown in the case details tab in caseworker now that the SIEL declaration has been updated in exporter.
[LTD-906](https://uktrade.atlassian.net/browse/LTD-906)
[LTD-906]: https://uktrade.atlassian.net/browse/LTD-906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix FOI answer shown in case details tab

exporter/goods/common/views.py, unit_tests/exporter/goods/views/test_archive_restore.py
Fix back links on the confirmation page to point to product detail page.
[LTD-5159](https://uktrade.atlassian.net/browse/LTD-5159)
[LTD-5159]: https://uktrade.atlassian.net/browse/LTD-5159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-5159: Fix back links on Archive/restore confirmation pages

exporter/applications/forms/common.py, exporter/applications/rules.py, exporter/applications/templates/edit_application_form.html, exporter/applications/urls.py, exporter/applications/views/common.py, exporter/templates/applications/application.html, unit_tests/conftest.py, unit_tests/exporter/applications/forms/test_amendments.py, unit_tests/exporter/applications/test_rules.py, unit_tests/exporter/applications/views/conftest.py, unit_tests/exporter/applications/views/test_amendments.py, unit_tests/exporter/applications/views/test_edit_application.py
Major edit creates a new application by copying the current application. This is enabled for specific exporters and in such cases we ask for their confirmation before creating amendment. This PR adds this new confirmation page for these exporters.
All other exporters see existing confirmation page which follows existing way of doing major edits.
Add tests that check for each category and ensure they redirect to correct success urls in each case.
[LTD-5136](https://uktrade.atlassian.net/browse/LTD-5136)
[LTD-5136]: https://uktrade.atlassian.net/browse/LTD-5136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-5136: Add confirmation page when major edit is selected

exporter/templates/applications/applications.html, exporter/templates/applications/drafts.html, ui_tests/exporter/conftest.py, ui_tests/exporter/features/amendments/siel_amendments.feature, ui_tests/exporter/step_defs/amendments/test_siel_amendments.py
The test first creates a draft application and submits it.
It then initiates a major edit which creates a new application by copying the existing application.
Note that major edit is initiated from the `Submitted` status itself. Ideally would've been good to do it after assessments but that involves switching to caseofficer and pushing the case forward. As the main purpose of this test that we can trigger major edit and ensure we create a new one successfully this is done from the submitted status itself. 
Once we create amended application it checks that the previous application is superseded by this new application and that it cannot be edited.
The new application is ensured to be in draft state and ready for amendments.
Finally it also ensures products and party details match with the …
=> LTD-5130: Add BDD scenario for amending an application by copy

caseworker/templates/layouts/case.html, unit_tests/caseworker/cases/views/test_case_details.py
Adjusts copy for orange amendment banner in the caseworker application.  This banner is displayed when a case is superseded or when a case is an amendment of another case.
[LTD-5216](https://uktrade.atlassian.net/browse/LTD-5216)
[LTD-5216]: https://uktrade.atlassian.net/browse/LTD-5216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-5216] Adjust caseworker amendment banner copy

exporter/ecju_queries/ecju_forms.py, exporter/ecju_queries/ecju_views.py, unit_tests/conftest.py, unit_tests/exporter/applications/views/ecju_queries/test_ecju_query_respond.py
Ensure that the exporter RFI response page only shows a link to edit the application if the application itself is eligible for editing (e.g. a major edit can be invoked).
Additionally, this PR makes sure that the edit flow the exporter is taken to will be the "amend by copy" flow if the feature flag is switched on for the user.
[LTD-5257](https://uktrade.atlassian.net/browse/LTD-5257)
[LTD-5257]: https://uktrade.atlassian.net/browse/LTD-5257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-5257] Conditionally show edit link in RFI response page.

exporter/applications/services.py, exporter/applications/urls.py, exporter/applications/views/goods/common/edit.py, unit_tests/exporter/applications/views/goods/common/test_edit_existing_goods_on_application.py
A new endpoint is added that allows only updating of quantity/value of goods that are already added to an application.
Previously we were using a common url using which other fields can also be updated.
API PR: https://github.com/uktrade/lite-api/pull/2121
[LTD-5083](https://uktrade.atlassian.net/browse/LTD-5083)
[LTD-5083]: https://uktrade.atlassian.net/browse/LTD-5083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-5083: Use exporter specific endpoint to update quantity/value of existing goods on application

exporter/goods/common/base.py, exporter/goods/views.py, exporter/templates/goods/archived_goods.html, exporter/templates/goods/product-details.html, unit_tests/exporter/goods/views/test_archive_restore.py
Once a product is archived the path to view its details is,
Home -> Products list -> Archived products -> Product detail.
Update breadcrumbs links to reflect the same.
[LTD-5161](https://uktrade.atlassian.net/browse/LTD-5161)
[LTD-5161]: https://uktrade.atlassian.net/browse/LTD-5161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-5161: Update breadcrumbs on product details page if it is an archived product

exporter/applications/views/common.py, exporter/templates/applications/applications.html, unit_tests/exporter/applications/views/test_applications_list.py
Designs required displaying 'submitted by' column for archived applications.
This was missed in the initial change and fixed in this PR.
This field is missing in the serializer so API changes are also required.
https://github.com/uktrade/lite-api/pull/2129
Updated tests to also verify the data rather than just the count of applications.
[LTD-5287](https://uktrade.atlassian.net/browse/LTD-5287)
[LTD-5287]: https://uktrade.atlassian.net/browse/LTD-5287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-5287: Include submitted by column when displaying Archived applications

caseworker/templates/components/security-approvals.html, unit_tests/caseworker/cases/views/test_case_details.py
Displays exporter provided answer for ITAR controls status on the internal side.
Add unit test to checks values displayed on the template.
[LTD-5278](https://uktrade.atlassian.net/browse/LTD-5278)
[LTD-5278]: https://uktrade.atlassian.net/browse/LTD-5278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-5278: Playback ITAR controls status on the internal side

exporter/templates/core/hub.html
The URL was hardcoded and pointed to the UAT environment, so it has been changed to use a template tag instead.
[LTD-5328](https://uktrade.atlassian.net/browse/LTD-5328)
[LTD-5328]: https://uktrade.atlassian.net/browse/LTD-5328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix wrong exporter URL for document digital signatures

tests_common/api_client/sub_helpers/applications.py
Ensure E2E tests use new application change status endpoint now that we want to remove the legacy shared authentication endpoint.
[LTD-5301](https://uktrade.atlassian.net/browse/LTD-5301)
[LTD-5301]: https://uktrade.atlassian.net/browse/LTD-5301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-5301] Ensure E2E tests use new application change status endpoint

.circleci/config.yml
Make sure that API logs are always output even if previous steps have failed.
There are currently some end-to-end tests failing on a feature branch and it looks like the API isn't coming up, however there are no API logs being output and I think it may be because the failure stops that command from being run. This ensures that the command is always run.
=> Ensure API logs are always output

exporter/applications/helpers/check_your_answers.py, exporter/applications/views/common.py, unit_tests/exporter/applications/helpers/test_check_your_answers.py, unit_tests/exporter/applications/views/test_application_summary.py
https://uktrade.atlassian.net/browse/LTD-5284
Exporter fix for the licence template is on BE
This shows only where it matters in `ApplicationDetail` page where it should show only the one where Licence is required and have been assessed by TAU. 
In the `CheckYourAnswers` and `GoodsDetailSummaryCheckYourAnswers` it will stay how it was before so showing the ones added by Users.
=> LTD-5284-Fix-show-correct-cle

exporter/core/services.py, unit_tests/exporter/applications/views/conftest.py, unit_tests/exporter/applications/views/goods/component/test_edit_component.py, unit_tests/exporter/applications/views/goods/firearm/test_edit_firearm.py, unit_tests/exporter/applications/views/goods/material/test_edit_material.py, unit_tests/exporter/applications/views/goods/platform/test_edit_platform.py, unit_tests/exporter/applications/views/goods/software/test_edit_software.py, unit_tests/exporter/applications/views/test_add_good.py, unit_tests/exporter/conftest.py, unit_tests/exporter/goods/forms/test_common.py, unit_tests/exporter/goods/forms/test_forms.py, unit_tests/exporter/licences/test_views.py
This is dependent on this API change here: https://github.com/uktrade/lite-api/pull/2160/
This changes the exporter frontend to use the new exporter-specific CLEs endpoint.
[LTD-5381](https://uktrade.atlassian.net/browse/LTD-5381)
[LTD-5381]: https://uktrade.atlassian.net/browse/LTD-5381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update exporter app to use new CLEs list view

unit_tests/caseworker/conftest.py, unit_tests/caseworker/flags/test_views.py
Remove fixtures that aren't used that relate to flagging rules.
[LTD-5518](https://uktrade.atlassian.net/browse/LTD-5518)
[LTD-5518]: https://uktrade.atlassian.net/browse/LTD-5518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove unused flagging rule fixtures

caseworker/templates/organisations/organisation/members.html, unit_tests/caseworker/organisations/users/test_user_views.py
Internal users are unable to see the status of a member within an Organisation. 
Hence this PR allows status to be displayed to help assist LITE support to help with loggin issues.
=>  LTD-5539-cw-show-user-status 

lite_forms/templates/components/summary.html, unit_tests/caseworker/organisations/test_views.py
Remove markdown rendering in lite_forms summary component.
[LTD-5572](https://uktrade.atlassian.net/browse/LTD-5572)
[LTD-5572]: https://uktrade.atlassian.net/browse/LTD-5572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Stop displaying markdown on summary component

exporter/applications/views/security_approvals/forms.py, unit_tests/exporter/applications/views/security_approvals/test_security_approvals_edit_views.py, unit_tests/exporter/applications/views/security_approvals/test_security_approvals_forms.py
In the security approvals section of exporter app, the F1686 reference number needs to be optional. This updates the field so that `required=False` and updates the label to show it is an optional field.
[LTD-5592](https://uktrade.atlassian.net/browse/LTD-5592)
[LTD-5592]: https://uktrade.atlassian.net/browse/LTD-5592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Make F1686 reference number field optional

caseworker/core/rules.py, caseworker/templates/users/profile.html, caseworker/users/views/users.py, unit_tests/caseworker/core/test_rules.py, unit_tests/caseworker/users/test_views.py
https://uktrade.atlassian.net/browse/LTD-5603
This restricts the view profile and removes the change links so only a super-user or someone from Admin team can change roles and teams. 
This PR is more about injecting in the permissions for following PR which will restrict  the change profile screen. 
At the moment i've decided to keep this as a lite form but the change user profile screen may be easier to convert to a crispy_form at that point I will consider moving both  views.
=> LTD-5603-privilege-escalation-restrict-view-profile 

caseworker/queues/views/cases.py, caseworker/queues/views/forms.py, unit_tests/caseworker/queues/views/test_cases.py
Adds capability for excluding cases with certain flags from queue view search results.
**Note:** This depends on a companion lite-api PR: https://github.com/uktrade/lite-api/pull/2340
[LTD-5712](https://uktrade.atlassian.net/browse/LTD-5712)
[LTD-5712]: https://uktrade.atlassian.net/browse/LTD-5712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-5712] Add ability to exclude cases with certain flags from queue view

caseworker/advice/forms/approval.py, caseworker/advice/forms/edit.py, unit_tests/caseworker/advice/views/test_edit_advice.py, unit_tests/caseworker/advice/views/test_give_approval_advice_view.py
DESNZ multi page flow change only:
* 'Add licence conditions, instructions to exporter or footnotes (optional)' -> ‘Add licence conditions (optional)’
* Remove hint text "Add a licence condition (optional)" on proviso checkboxes
* Change page header from "Instructions for the exporter (optional)" -> ‘Add instructions to the exporter, or a reporting footnote (optional)'
[LTD-5725](https://uktrade.atlassian.net/browse/LTD-5725)
[LTD-5725]: https://uktrade.atlassian.net/browse/LTD-5725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-5727] Updated page headers and removed label

.circleci/config.yml, caseworker/advice/services.py, caseworker/advice/tests/test_services.py
Colin summarises the issue brilliantly here; https://teams.microsoft.com/l/message/19:c91f81450ae041028ed350e84de52e99@thread.tacv2/1734095933610?tenantId=8fa217ec-33aa-46fb-ad96-dfe68006bb86&groupId=eced0ad8-d420-418b-9e1a-1b3e26b68c46&parentMessageId=1734095933610&teamName=LITE%20DDaT%20Team&channelName=Licence%20conditions%20and%20DESNZ%20countersigning&createdTime=1734095933610
TLDR; We were "rolling up" advice from all MOD teams in to MOD-ECJU's advice at the point of LU consolidation **if there was advice present from MOD-ECJU on the case**.
The issue with this is that advice from MOD-DI is only consolidated by LU if it visited MOD-DI's "Indirect" queue.  MOD-DI direct advice would effectively be masked away incorrectly.  This could mean the potential for LU missing important …
=> [LTD-5739] Ensure MOD-DI advice is shown at consolidation regardless of MOD-ECJU advice

caseworker/queues/views/forms.py, unit_tests/caseworker/cases/views/test_case_bookmarks.py
Content tweaks as per ticket.
[LTD-5738](https://uktrade.atlassian.net/browse/LTD-5738)
[LTD-5738]: https://uktrade.atlassian.net/browse/LTD-5738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-5738] Content tweaks to queue view exclude flags filter

unit_tests/caseworker/test_template_tags.py
Add tests for variable highlight
[LTD-5574](https://uktrade.atlassian.net/browse/LTD-5574)
[LTD-5574]: https://uktrade.atlassian.net/browse/LTD-5574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add tests for variable highlight

lite_content/lite_internal_frontend/strings.py, lite_content/lite_internal_frontend/tests.py, lite_forms/templates/govuk-link-button.html, lite_forms/templatetags/custom_tags.py, unit_tests/conftest.py, unit_tests/lite_forms/templatetags/test_custom_tags.py
Ensure the govuk link button template tag doesn't need to use `mark_safe` and therefore will always correctly sanitised any information that is sent to it.
[LTD-5745](https://uktrade.atlassian.net/browse/LTD-5745)
[LTD-5745]: https://uktrade.atlassian.net/browse/LTD-5745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add tests for govuk link button template tag

caseworker/advice/forms/approval.py, unit_tests/caseworker/advice/views/test_give_approval_advice_view.py
Ensure that the new multiple licence conditions flow concatenates licence conditions with a line separator.
[LTD-5743](https://uktrade.atlassian.net/browse/LTD-5743)
[LTD-5743]: https://uktrade.atlassian.net/browse/LTD-5743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-5743] Add line separator to multiple licence condition concatenation

exporter/templates/core/registration/confirmation-registration-base.html, exporter/templates/core/registration/confirmation-registration-corporation-abroad.html, exporter/templates/core/registration/confirmation-registration-corporation-uk.html, exporter/templates/core/registration/confirmation-registration-individual-abroad.html, exporter/templates/core/registration/confirmation-registration-individual-uk.html, exporter/templates/core/registration/includes/registration-details-corporation.html, exporter/templates/core/registration/includes/registration-details-individual.html
For accessibility it is expected that there is one H1 heading element on the page and other H2 or smaller headings to make it clear to screen readers what the relative importance of information on the page is. The example here (https://design-system.service.gov.uk/styles/headings/) shows H2 headings should be used when the `govuk-heading-m` class is used. The style does not change as a result of changing H1 elements to H2 because that is set by the CSS class `govuk-heading-m`, so the change only impacts accessibility tools.
[LTD-5173](https://uktrade.atlassian.net/browse/LTD-5173)
[LTD-5173]: https://uktrade.atlassian.net/browse/LTD-5173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix headings hierarchy for accessibility tools

exporter/assets/scss/components/_hub.scss, exporter/templates/core/hub.html
Previously the app tiles for compliance and open licence returns were shown on screen, but disabled. As discussed in the ticket it is better to hide the tiles for now until we implement these features, as it is difficult to accessibly show disabled visual content.
[LTD-5177](https://uktrade.atlassian.net/browse/LTD-5177)
[LTD-5177]: https://uktrade.atlassian.net/browse/LTD-5177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Hide disabled cards in exporter hub

lite_forms/templates/components.html
This updates some input labels as the `for` attribute only works on a `<label>` element.
[LTD-5796](https://uktrade.atlassian.net/browse/LTD-5796)
[LTD-5796]: https://uktrade.atlassian.net/browse/LTD-5796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Change span to label so for attribute works

exporter/templates/applications/parties/third-parties.html, exporter/templates/applications/parties/ultimate-end-users.html
For both the Ultimate end-users and Third parties pages the changes include:
- Changing the Back link text to say 'Back'
- Making the 'Add a third party' or 'Add an ultimate end-user' buttons grey, i.e. secondary colour
- Adding a new button 'Save and continue' at the bottom which is green i.e. is primary colour and is the call to action on the page
[LTD-5809](https://uktrade.atlassian.net/browse/LTD-5809)
[LTD-5809]: https://uktrade.atlassian.net/browse/LTD-5809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update call to action buttons for Ultimate end-users and Third parties pages

caseworker/advice/constants.py, caseworker/advice/templatetags/advice_tags.py
Aim
Ensure front end can handle F680 approval when showing advice
[LTD-5804](https://uktrade.atlassian.net/browse/LTD-5804)
[LTD-5804]: https://uktrade.atlassian.net/browse/LTD-5804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-5804] add in f680 approval advice type

exporter/applications/views/parties/end_users.py
The back links were not working for the `add_end_user` and `set_end_user` views so this fixes that functionality.
[LTD-5811](https://uktrade.atlassian.net/browse/LTD-5811)
[LTD-5811]: https://uktrade.atlassian.net/browse/LTD-5811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix back links for end user questions

core/assets/styles/overrides/_all.scss, core/assets/styles/overrides/_fieldset.scss, core/common/forms.py, exporter/applications/forms/hcsat.py, exporter/applications/forms/parties.py, exporter/applications/views/goods/goods.py, exporter/core/organisation/forms.py, exporter/goods/forms/common.py, exporter/goods/forms/firearms.py, exporter/goods/forms/goods.py, exporter/goods/views.py, exporter/templates/applications/application-submit-success.html, unit_tests/exporter/applications/views/parties/test_end_users.py
The forms listed in the ticket have been updated to make use of the Fieldset component: https://design-system.service.gov.uk/components/fieldset/ via the Fieldset component in Crispy Forms GDS: https://crispy-forms-gds.readthedocs.io/en/latest/components/fieldset.html
A Fieldset component with a Legend serving as the title is considered an accessible way to structure single question forms; see the ticket and link above for more information.
Using DevTools you can see that there is now a `<fieldset>` element which wraps the form inputs and is given a name through the `<legend>` element, this means that the accessibility requirements for WCAG to label form inputs and to structure the page to make relations clear to the user can both be met.
Mostly this is done through the use of a new class …
=> Update fieldsets to group related elements

caseworker/cases/helpers/case.py, unit_tests/caseworker/cases/views/test_quick_summary.py
Fixes a bug where allocate and approve would use the legacy approval flow (which has now been paired back to FCDO-only).  This would result in non-FCDO OGDs getting FCDO's partial country approval flow.
The current team is now checked to ensure FCDO flow shows for FCDO and the new multi-step approvals flow shows for everybody else.
[LTD-5836](https://uktrade.atlassian.net/browse/LTD-)
[LTD-5836]: https://uktrade.atlassian.net/browse/LTD-5836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-5836] Ensure OGDs using allocate and approve button are taken to correct approval flow

exporter/templates/applications/additional-documents/additional-documents.html, exporter/templates/includes/case-notes.html
https://uktrade.atlassian.net/browse/LTD-5823
CTA added as per ticket
=> LTD-5823-cta-notes-additional-docs 

caseworker/advice/templates/advice/form_wizard.html, caseworker/advice/views/approval.py, caseworker/templates/core/form-wizard.html, unit_tests/caseworker/advice/views/test_give_approval_advice_view.py
To reinstate (or add) the case details panel into the new recommendation flow
[LTD-5859](https://uktrade.atlassian.net/browse/LTD-5859)
[LTD-5859]: https://uktrade.atlassian.net/browse/LTD-5859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-5859] - Reinstate case details panel in advice approval views

exporter/applications/services.py, exporter/applications/views/common.py, exporter/templates/applications/application.html, exporter/templates/applications/history.html, exporter/templates/applications/summary.html, ui_tests/exporter/features/amendments/siel_amendments.feature, ui_tests/exporter/step_defs/amendments/test_siel_amendments.py, unit_tests/exporter/applications/helpers/test_check_your_answers.py, unit_tests/exporter/applications/views/conftest.py, unit_tests/exporter/applications/views/ecju_queries/test_ecju_query_team_name.py, unit_tests/exporter/applications/views/test_amendments.py, unit_tests/exporter/applications/views/test_application_detail.py, unit_tests/exporter/applications/views/test_application_summary.py
https://uktrade.atlassian.net/browse/LTD-5817
Add a new view on the exporter application details. 
This utilises a new endpoint which extracts the history 
https://github.com/uktrade/lite-api/pull/2388
=> LTD-5817-add-application-history

caseworker/queues/views/forms.py, caseworker/templates/queues/cases.html, unit_tests/caseworker/cases/views/test_case_filters.py, unit_tests/caseworker/queues/views/test_cases.py
We are adding option to sort the case list in queue view. Initially users can sort based on submission date (newest first or oldest first).
Relevant API PR https://github.com/uktrade/lite-api/pull/2390
[LTD-5850](https://uktrade.atlassian.net/browse/LTD-5850)
[LTD-5850]: https://uktrade.atlassian.net/browse/LTD-5850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-5850: Add queue view sort options

caseworker/assets/styles/components/_all.scss, caseworker/assets/styles/components/_application-section.scss, caseworker/f680/templates/f680/case/detail.html, caseworker/f680/templates/f680/includes/answer.html, caseworker/f680/templates/f680/includes/application_section_fields.html
This change cleans up the display of the application question/answers on the F680 case details page;
- A uniform column width is used for the questions.
- Questions where no answer is present are hidden.
- Answers for fields with `datatype="list"` are displayed in a `<ul>`
[LTD-5921](https://uktrade.atlassian.net/browse/LTD-5921)
[LTD-5921]: https://uktrade.atlassian.net/browse/LTD-5921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-5921] Clean up presentation of question/answer sections for F680 details

caseworker/core/rules.py, caseworker/f680/templates/f680/case/detail.html, caseworker/f680/tests/test_views.py, caseworker/f680/urls.py, caseworker/f680/views.py, unit_tests/caseworker/core/test_rules.py
This PR adds a rudimentary "Move case forward" button when a case is on a team queue.
This also introduces a success message with a link; in order to allow the user to see where the case went after they have moved it forward.
[LTD-5949](https://uktrade.atlassian.net/browse/LTD-5949)
[LTD-5949]: https://uktrade.atlassian.net/browse/LTD-5949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-5949] F680 move case forward button

caseworker/cases/helpers/case.py
Noticed when working locally that various case views will error based on these new defaults with `TypeError unsupported operand type(s) for +: 'dict' and 'dict'`
This change remedies that issue.
=> Fix type error manifesting from appending lists

caseworker/core/rules.py, caseworker/f680/recommendation/forms/forms.py, caseworker/f680/recommendation/mixins.py, caseworker/f680/recommendation/services.py, caseworker/f680/recommendation/views.py, caseworker/f680/templates/f680/case/recommendation/form_wizard.html, caseworker/f680/templates/f680/case/recommendation/includes/recommendation_details_approve.html, caseworker/f680/templates/f680/case/recommendation/includes/recommendation_details_refuse.html, caseworker/f680/templates/f680/case/recommendation/recommendation.html, caseworker/f680/templates/f680/case/recommendation/recommendation_details.html, caseworker/f680/templates/f680/case/recommendation/select_recommendation_type.html, caseworker/f680/templates/f680/case/recommendation/view_my_recommendation.html, caseworker/f680/tests/conftest.py, caseworker/f680/tests/recommendation/test_views.py, caseworker/f680/tests/test_views.py, caseworker/f680/urls.py
Add option to make approval recommendation for F680.
This is based on recommendation flow for SIEL where user can either approve/refuse all. Currently only approve option is presented.
When making recommendation we pull approval text (picklists) corresponding to the team. User can optionally enter provisos etc and submit recommendation. We then show the given recommendation details.
Currently any user can make a recommendation but this needs to be enclosed in a rule which will be done in subsequent PRs. This is mainly to limit the size of PR.
The option is add recommendation is not exposed to the user. It can only be accessed using the URL.
[LTD-5948](https://uktrade.atlassian.net/browse/LTD-5948)
[LTD-5948]: https://uktrade.atlassian.net/browse/LTD-5948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
=> LTD-5948: Add option to make approval recommendation for F680 application

exporter/applications/licence_type_processors.py, exporter/apply_for_a_licence/enums.py, exporter/apply_for_a_licence/forms/triage_questions.py, exporter/apply_for_a_licence/urls.py, exporter/apply_for_a_licence/views.py, exporter/f680/licence_type_processors.py, exporter/f680/tests/test_views.py, exporter/f680/urls.py, exporter/f680/views.py, unit_tests/exporter/applications/views/test_apply_for_a_licence.py, unit_tests/exporter/apply_for_a_licence/test_urls.py, unit_tests/exporter/apply_for_a_licence/test_views.py
Delegate out the processing of the application type answer.
This is so that the logic about what to do with the application is in the django app of that application type.
[LTD-5994](https://uktrade.atlassian.net/browse/LTD-5994)
[LTD-5994]: https://uktrade.atlassian.net/browse/LTD-5994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Delegate out processing of licence type questions to separate apps

exporter/applications/constants.py, exporter/applications/forms/common.py, exporter/applications/licence_type_processors.py, exporter/applications/payloads.py, exporter/applications/urls.py, exporter/applications/views/common.py, exporter/apply_for_a_licence/urls.py, exporter/apply_for_a_licence/views.py, exporter/templates/applications/use-spire-application-type.html, ui_tests/exporter/pages/apply_for_a_licence_page.py, unit_tests/conftest.py, unit_tests/exporter/applications/forms/test_common.py, unit_tests/exporter/applications/views/test_apply_for_a_licence.py, unit_tests/exporter/apply_for_a_licence/test_urls.py
This moves out the logic for the SIEL application flow and puts it into the relevant SIEL application Django app.
This also switches it over to a Django form wizard from lite_forms.
[LTD-5996](https://uktrade.atlassian.net/browse/LTD-5996)
[LTD-5996]: https://uktrade.atlassian.net/browse/LTD-5996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Move SIEL application code into SIELs Django app

caseworker/assets/styles/styles.scss, caseworker/cases/helpers/tests/test_case.py, caseworker/f680/templates/f680/case/base.html, caseworker/f680/templates/f680/case/detail.html, caseworker/f680/templates/f680/case/summary.html, caseworker/f680/templates/f680/includes/application_section.html, caseworker/f680/templates/f680/includes/application_section_multiple.html, caseworker/f680/templates/f680/includes/application_section_single.html, caseworker/f680/templates/f680/includes/application_section_user_information.html, caseworker/f680/templates/f680/includes/summary.html, caseworker/f680/tests/test_views.py, caseworker/f680/urls.py, caseworker/f680/views.py, unit_tests/caseworker/cases/views/test_case_assignments.py, unit_tests/conftest.py
Depends on API PR: https://github.com/uktrade/lite-api/pull/2460
This change displays F680 security release requests and products on a new F680 summary tab on the caseworker application.
[LTD-5991](https://uktrade.atlassian.net/browse/LTD-5991)
[LTD-5991]: https://uktrade.atlassian.net/browse/LTD-5991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-5991] Add new F680 summary tab and display related models in tables

caseworker/f680/templates/f680/includes/application_section_fields.html, core/builtins/custom_tags.py, exporter/f680/application_sections/additional_information/tests/test_views.py, exporter/f680/application_sections/approval_details/tests/test_views.py, exporter/f680/application_sections/conftest.py, exporter/f680/application_sections/general_application_details/tests/test_views.py, exporter/f680/application_sections/supporting_documents/tests/test_views.py, exporter/f680/application_sections/user_information/tests/test_views.py, exporter/f680/application_sections/user_information/views.py, exporter/f680/application_sections/views.py, exporter/f680/payloads.py, unit_tests/conftest.py
Change the F680 application JSON contract so that `fields` is a dictionary as opposed to an array.  This allows us to have a much easier time with DRF serializer validation and additionally makes lookups much easier.
Companion API PR: https://github.com/uktrade/lite-api/pull/2462
[LTD-5993](https://uktrade.atlassian.net/browse/LTD-5993)
[LTD-5993]: https://uktrade.atlassian.net/browse/LTD-5993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-5993] Change F680 JSON contract for fields to be dict

exporter/f680/application_sections/additional_information/tests/test_views.py, exporter/f680/application_sections/approval_details/tests/test_views.py, exporter/f680/application_sections/general_application_details/tests/test_views.py, exporter/f680/application_sections/user_information/tests/test_views.py, exporter/f680/application_sections/user_information/views.py, exporter/f680/application_sections/views.py, exporter/templates/f680/summary.html
There are currently no back links on the first step of each of sections in the F680 exporter journey.  This PR looks to address this adding these links.  The backlink on the F680 draft application summary page has also been repaired so that it returns to the application list page (this follows the same convention set in SIEL application)
[LTD-6043](https://uktrade.atlassian.net/browse/LTD-6043)
[LTD-6043]: https://uktrade.atlassian.net/browse/LTD-6043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-6043 add backlinks to first wizard step

caseworker/f680/conftest.py, caseworker/f680/recommendation/tests/test_views.py, caseworker/f680/rules.py, caseworker/f680/templates/f680/case/base.html, caseworker/f680/tests/test_rules.py, caseworker/f680/tests/test_views.py
Users are only allowed to make recommendations if the case is in the correct status otherwise switching to this tab raises an exception.
Recommendation tab is hidden if it is not applicable for the given case status. Add unit tests for this.
Group rules unit tests under different classes.
=> LTD: Hide recommendations tab if the case status is not appropriate

caseworker/advice/templates/advice/advice_details.html, caseworker/advice/templatetags/advice_tags.py, unit_tests/caseworker/advice/views/test_consolidate.py, unit_tests/caseworker/advice/views/test_countersign.py, unit_tests/helpers.py
This fixes an issue where parties were displayed multiple times on the countersign page for advice that was given previously.
[LTD-6060](https://uktrade.atlassian.net/browse/LTD-6060)
[LTD-6060]: https://uktrade.atlassian.net/browse/LTD-6060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix displaying duplicated ultimate end users

core/builtins/custom_tags.py, unit_tests/core/builtins/test_custom_tags.py
Stop errors when someone has put the word "country" in the address field itself.
This was failing as there was an `in` lookup that assumed that the variable was always a dict but could have just been a string with the word "country" in it.
This resolves this and any other edge cases I could think of.
Ideally we should have a single format for addresses that everything adheres to instead of having a function that tries to handle a multitude of cases, but for this specific fix I chose just to fix it in this particular template tag.
[LTD-6082](https://uktrade.atlassian.net/browse/LTD-6082)
[LTD-6082]: https://uktrade.atlassian.net/browse/LTD-6082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Handle additional edge cases for address formatting

caseworker/f680/templates/f680/case/base.html, caseworker/f680/templates/f680/case/recommendation/includes/case_details.html, caseworker/f680/tests/test_views.py
It was hidden when the status is submitted as they don't really make recommendations but this behaviour is inconsistent.
Update case details in side panel to include `intended_use`
[LTD-6094](https://uktrade.atlassian.net/browse/LTD-6094)
[LTD-6094]: https://uktrade.atlassian.net/browse/LTD-6094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-6094: Display recommendations tab for all case statuses

caseworker/f680/outcome/forms.py, caseworker/f680/outcome/tests/test_views.py, caseworker/f680/outcome/views.py, caseworker/f680/templates/f680/case/outcome/includes/security_release_request_details.html
This adds some simple grouping of conditions to the existing outcome flow.  Conditions are aggregated/de-duplicated by text string - so that a MOD-ECJU user selecting to give outcomes to multiple security releases will have an aggregated condition text box to edit.
[LTD-6096](https://uktrade.atlassian.net/browse/LTD-6096)
[LTD-6096]: https://uktrade.atlassian.net/browse/LTD-6096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-6096] F680 outcome condition grouping

caseworker/f680/conftest.py, caseworker/f680/outcome/services.py, caseworker/f680/outcome/tests/test_views.py, caseworker/f680/outcome/views.py, caseworker/f680/rules.py, caseworker/f680/tests/test_rules.py
This change adds a success message when issuing outcomes.  The "Decide outcome" button permissions are also tightened, so that it will not show when outcomes for all security releases have been issued.
[LTD-6073](https://uktrade.atlassian.net/browse/LTD-6073)
[LTD-6073]: https://uktrade.atlassian.net/browse/LTD-6073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-6073] F680 outcomes success message

caseworker/f680/recommendation/tests/test_views.py, caseworker/f680/templates/f680/case/recommendation/clear_recommendation.html, caseworker/f680/templates/f680/case/recommendation/recommendation.html
Currently the option to clear recommendation is only available on ‘View my recommendation’ page. This is the page user is taken to after making a recommendation. If user navigates away then this option is not available.
[LTD-6119](https://uktrade.atlassian.net/browse/LTD-6119)
[LTD-6119]: https://uktrade.atlassian.net/browse/LTD-6119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-6119: Add clear recommendation option on the landing page

caseworker/f680/conftest.py, caseworker/f680/outcome/forms.py, caseworker/f680/outcome/services.py, caseworker/f680/outcome/tests/test_views.py, caseworker/f680/outcome/urls.py, caseworker/f680/outcome/views.py, caseworker/f680/rules.py, caseworker/f680/templates/f680/case/outcome/includes/outcomes_table.html
This change adds a "Clear" button to each row of the outcome table - so that MOD-ECJU are able to clear an outcome grouping after they have created it.
[LTD-6070](https://uktrade.atlassian.net/browse/LTD-6070)
[LTD-6070]: https://uktrade.atlassian.net/browse/LTD-6070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-6070] Add ability to clear F680 outcome records

caseworker/f680/conftest.py, caseworker/f680/outcome/constants.py, caseworker/f680/outcome/forms.py, caseworker/f680/outcome/services.py, caseworker/f680/outcome/tests/test_forms.py, caseworker/f680/outcome/tests/test_views.py, caseworker/f680/templates/f680/case/outcome/includes/outcomes_table.html, core/common/forms.py, core/common/validators.py
Security outcomes are typically valid for 24/48 months but we are not capturing this at the moment.
Update forms to have start date and duration so user can specify a valid 24/48 month period for each outcome.
Data model changes are in this PR https://github.com/uktrade/lite-api/pull/2508
[LTD-6140](https://uktrade.atlassian.net/browse/LTD-6140)
[LTD-6140]: https://uktrade.atlassian.net/browse/LTD-6140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-6140: Update Security outcome flow to capture validity dates

caseworker/cases/services.py, caseworker/f680/conftest.py, caseworker/f680/document/forms.py, caseworker/f680/document/tests/test_document_views.py, caseworker/f680/document/views.py, caseworker/f680/outcome/constants.py, caseworker/f680/rules.py, caseworker/f680/templates/f680/case/recommendation/recommendation.html, caseworker/f680/templates/f680/document/all_documents.html, exporter/templates/f680/application_detail.html
This change adds a "Finalise and publish to exporter" button to the "all documents" view.  This is wired up with the finalise endpoint (adjusted in PR https://github.com/uktrade/lite-api/pull/2507)
[LTD-6123](https://uktrade.atlassian.net/browse/LTD-6123)
[LTD-6123]: https://uktrade.atlassian.net/browse/LTD-6123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-6123] F680 finalise flow

.circleci/config.yml
Fix failing CI tests by forcing a cache update on pipenv dependency installation.
=> Fix e2e tests

caseworker/f680/templates/f680/includes/product_table.html
Show a value for `security_grading_other` in the product table on F680 summary page.
[LTD-6055](https://uktrade.atlassian.net/browse/LTD-6055)
[LTD-6055]: https://uktrade.atlassian.net/browse/LTD-6055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-6055] Show security grading other on F680 product table

caseworker/f680/outcome/forms.py
Make validity_start_date initial value evaluate at runtime instead of module-load
[LTD-6164](https://uktrade.atlassian.net/browse/LTD-6164)
[LTD-6164]: https://uktrade.atlassian.net/browse/LTD-6164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LTD-6164] Make validity_start_date initial value evaluate at runtime instead of module-load

caseworker/activities/views.py, caseworker/advice/views/views.py, caseworker/cases/helpers/case.py, caseworker/cases/views/main.py, caseworker/tau/views.py
Make the internal case details page work for Export Licence types.
I've additionally removed code that didn't pertain to Export Licences and SIELs for this view as we'll be implementing the F680s pattern moving forward.
There's also a bit of general refactoring of this view to tidy it up.
[LTD-6198](https://uktrade.atlassian.net/browse/LTD-6198)
[LTD-6198]: https://uktrade.atlassian.net/browse/LTD-6198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Make the internal case details page work for Export Licence types

caseworker/core/services.py, unit_tests/caseworker/core/test_services.py
After a better understanding of how the manual override for SIELs is used it seemed better to omit this option from f680s rather than supporting it from the outset.
[LTD-6199](https://uktrade.atlassian.net/browse/LTD-6199)
[LTD-6199]: https://uktrade.atlassian.net/browse/LTD-6199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-6199 - Remove the ability to manually set an F680 to finalised

caseworker/f680/document/tests/test_document_views.py, caseworker/f680/outcome/tests/test_views.py, caseworker/f680/recommendation/tests/test_views.py, caseworker/f680/tests/test_views.py, caseworker/f680/views.py, caseworker/picklists/enums.py, lite_content/lite_internal_frontend/picklists.py, unit_tests/caseworker/cases/views/test_case_assignments.py, unit_tests/caseworker/conftest.py
Users first need to create them to be able to select from the forms. If they don't create they will see a text box to enter the conditions manually.
Relevant API PR is https://github.com/uktrade/lite-api/pull/2560
[LTD-6181](https://uktrade.atlassian.net/browse/LTD-6181)
[LTD-6181]: https://uktrade.atlassian.net/browse/LTD-6181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LTD-6181: Retrieve F680 specific provisos when making recommendation
